// Code generated by "stringer -type=vmStatus,OpCode -output stringer.go"; DO NOT EDIT.

package vm

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[whyNot-0]
	_ = x[whyException-1]
	_ = x[whyReturn-2]
	_ = x[whyBreak-3]
	_ = x[whyContinue-4]
	_ = x[whyYield-5]
	_ = x[whySilenced-6]
}

const _vmStatus_name = "whyNotwhyExceptionwhyReturnwhyBreakwhyContinuewhyYieldwhySilenced"

var _vmStatus_index = [...]uint8{0, 6, 18, 27, 35, 46, 54, 65}

func (i vmStatus) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_vmStatus_index)-1 {
		return "vmStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _vmStatus_name[_vmStatus_index[idx]:_vmStatus_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[POP_TOP-1]
	_ = x[ROT_TWO-2]
	_ = x[ROT_THREE-3]
	_ = x[DUP_TOP-4]
	_ = x[DUP_TOP_TWO-5]
	_ = x[NOP-9]
	_ = x[UNARY_POSITIVE-10]
	_ = x[UNARY_NEGATIVE-11]
	_ = x[UNARY_NOT-12]
	_ = x[UNARY_INVERT-15]
	_ = x[BINARY_POWER-19]
	_ = x[BINARY_MULTIPLY-20]
	_ = x[BINARY_MODULO-22]
	_ = x[BINARY_ADD-23]
	_ = x[BINARY_SUBTRACT-24]
	_ = x[BINARY_SUBSCR-25]
	_ = x[BINARY_FLOOR_DIVIDE-26]
	_ = x[BINARY_TRUE_DIVIDE-27]
	_ = x[INPLACE_FLOOR_DIVIDE-28]
	_ = x[INPLACE_TRUE_DIVIDE-29]
	_ = x[STORE_MAP-54]
	_ = x[INPLACE_ADD-55]
	_ = x[INPLACE_SUBTRACT-56]
	_ = x[INPLACE_MULTIPLY-57]
	_ = x[INPLACE_MODULO-59]
	_ = x[STORE_SUBSCR-60]
	_ = x[DELETE_SUBSCR-61]
	_ = x[BINARY_LSHIFT-62]
	_ = x[BINARY_RSHIFT-63]
	_ = x[BINARY_AND-64]
	_ = x[BINARY_XOR-65]
	_ = x[BINARY_OR-66]
	_ = x[INPLACE_POWER-67]
	_ = x[GET_ITER-68]
	_ = x[PRINT_EXPR-70]
	_ = x[LOAD_BUILD_CLASS-71]
	_ = x[YIELD_FROM-72]
	_ = x[INPLACE_LSHIFT-75]
	_ = x[INPLACE_RSHIFT-76]
	_ = x[INPLACE_AND-77]
	_ = x[INPLACE_XOR-78]
	_ = x[INPLACE_OR-79]
	_ = x[BREAK_LOOP-80]
	_ = x[WITH_CLEANUP-81]
	_ = x[RETURN_VALUE-83]
	_ = x[IMPORT_STAR-84]
	_ = x[YIELD_VALUE-86]
	_ = x[POP_BLOCK-87]
	_ = x[END_FINALLY-88]
	_ = x[POP_EXCEPT-89]
	_ = x[HAVE_ARGUMENT-90]
	_ = x[STORE_NAME-90]
	_ = x[DELETE_NAME-91]
	_ = x[UNPACK_SEQUENCE-92]
	_ = x[FOR_ITER-93]
	_ = x[UNPACK_EX-94]
	_ = x[STORE_ATTR-95]
	_ = x[DELETE_ATTR-96]
	_ = x[STORE_GLOBAL-97]
	_ = x[DELETE_GLOBAL-98]
	_ = x[LOAD_CONST-100]
	_ = x[LOAD_NAME-101]
	_ = x[BUILD_TUPLE-102]
	_ = x[BUILD_LIST-103]
	_ = x[BUILD_SET-104]
	_ = x[BUILD_MAP-105]
	_ = x[LOAD_ATTR-106]
	_ = x[COMPARE_OP-107]
	_ = x[IMPORT_NAME-108]
	_ = x[IMPORT_FROM-109]
	_ = x[JUMP_FORWARD-110]
	_ = x[JUMP_IF_FALSE_OR_POP-111]
	_ = x[JUMP_IF_TRUE_OR_POP-112]
	_ = x[JUMP_ABSOLUTE-113]
	_ = x[POP_JUMP_IF_FALSE-114]
	_ = x[POP_JUMP_IF_TRUE-115]
	_ = x[LOAD_GLOBAL-116]
	_ = x[CONTINUE_LOOP-119]
	_ = x[SETUP_LOOP-120]
	_ = x[SETUP_EXCEPT-121]
	_ = x[SETUP_FINALLY-122]
	_ = x[LOAD_FAST-124]
	_ = x[STORE_FAST-125]
	_ = x[DELETE_FAST-126]
	_ = x[RAISE_VARARGS-130]
	_ = x[CALL_FUNCTION-131]
	_ = x[MAKE_FUNCTION-132]
	_ = x[BUILD_SLICE-133]
	_ = x[MAKE_CLOSURE-134]
	_ = x[LOAD_CLOSURE-135]
	_ = x[LOAD_DEREF-136]
	_ = x[STORE_DEREF-137]
	_ = x[DELETE_DEREF-138]
	_ = x[CALL_FUNCTION_VAR-140]
	_ = x[CALL_FUNCTION_KW-141]
	_ = x[CALL_FUNCTION_VAR_KW-142]
	_ = x[SETUP_WITH-143]
	_ = x[EXTENDED_ARG-144]
	_ = x[LIST_APPEND-145]
	_ = x[SET_ADD-146]
	_ = x[MAP_ADD-147]
	_ = x[LOAD_CLASSDEREF-148]
	_ = x[LIST_EXTEND-149]
	_ = x[DICT_UPDATE-150]
	_ = x[TUPLE_EXTEND-151]
	_ = x[CALL_FUNCTION_EX-152]
	_ = x[LIST_EXTEND_MAPPING-153]
	_ = x[BEFORE_ASYNC_WITH-154]
	_ = x[BEFORE_AWAIT-155]
	_ = x[GET_AITER-156]
	_ = x[GET_ANEXT-157]
	_ = x[SETUP_ASYNC_WITH-158]
	_ = x[WITH_CLEANUP_ASYNC-159]
	_ = x[FOR_ITER_AEXPR-160]
	_ = x[WITH_CLEANUP_FINISH_ASYNC-161]
}

const _OpCode_name = "POP_TOPROT_TWOROT_THREEDUP_TOPDUP_TOP_TWONOPUNARY_POSITIVEUNARY_NEGATIVEUNARY_NOTUNARY_INVERTBINARY_POWERBINARY_MULTIPLYBINARY_MODULOBINARY_ADDBINARY_SUBTRACTBINARY_SUBSCRBINARY_FLOOR_DIVIDEBINARY_TRUE_DIVIDEINPLACE_FLOOR_DIVIDEINPLACE_TRUE_DIVIDESTORE_MAPINPLACE_ADDINPLACE_SUBTRACTINPLACE_MULTIPLYINPLACE_MODULOSTORE_SUBSCRDELETE_SUBSCRBINARY_LSHIFTBINARY_RSHIFTBINARY_ANDBINARY_XORBINARY_ORINPLACE_POWERGET_ITERPRINT_EXPRLOAD_BUILD_CLASSYIELD_FROMINPLACE_LSHIFTINPLACE_RSHIFTINPLACE_ANDINPLACE_XORINPLACE_ORBREAK_LOOPWITH_CLEANUPRETURN_VALUEIMPORT_STARYIELD_VALUEPOP_BLOCKEND_FINALLYPOP_EXCEPTHAVE_ARGUMENTDELETE_NAMEUNPACK_SEQUENCEFOR_ITERUNPACK_EXSTORE_ATTRDELETE_ATTRSTORE_GLOBALDELETE_GLOBALLOAD_CONSTLOAD_NAMEBUILD_TUPLEBUILD_LISTBUILD_SETBUILD_MAPLOAD_ATTRCOMPARE_OPIMPORT_NAMEIMPORT_FROMJUMP_FORWARDJUMP_IF_FALSE_OR_POPJUMP_IF_TRUE_OR_POPJUMP_ABSOLUTEPOP_JUMP_IF_FALSEPOP_JUMP_IF_TRUELOAD_GLOBALCONTINUE_LOOPSETUP_LOOPSETUP_EXCEPTSETUP_FINALLYLOAD_FASTSTORE_FASTDELETE_FASTRAISE_VARARGSCALL_FUNCTIONMAKE_FUNCTIONBUILD_SLICEMAKE_CLOSURELOAD_CLOSURELOAD_DEREFSTORE_DEREFDELETE_DEREFCALL_FUNCTION_VARCALL_FUNCTION_KWCALL_FUNCTION_VAR_KWSETUP_WITHEXTENDED_ARGLIST_APPENDSET_ADDMAP_ADDLOAD_CLASSDEREFLIST_EXTENDDICT_UPDATETUPLE_EXTENDCALL_FUNCTION_EXLIST_EXTEND_MAPPINGBEFORE_ASYNC_WITHBEFORE_AWAITGET_AITERGET_ANEXTSETUP_ASYNC_WITHWITH_CLEANUP_ASYNCFOR_ITER_AEXPRWITH_CLEANUP_FINISH_ASYNC"

var _OpCode_map = map[OpCode]string{
	1:   _OpCode_name[0:7],
	2:   _OpCode_name[7:14],
	3:   _OpCode_name[14:23],
	4:   _OpCode_name[23:30],
	5:   _OpCode_name[30:41],
	9:   _OpCode_name[41:44],
	10:  _OpCode_name[44:58],
	11:  _OpCode_name[58:72],
	12:  _OpCode_name[72:81],
	15:  _OpCode_name[81:93],
	19:  _OpCode_name[93:105],
	20:  _OpCode_name[105:120],
	22:  _OpCode_name[120:133],
	23:  _OpCode_name[133:143],
	24:  _OpCode_name[143:158],
	25:  _OpCode_name[158:171],
	26:  _OpCode_name[171:190],
	27:  _OpCode_name[190:208],
	28:  _OpCode_name[208:228],
	29:  _OpCode_name[228:247],
	54:  _OpCode_name[247:256],
	55:  _OpCode_name[256:267],
	56:  _OpCode_name[267:283],
	57:  _OpCode_name[283:299],
	59:  _OpCode_name[299:313],
	60:  _OpCode_name[313:325],
	61:  _OpCode_name[325:338],
	62:  _OpCode_name[338:351],
	63:  _OpCode_name[351:364],
	64:  _OpCode_name[364:374],
	65:  _OpCode_name[374:384],
	66:  _OpCode_name[384:393],
	67:  _OpCode_name[393:406],
	68:  _OpCode_name[406:414],
	70:  _OpCode_name[414:424],
	71:  _OpCode_name[424:440],
	72:  _OpCode_name[440:450],
	75:  _OpCode_name[450:464],
	76:  _OpCode_name[464:478],
	77:  _OpCode_name[478:489],
	78:  _OpCode_name[489:500],
	79:  _OpCode_name[500:510],
	80:  _OpCode_name[510:520],
	81:  _OpCode_name[520:532],
	83:  _OpCode_name[532:544],
	84:  _OpCode_name[544:555],
	86:  _OpCode_name[555:566],
	87:  _OpCode_name[566:575],
	88:  _OpCode_name[575:586],
	89:  _OpCode_name[586:596],
	90:  _OpCode_name[596:609],
	91:  _OpCode_name[609:620],
	92:  _OpCode_name[620:635],
	93:  _OpCode_name[635:643],
	94:  _OpCode_name[643:652],
	95:  _OpCode_name[652:662],
	96:  _OpCode_name[662:673],
	97:  _OpCode_name[673:685],
	98:  _OpCode_name[685:698],
	100: _OpCode_name[698:708],
	101: _OpCode_name[708:717],
	102: _OpCode_name[717:728],
	103: _OpCode_name[728:738],
	104: _OpCode_name[738:747],
	105: _OpCode_name[747:756],
	106: _OpCode_name[756:765],
	107: _OpCode_name[765:775],
	108: _OpCode_name[775:786],
	109: _OpCode_name[786:797],
	110: _OpCode_name[797:809],
	111: _OpCode_name[809:829],
	112: _OpCode_name[829:848],
	113: _OpCode_name[848:861],
	114: _OpCode_name[861:878],
	115: _OpCode_name[878:894],
	116: _OpCode_name[894:905],
	119: _OpCode_name[905:918],
	120: _OpCode_name[918:928],
	121: _OpCode_name[928:940],
	122: _OpCode_name[940:953],
	124: _OpCode_name[953:962],
	125: _OpCode_name[962:972],
	126: _OpCode_name[972:983],
	130: _OpCode_name[983:996],
	131: _OpCode_name[996:1009],
	132: _OpCode_name[1009:1022],
	133: _OpCode_name[1022:1033],
	134: _OpCode_name[1033:1045],
	135: _OpCode_name[1045:1057],
	136: _OpCode_name[1057:1067],
	137: _OpCode_name[1067:1078],
	138: _OpCode_name[1078:1090],
	140: _OpCode_name[1090:1107],
	141: _OpCode_name[1107:1123],
	142: _OpCode_name[1123:1143],
	143: _OpCode_name[1143:1153],
	144: _OpCode_name[1153:1165],
	145: _OpCode_name[1165:1176],
	146: _OpCode_name[1176:1183],
	147: _OpCode_name[1183:1190],
	148: _OpCode_name[1190:1205],
	149: _OpCode_name[1205:1216],
	150: _OpCode_name[1216:1227],
	151: _OpCode_name[1227:1239],
	152: _OpCode_name[1239:1255],
	153: _OpCode_name[1255:1274],
	154: _OpCode_name[1274:1291],
	155: _OpCode_name[1291:1303],
	156: _OpCode_name[1303:1312],
	157: _OpCode_name[1312:1321],
	158: _OpCode_name[1321:1337],
	159: _OpCode_name[1337:1355],
	160: _OpCode_name[1355:1369],
	161: _OpCode_name[1369:1394],
}

func (i OpCode) String() string {
	if str, ok := _OpCode_map[i]; ok {
		return str
	}
	return "OpCode(" + strconv.FormatInt(int64(i), 10) + ")"
}
