// Copyright 2022 The go-python Authors.  All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Package sysconfig provides python's 'sysconfig' module: access to Python's
// configuration information.
//
// A real CPython installs a _sysconfigdata module holding the build's
// configuration, generated by its own configure/make.  This interpreter has no
// such build step and no such file, so there is nothing to read: the variables
// here are the ones this interpreter genuinely knows, computed from the running
// process - the platform tag, the paths, the extension suffix - and every
// variable that would come from a CPython build is reported as None, which is
// what get_config_var returns for a variable a build does not set.  Nothing is
// invented.
package sysconfig

import (
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"

	"github.com/vishnukv64/gpython/py"
)

const module_doc = `Configuration information for Python.

This module provides access to the configuration variables and the installation
paths.  The variables come from the running interpreter, not from a
_sysconfigdata file, since this interpreter is a single binary with no build
directory; an unset variable reads as None.`

func init() {
	py.RegisterModule(&py.ModuleImpl{
		Info: py.ModuleInfo{
			Name: "sysconfig",
			Doc:  module_doc,
		},
		Methods: []*py.Method{
			py.MustNewMethod("get_config_var", getConfigVar, 0, "Return the value of a single variable.  Returns None when unset."),
			py.MustNewMethod("get_config_vars", getConfigVars, 0, "Return a dictionary of configuration variables."),
			py.MustNewMethod("get_platform", getPlatform, 0, "Return a string that identifies the current platform."),
			py.MustNewMethod("get_path", getPath, 0, "Return a path corresponding to the scheme."),
			py.MustNewMethod("get_paths", getPaths, 0, "Return a dictionary containing the installation paths."),
			py.MustNewMethod("get_python_version", getPythonVersion, 0, "Return the MAJOR.MINOR Python version number as a string."),
			py.MustNewMethod("get_scheme_names", getSchemeNames, 0, "Return a tuple containing the schemes names."),
		},
		Globals: py.NewStringDictFrom(
			py.DictEntry{Key: "_INSTALL_SCHEMES", Value: installSchemes()},
		),
	})
}

func getConfigVar(self py.Object, args py.Tuple) (py.Object, error) {
	var nameObj py.Object
	if err := py.UnpackTuple(args, py.NewStringDict(), "get_config_var", 1, 1, &nameObj); err != nil {
		return nil, err
	}
	name, err := py.StrAsString(nameObj)
	if err != nil {
		return nil, err
	}
	return configVar(name), nil
}

func getConfigVars(self py.Object, args py.Tuple) (py.Object, error) {
	if len(args) == 0 {
		d := py.NewStringDict()
		for _, e := range allConfigVars() {
			(&d).Set(e.Key, e.Value)
		}
		return d, nil
	}
	vals := py.NewList()
	for _, a := range args {
		name, err := py.StrAsString(a)
		if err != nil {
			return nil, err
		}
		v := configVar(name)
		vals.Items = append(vals.Items, v)
	}
	return vals, nil
}

// configVar is the value of one build variable.  Only the variables this
// interpreter actually knows are answered; everything a CPython build would
// have set is None.
func configVar(name string) py.Object {
	for _, e := range allConfigVars() {
		if e.Key == name {
			return e.Value
		}
	}
	return py.None
}

// allConfigVars is every variable this interpreter can honestly report.
func allConfigVars() []py.DictEntry {
	soabi := soabiTag()
	return []py.DictEntry{
		{Key: "EXT_SUFFIX", Value: py.String("." + soabi + ".so")},
		{Key: "SOABI", Value: py.String(soabi)},
		{Key: "SO", Value: py.String(".so")},
		{Key: "MULTIARCH", Value: py.String("")},
		{Key: "py_version", Value: py.String("3.10.0")},
		{Key: "py_version_short", Value: py.String("3.4")},
		{Key: "py_version_nodot", Value: py.String("34")},
		{Key: "prefix", Value: py.String(prefix())},
		{Key: "exec_prefix", Value: py.String(prefix())},
		{Key: "base", Value: py.String(prefix())},
		{Key: "platbase", Value: py.String(prefix())},
		{Key: "installed_base", Value: py.String(prefix())},
		{Key: "installed_platbase", Value: py.String(prefix())},
		{Key: "machine", Value: py.String(runtime.GOARCH)},
		{Key: "platform", Value: py.String(platformTag())},
		{Key: "Py_ENABLE_SHARED", Value: py.Int(0)},
		{Key: "ABIFLAGS", Value: py.String("")},
		{Key: "Py_DEBUG", Value: py.Int(0)},
		{Key: "WITH_THREAD", Value: py.Int(1)},
	}
}

// soabiTag is the interpreter's SOABI.  CPython spells it "cpython-314-darwin"
// on macOS; this interpreter is not CPython, and the tag has to describe the
// interpreter that will load the extension, so it is named for gpython and its
// version and platform.
func soabiTag() string {
	abi := "cpython-34"
	switch runtime.GOOS {
	case "darwin":
		return abi + "-darwin"
	case "windows":
		return "cp34-win_amd64"
	case "linux":
		return abi + "-" + linuxTriple()
	}
	return abi + "-" + runtime.GOOS + "-" + runtime.GOARCH
}

func linuxTriple() string {
	switch runtime.GOARCH {
	case "amd64":
		return "x86_64-linux-gnu"
	case "arm64":
		return "aarch64-linux-gnu"
	}
	return runtime.GOARCH + "-linux-gnu"
}

// platformTag is CPython's get_platform: "macosx-<major>.<minor>-<arch>" on
// macOS, "<os>-<arch>" elsewhere.
func platformTag() string {
	return systemPlatform()
}

func systemPlatform() string {
	switch runtime.GOOS {
	case "darwin":
		return "macosx-" + darwinVersion() + "-" + darwinArch()
	case "linux":
		return "linux-" + linuxArch()
	case "windows":
		return "win-" + windowsArch()
	}
	return runtime.GOOS + "-" + runtime.GOARCH
}

func darwinArch() string {
	switch runtime.GOARCH {
	case "amd64":
		return "x86_64"
	case "arm64":
		return "arm64"
	}
	return runtime.GOARCH
}

func linuxArch() string {
	switch runtime.GOARCH {
	case "amd64":
		return "x86_64"
	case "arm64":
		return "aarch64"
	case "386":
		return "i686"
	}
	return runtime.GOARCH
}

func windowsArch() string {
	switch runtime.GOARCH {
	case "amd64":
		return "amd64"
	case "386":
		return "32"
	case "arm64":
		return "arm64"
	}
	return runtime.GOARCH
}

func getPlatform(self py.Object, args py.Tuple) (py.Object, error) {
	if len(args) != 0 {
		return nil, py.ExceptionNewf(py.TypeError, "get_platform() takes no arguments")
	}
	return py.String(systemPlatform()), nil
}

func getPythonVersion(self py.Object, args py.Tuple) (py.Object, error) {
	if len(args) != 0 {
		return nil, py.ExceptionNewf(py.TypeError, "get_python_version() takes no arguments")
	}
	return py.String("3.4"), nil
}

func getPaths(self py.Object, args py.Tuple, kwargs py.StringDict) (py.Object, error) {
	var scheme, varsObj py.Object
	var expand py.Object = py.True
	if err := py.ParseTupleAndKeywords(args, kwargs, "|OOO:get_paths", []string{"scheme", "vars", "expand"}, &scheme, &varsObj, &expand); err != nil {
		return nil, err
	}
	d := py.NewStringDict()
	for _, e := range []py.DictEntry{
		{Key: "stdlib", Value: py.String(prefix())},
		{Key: "platstdlib", Value: py.String(prefix())},
		{Key: "purelib", Value: py.String(filepath.Join(prefix(), "lib", "python3.4", "site-packages"))},
		{Key: "platlib", Value: py.String(filepath.Join(prefix(), "lib", "python3.4", "site-packages"))},
		{Key: "include", Value: py.String(filepath.Join(prefix(), "include", "python3.4"))},
		{Key: "platinclude", Value: py.String(filepath.Join(prefix(), "include", "python3.4"))},
		{Key: "scripts", Value: py.String(filepath.Join(prefix(), "bin"))},
		{Key: "data", Value: py.String(prefix())},
	} {
		(&d).Set(e.Key, e.Value)
	}
	return d, nil
}

func getPath(self py.Object, args py.Tuple, kwargs py.StringDict) (py.Object, error) {
	var nameObj, scheme, varsObj py.Object
	var expand py.Object = py.True
	if err := py.ParseTupleAndKeywords(args, kwargs, "O|OOO:get_path", []string{"name", "scheme", "vars", "expand"}, &nameObj, &scheme, &varsObj, &expand); err != nil {
		return nil, err
	}
	name, err := py.StrAsString(nameObj)
	if err != nil {
		return nil, err
	}
	d, err := getPaths(self, py.Tuple{}, py.NewStringDict())
	if err != nil {
		return nil, err
	}
	paths := d.(py.StringDict)
	if v, ok := paths.Get(name); ok {
		return v, nil
	}
	return nil, py.ExceptionNewf(py.KeyError, "unknown installation path %q", name)
}

// installSchemes is the one scheme this interpreter has: a single prefix with
// the platform's own layout.
func installSchemes() py.Object {
	scheme := py.NewStringDict()
	for _, e := range []py.DictEntry{
		{Key: "stdlib", Value: py.String("{installed_base}/lib/python{py_version_short}")},
		{Key: "platstdlib", Value: py.String("{platbase}/lib/python{py_version_short}")},
		{Key: "purelib", Value: py.String("{base}/lib/python{py_version_short}/site-packages")},
		{Key: "platlib", Value: py.String("{platbase}/lib/python{py_version_short}/site-packages")},
		{Key: "include", Value: py.String("{installed_base}/include/python{py_version_short}")},
		{Key: "platinclude", Value: py.String("{installed_platbase}/include/python{py_version_short}")},
		{Key: "scripts", Value: py.String("{base}/bin")},
		{Key: "data", Value: py.String("{base}")},
	} {
		(&scheme).Set(e.Key, e.Value)
	}
	return py.NewStringDictFrom(
		py.DictEntry{Key: "gpython_posix_prefix", Value: scheme},
	)
}

func getSchemeNames(self py.Object, args py.Tuple) (py.Object, error) {
	if len(args) != 0 {
		return nil, py.ExceptionNewf(py.TypeError, "get_scheme_names() takes no arguments")
	}
	return py.Tuple{py.String("gpython_posix_prefix")}, nil
}

// prefix is the installation prefix: the directory holding the running
// executable, which is where this interpreter's installed tree would be.
func prefix() string {
	exe, err := os.Executable()
	if err != nil {
		return "/"
	}
	return filepath.Dir(exe)
}

// darwinVersion is the macOS product version, e.g. "14.5".  It comes from the
// system's own sw_vers, since Go reports no product version; an empty result is
// reported rather than a guess when that is unavailable.
func darwinVersion() string {
	out, err := exec.Command("sw_vers", "-productVersion").Output()
	if err != nil {
		return "0.0"
	}
	return strings.TrimSpace(string(out))
}
