// Code generated by goyacc -v parser/y.output -o parser/y.go parser/grammar.y. DO NOT EDIT.

//line parser/grammar.y:6

package parser

import __yyfmt__ "fmt"

//line parser/grammar.y:7

// Grammar for Python

import (
	"fmt"
	"github.com/vishnukv64/gpython/ast"
	"github.com/vishnukv64/gpython/py"
)

// NB can put code blocks in not just at the end

// Returns a Tuple if > 1 items or a trailing comma, otherwise returns
// the first item in elts
func tupleOrExpr(pos ast.Pos, elts []ast.Expr, optional_comma bool) ast.Expr {
	if optional_comma || len(elts) > 1 {
		return &ast.Tuple{ExprBase: ast.ExprBase{Pos: pos}, Elts: elts, Ctx: ast.Load}
	} else {
		return elts[0]
	}
}

// Apply trailers (if any) to expr
//
// trailers are half made Call, Subscript or Attribute
func applyTrailers(expr ast.Expr, trailers []ast.Expr) ast.Expr {
	//trailers := $1
	for _, trailer := range trailers {
		switch x := trailer.(type) {
		case *ast.Call:
			x.Func, expr = expr, x
		case *ast.Subscript:
			x.Value, expr = expr, x
		case *ast.Attribute:
			x.Value, expr = expr, x
		default:
			panic(fmt.Sprintf("Unknown trailer type: %T", expr))
		}
	}
	return expr
}

// Set the context for expr
func setCtx(yylex yyLexer, expr ast.Expr, ctx ast.ExprContext) {
	setctxer, ok := expr.(ast.SetCtxer)
	if !ok {
		expr_name := ""
		switch expr.(type) {
		case *ast.Lambda:
			expr_name = "lambda"
		case *ast.Call:
			expr_name = "function call"
		case *ast.BoolOp, *ast.BinOp, *ast.UnaryOp:
			expr_name = "operator"
		case *ast.GeneratorExp:
			expr_name = "generator expression"
		case *ast.Yield, *ast.YieldFrom:
			expr_name = "yield expression"
		case *ast.ListComp:
			expr_name = "list comprehension"
		case *ast.SetComp:
			expr_name = "set comprehension"
		case *ast.DictComp:
			expr_name = "dict comprehension"
		case *ast.Dict, *ast.Set, *ast.Num, *ast.Str, *ast.Bytes:
			expr_name = "literal"
		case *ast.NameConstant:
			expr_name = "keyword"
		case *ast.Ellipsis:
			expr_name = "Ellipsis"
		case *ast.Compare:
			expr_name = "comparison"
		case *ast.IfExp:
			expr_name = "conditional expression"
		default:
			expr_name = fmt.Sprintf("unexpected %T", expr)
		}
		action := "assign to"
		if ctx == ast.Del {
			action = "delete"
		}
		yylex.(*yyLex).SyntaxErrorf("can't %s %s", action, expr_name)
		return
	}
	setctxer.SetCtx(ctx)
}

// Set the context for all the items in exprs
func setCtxs(yylex yyLexer, exprs []ast.Expr, ctx ast.ExprContext) {
	for i := range exprs {
		setCtx(yylex, exprs[i], ctx)
	}
}

//line parser/grammar.y:103
type yySymType struct {
	yys            int
	pos            ast.Pos // kept up to date by the lexer
	str            string
	obj            py.Object
	mod            ast.Mod
	stmt           ast.Stmt
	stmts          []ast.Stmt
	expr           ast.Expr
	exprs          []ast.Expr
	op             ast.OperatorNumber
	cmpop          ast.CmpOp
	comma          bool
	comprehensions []ast.Comprehension
	isExpr         bool
	slice          ast.Slicer
	call           *ast.Call
	level          int
	alias          *ast.Alias
	aliases        []*ast.Alias
	identifiers    []ast.Identifier
	ifstmt         *ast.If
	lastif         *ast.If
	exchandlers    []*ast.ExceptHandler
	withitem       *ast.WithItem
	withitems      []*ast.WithItem
	arg            *ast.Arg
	annassign      *ast.AnnAssign
	args           []*ast.Arg
	arguments      *ast.Arguments
}

const NEWLINE = 57346
const ENDMARKER = 57347
const NAME = 57348
const INDENT = 57349
const DEDENT = 57350
const STRING = 57351
const NUMBER = 57352
const PLINGEQ = 57353
const PERCEQ = 57354
const ANDEQ = 57355
const STARSTAR = 57356
const STARSTAREQ = 57357
const STAREQ = 57358
const PLUSEQ = 57359
const MINUSEQ = 57360
const MINUSGT = 57361
const ELIPSIS = 57362
const DIVDIV = 57363
const DIVDIVEQ = 57364
const DIVEQ = 57365
const LTLT = 57366
const LTLTEQ = 57367
const LTEQ = 57368
const LTGT = 57369
const EQEQ = 57370
const GTEQ = 57371
const GTGT = 57372
const GTGTEQ = 57373
const HATEQ = 57374
const PIPEEQ = 57375
const FALSE = 57376
const NONE = 57377
const TRUE = 57378
const AND = 57379
const AS = 57380
const ASSERT = 57381
const BREAK = 57382
const CLASS = 57383
const CONTINUE = 57384
const DEF = 57385
const DEL = 57386
const ELIF = 57387
const ELSE = 57388
const EXCEPT = 57389
const FINALLY = 57390
const FOR = 57391
const FROM = 57392
const GLOBAL = 57393
const IF = 57394
const IMPORT = 57395
const IN = 57396
const IS = 57397
const LAMBDA = 57398
const NONLOCAL = 57399
const NOT = 57400
const OR = 57401
const PASS = 57402
const RAISE = 57403
const RETURN = 57404
const TRY = 57405
const WHILE = 57406
const WITH = 57407
const YIELD = 57408
const SINGLE_INPUT = 57409
const FILE_INPUT = 57410
const EVAL_INPUT = 57411

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"NEWLINE",
	"ENDMARKER",
	"NAME",
	"INDENT",
	"DEDENT",
	"STRING",
	"NUMBER",
	"PLINGEQ",
	"PERCEQ",
	"ANDEQ",
	"STARSTAR",
	"STARSTAREQ",
	"STAREQ",
	"PLUSEQ",
	"MINUSEQ",
	"MINUSGT",
	"ELIPSIS",
	"DIVDIV",
	"DIVDIVEQ",
	"DIVEQ",
	"LTLT",
	"LTLTEQ",
	"LTEQ",
	"LTGT",
	"EQEQ",
	"GTEQ",
	"GTGT",
	"GTGTEQ",
	"HATEQ",
	"PIPEEQ",
	"FALSE",
	"NONE",
	"TRUE",
	"AND",
	"AS",
	"ASSERT",
	"BREAK",
	"CLASS",
	"CONTINUE",
	"DEF",
	"DEL",
	"ELIF",
	"ELSE",
	"EXCEPT",
	"FINALLY",
	"FOR",
	"FROM",
	"GLOBAL",
	"IF",
	"IMPORT",
	"IN",
	"IS",
	"LAMBDA",
	"NONLOCAL",
	"NOT",
	"OR",
	"PASS",
	"RAISE",
	"RETURN",
	"TRY",
	"WHILE",
	"WITH",
	"YIELD",
	"'('",
	"')'",
	"'['",
	"']'",
	"':'",
	"','",
	"';'",
	"'+'",
	"'-'",
	"'*'",
	"'/'",
	"'|'",
	"'&'",
	"'<'",
	"'>'",
	"'='",
	"'.'",
	"'%'",
	"'{'",
	"'}'",
	"'^'",
	"'~'",
	"'@'",
	"SINGLE_INPUT",
	"FILE_INPUT",
	"EVAL_INPUT",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line yacctab:1
var yyExca = [...]int16{
	-1, 1,
	1, -1,
	-2, 0,
	-1, 233,
	68, 13,
	-2, 293,
	-1, 385,
	68, 93,
	-2, 294,
}

const yyPrivate = 57344

const yyLast = 1463

var yyAct = [...]int16{
	59, 472, 61, 316, 166, 97, 460, 323, 161, 165,
	425, 405, 352, 378, 364, 345, 261, 468, 224, 101,
	102, 142, 338, 111, 211, 337, 225, 103, 69, 6,
	35, 320, 146, 54, 60, 239, 110, 71, 74, 461,
	70, 66, 64, 151, 95, 147, 73, 105, 138, 106,
	72, 57, 232, 97, 144, 107, 17, 125, 126, 97,
	131, 123, 121, 122, 134, 106, 181, 132, 124, 190,
	129, 107, 75, 2, 3, 4, 130, 128, 127, 290,
	24, 245, 23, 381, 205, 140, 96, 326, 233, 279,
	249, 49, 158, 264, 139, 237, 176, 143, 286, 153,
	478, 182, 149, 155, 245, 180, 185, 186, 99, 168,
	470, 174, 175, 172, 173, 196, 120, 339, 216, 97,
	212, 238, 457, 388, 187, 188, 223, 133, 48, 228,
	227, 390, 189, 197, 200, 245, 454, 167, 167, 177,
	179, 394, 281, 178, 282, 164, 164, 401, 402, 191,
	192, 193, 235, 399, 385, 253, 217, 490, 283, 254,
	376, 257, 152, 236, 241, 170, 171, 240, 262, 263,
	207, 317, 167, 198, 201, 215, 291, 286, 336, 424,
	344, 477, 317, 464, 260, 387, 141, 335, 259, 248,
	314, 243, 244, 246, 251, 242, 252, 222, 265, 293,
	255, 256, 484, 160, 407, 417, 416, 163, 163, 415,
	413, 409, 404, 382, 373, 366, 298, 318, 258, 269,
	287, 268, 97, 289, 273, 274, 292, 220, 111, 295,
	271, 272, 219, 270, 324, 108, 456, 285, 299, 300,
	288, 423, 343, 360, 328, 294, 400, 306, 331, 315,
	359, 106, 313, 384, 375, 358, 356, 107, 307, 341,
	275, 276, 277, 278, 305, 346, 301, 284, 241, 342,
	302, 240, 233, 325, 231, 286, 340, 156, 463, 157,
	267, 332, 324, 353, 157, 157, 408, 266, 221, 157,
	286, 250, 361, 463, 362, 368, 370, 369, 247, 286,
	465, 411, 365, 135, 365, 451, 395, 229, 159, 34,
	374, 208, 15, 349, 357, 106, 183, 379, 380, 14,
	309, 107, 184, 304, 317, 167, 317, 167, 317, 372,
	466, 212, 487, 471, 377, 114, 469, 383, 116, 167,
	434, 396, 339, 386, 355, 117, 333, 437, 262, 398,
	137, 140, 347, 330, 327, 406, 136, 391, 113, 393,
	397, 112, 392, 329, 389, 297, 296, 218, 98, 213,
	100, 418, 7, 403, 214, 311, 310, 230, 412, 312,
	162, 109, 426, 427, 303, 414, 324, 363, 429, 430,
	334, 431, 421, 428, 422, 145, 419, 148, 212, 150,
	319, 455, 410, 353, 322, 440, 321, 351, 442, 436,
	444, 443, 445, 435, 432, 438, 439, 433, 441, 350,
	169, 25, 119, 194, 204, 104, 462, 379, 453, 447,
	206, 308, 446, 367, 448, 449, 450, 452, 203, 234,
	68, 474, 458, 62, 80, 280, 79, 118, 16, 115,
	13, 12, 459, 11, 9, 10, 44, 43, 42, 41,
	40, 39, 38, 467, 33, 32, 473, 436, 31, 30,
	29, 324, 28, 479, 27, 26, 482, 371, 480, 483,
	8, 93, 488, 476, 485, 94, 489, 473, 5, 92,
	1, 491, 492, 473, 86, 0, 486, 210, 209, 84,
	0, 0, 91, 85, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 87, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 90, 88, 89,
	0, 0, 47, 50, 24, 51, 23, 36, 0, 0,
	0, 0, 20, 56, 45, 18, 55, 0, 0, 65,
	46, 67, 0, 37, 53, 52, 21, 19, 22, 58,
	81, 84, 82, 420, 91, 85, 0, 76, 77, 63,
	0, 0, 0, 0, 0, 87, 0, 0, 83, 0,
	0, 78, 48, 0, 0, 0, 0, 0, 0, 90,
	88, 89, 0, 0, 47, 50, 24, 51, 23, 36,
	0, 0, 0, 0, 20, 56, 45, 18, 55, 0,
	0, 65, 46, 67, 0, 37, 53, 52, 21, 19,
	22, 58, 81, 84, 82, 0, 91, 85, 0, 76,
	77, 63, 0, 0, 0, 0, 0, 87, 0, 0,
	83, 0, 0, 78, 48, 0, 0, 0, 0, 0,
	0, 90, 88, 89, 0, 0, 47, 50, 24, 51,
	23, 36, 0, 0, 0, 0, 20, 56, 45, 18,
	55, 0, 0, 65, 46, 67, 0, 37, 53, 52,
	21, 19, 22, 58, 81, 0, 82, 0, 0, 0,
	0, 76, 77, 63, 226, 0, 84, 0, 0, 91,
	85, 0, 83, 0, 0, 78, 48, 0, 0, 0,
	87, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 90, 88, 89, 0, 0, 47,
	50, 0, 51, 0, 36, 0, 0, 0, 0, 0,
	56, 45, 0, 55, 0, 0, 65, 46, 67, 0,
	37, 53, 52, 0, 0, 0, 58, 81, 84, 82,
	0, 91, 85, 0, 76, 77, 63, 0, 0, 0,
	0, 0, 87, 0, 0, 83, 0, 0, 78, 0,
	0, 0, 0, 0, 0, 0, 90, 88, 89, 0,
	0, 47, 50, 0, 51, 0, 36, 0, 0, 0,
	0, 0, 56, 45, 0, 55, 0, 0, 65, 46,
	67, 0, 37, 53, 52, 0, 0, 0, 58, 81,
	84, 82, 0, 91, 85, 0, 76, 77, 63, 0,
	0, 0, 0, 0, 87, 0, 0, 83, 0, 0,
	78, 0, 0, 0, 0, 0, 0, 0, 90, 88,
	89, 0, 0, 0, 0, 0, 0, 84, 0, 0,
	91, 85, 0, 0, 0, 0, 0, 0, 0, 0,
	65, 87, 67, 0, 0, 0, 0, 0, 0, 0,
	58, 81, 195, 82, 0, 90, 88, 89, 76, 77,
	63, 0, 0, 0, 84, 0, 0, 91, 85, 83,
	0, 0, 78, 0, 0, 0, 0, 65, 87, 67,
	0, 0, 0, 0, 0, 0, 0, 58, 81, 0,
	82, 0, 90, 88, 89, 76, 77, 63, 0, 0,
	0, 0, 0, 0, 0, 0, 83, 84, 0, 78,
	91, 85, 0, 0, 65, 481, 67, 0, 0, 0,
	0, 87, 0, 0, 0, 81, 0, 82, 199, 0,
	0, 0, 76, 77, 63, 90, 88, 89, 0, 0,
	0, 0, 0, 83, 84, 0, 78, 91, 85, 0,
	0, 0, 0, 0, 0, 0, 0, 65, 87, 67,
	0, 0, 0, 0, 0, 0, 0, 0, 81, 0,
	82, 0, 90, 88, 89, 76, 77, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 83, 84, 0, 78,
	91, 85, 0, 0, 65, 0, 67, 0, 0, 0,
	0, 87, 0, 0, 0, 81, 0, 82, 0, 407,
	0, 0, 76, 77, 0, 90, 88, 89, 0, 0,
	0, 0, 0, 83, 0, 0, 78, 0, 0, 84,
	0, 0, 91, 85, 0, 0, 0, 65, 0, 67,
	0, 0, 0, 87, 0, 0, 0, 0, 81, 0,
	82, 0, 354, 0, 0, 76, 77, 90, 88, 89,
	0, 0, 0, 0, 0, 0, 83, 0, 0, 78,
	0, 0, 84, 0, 0, 91, 85, 0, 0, 65,
	0, 67, 0, 0, 0, 0, 87, 0, 0, 0,
	81, 0, 82, 0, 0, 0, 0, 76, 77, 63,
	90, 88, 89, 0, 0, 0, 0, 0, 83, 84,
	0, 78, 91, 85, 0, 0, 0, 0, 0, 0,
	0, 0, 65, 87, 67, 0, 0, 0, 0, 0,
	0, 0, 0, 81, 348, 82, 0, 90, 88, 89,
	76, 77, 0, 0, 0, 0, 84, 0, 0, 91,
	85, 83, 0, 0, 78, 0, 0, 0, 0, 65,
	87, 67, 0, 0, 0, 0, 0, 0, 0, 58,
	81, 0, 82, 0, 90, 88, 89, 76, 77, 0,
	0, 0, 0, 84, 0, 0, 91, 85, 83, 0,
	0, 78, 0, 0, 0, 0, 65, 87, 67, 0,
	0, 0, 0, 0, 0, 0, 0, 81, 0, 82,
	0, 90, 88, 89, 76, 77, 0, 0, 0, 0,
	84, 0, 0, 91, 85, 83, 202, 154, 78, 0,
	0, 0, 0, 65, 87, 67, 0, 0, 0, 0,
	0, 0, 0, 0, 81, 0, 82, 0, 90, 88,
	89, 76, 77, 0, 0, 0, 0, 84, 0, 0,
	91, 85, 83, 0, 0, 78, 0, 0, 0, 0,
	475, 87, 67, 0, 0, 0, 0, 0, 0, 0,
	0, 81, 0, 82, 0, 90, 88, 89, 76, 77,
	0, 0, 0, 0, 84, 0, 0, 91, 85, 83,
	0, 0, 78, 0, 0, 0, 0, 65, 87, 67,
	0, 0, 0, 0, 0, 0, 0, 0, 81, 0,
	82, 0, 90, 88, 89, 76, 77, 0, 0, 0,
	84, 0, 0, 91, 85, 0, 83, 0, 0, 78,
	0, 0, 0, 0, 87, 0, 67, 0, 0, 0,
	84, 0, 0, 91, 85, 81, 0, 82, 90, 88,
	89, 0, 76, 77, 87, 0, 0, 0, 0, 0,
	0, 0, 0, 83, 0, 0, 78, 0, 90, 88,
	89, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 81, 0, 82, 0, 0, 0, 0, 76, 77,
	63, 0, 0, 0, 0, 0, 0, 0, 0, 83,
	0, 81, 78, 82, 0, 0, 0, 0, 76, 77,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 83,
	0, 0, 78,
}

var yyPact = [...]int16{
	-17, -32768, 617, -32768, 1281, -32768, -32768, 364, 35, -32768,
	-32768, -32768, -32768, -32768, -32768, -32768, -32768, -32768, 1281, 1281,
	1354, 164, 1281, 355, 352, 39, -32768, -32768, -32768, -32768,
	-32768, -32768, -32768, -32768, -32768, 45, 1354, -32768, -32768, -32768,
	-32768, -32768, -32768, -32768, -32768, 350, 350, 1281, 345, 114,
	-32768, -32768, 1281, 1281, -32768, 345, 79, -32768, 1207, -32768,
	-32768, 225, -32768, 1374, 271, 132, -32768, 1318, 85, 27,
	-21, 22, 292, 32, 48, -32768, 1374, 1374, 1374, -32768,
	-32768, 814, 888, 1170, -32768, -32768, 302, -32768, -32768, -32768,
	-32768, -32768, -32768, 493, -32768, -32768, 103, -32768, -32768, 752,
	363, 161, 156, 234, 125, -32768, 27, -32768, 690, 58,
	-32768, 269, 207, 205, -32768, -32768, -32768, -32768, 1133, 13,
	1281, -32768, -32768, -32768, -32768, -32768, -32768, -32768, -32768, -32768,
	-32768, -32768, -32768, 851, -32768, 123, -32768, 123, 119, 21,
	-32768, 1053, -32768, -32768, 248, 117, -32768, 52, 238, -2,
	79, -32768, -32768, -32768, 1281, -32768, 1318, 1318, 27, 1318,
	1281, 147, 116, 321, 321, -32768, 11, -32768, -32768, 1374,
	-32768, -32768, -32768, -32768, -32768, -32768, -32768, -32768, 233, 222,
	1374, 1374, 1374, 1374, 1374, 1374, 1374, 1374, 1374, 1374,
	1374, -32768, -32768, -32768, 75, -32768, 199, 250, 114, -32768,
	250, 114, -32768, -7, 104, 128, -32768, 103, -32768, -32768,
	-32768, -32768, -32768, -32768, 361, 1281, -32768, -32768, -32768, 690,
	690, 1281, 1354, -32768, -32768, -32768, 316, 1281, 690, 1374,
	301, 176, 146, 1281, -32768, -32768, -32768, 851, 5, -32768,
	-32768, -32768, 348, 1281, 359, 347, -32768, 1281, 345, 340,
	111, -32768, -2, -32768, 230, 271, -32768, -32768, 1281, 166,
	-32768, -32768, -32768, -32768, 1281, 27, -32768, -32768, -21, 22,
	292, 32, 32, 48, 48, -32768, -32768, -32768, -32768, 1374,
	-32768, 1096, 1011, 338, -32768, 188, 1354, 187, 180, 173,
	-32768, 1281, -32768, 1281, -32768, -32768, -32768, -32768, -32768, -32768,
	258, 144, -32768, 249, 617, -32768, -32768, 27, 143, 1281,
	186, -32768, 88, 320, 320, -32768, 1, 142, 690, 185,
	-32768, 82, 109, -32768, 49, -32768, 1053, -32768, -32768, -32768,
	-32768, -32768, -32768, -32768, -32768, -32768, 336, 69, -32768, 268,
	1281, -32768, -32768, 321, 321, 81, -32768, -32768, -32768, 178,
	77, 76, -32768, 141, 968, -32768, -32768, 232, -32768, -32768,
	-32768, 140, 250, 256, -32768, 139, 690, 138, 135, 134,
	1281, 555, -32768, 690, -32768, -32768, 165, -32768, -32768, -32768,
	-32768, 1281, 1281, -32768, -32768, 1281, -32768, 1281, 1281, -32768,
	1281, -32768, 69, -32768, 336, 334, -32768, -32768, -32768, 333,
	-32768, -32768, 1011, -32768, 968, -32768, 133, 1281, 1318, 1281,
	-32768, 1281, -32768, 690, 258, 690, 690, 690, 267, -32768,
	-32768, -32768, -32768, 320, 320, 64, -32768, -32768, -32768, -32768,
	-32768, -32768, 168, -32768, -32768, 50, -32768, 321, -32768, -32768,
	133, -32768, -32768, 226, -32768, 112, -32768, -32768, -32768, 252,
	-32768, 324, -32768, -32768, 322, 38, -32768, 319, -32768, -32768,
	-32768, -32768, -32768, 1244, 690, 110, -32768, 28, -32768, 320,
	931, 321, 241, 220, -32768, 131, -32768, 690, 318, -32768,
	-32768, 1281, -32768, -32768, 1244, 86, -32768, 320, -32768, -32768,
	1244, -32768, -32768,
}

var yyPgo = [...]int16{
	0, 494, 490, 489, 488, 485, 26, 24, 481, 480,
	477, 18, 14, 369, 56, 475, 474, 472, 470, 469,
	468, 465, 464, 462, 461, 460, 459, 458, 457, 456,
	455, 454, 453, 451, 450, 319, 312, 449, 448, 447,
	47, 28, 34, 40, 37, 50, 46, 38, 72, 446,
	445, 444, 51, 0, 41, 443, 1, 441, 2, 42,
	440, 44, 30, 439, 33, 35, 438, 11, 433, 431,
	309, 27, 430, 426, 6, 425, 91, 86, 424, 423,
	422, 421, 420, 21, 39, 12, 419, 407, 7, 406,
	404, 401, 31, 52, 400, 43, 399, 45, 397, 303,
	32, 22, 395, 25, 390, 387, 384, 36, 381, 9,
	4, 16, 17, 3, 13, 15, 380, 10, 379, 8,
	377, 376, 375, 374, 370,
}

var yyR1 = [...]int8{
	0, 2, 2, 2, 4, 4, 3, 8, 8, 8,
	5, 123, 123, 94, 94, 93, 93, 70, 81, 81,
	37, 37, 38, 69, 69, 35, 120, 121, 121, 112,
	112, 117, 117, 118, 118, 114, 114, 122, 122, 122,
	122, 122, 122, 122, 113, 113, 109, 109, 115, 115,
	116, 116, 111, 111, 119, 119, 119, 119, 119, 119,
	119, 110, 7, 7, 124, 124, 9, 9, 6, 14,
	14, 14, 14, 14, 14, 14, 14, 15, 15, 15,
	15, 15, 63, 63, 65, 65, 80, 80, 76, 76,
	52, 52, 83, 83, 62, 39, 39, 39, 39, 39,
	39, 39, 39, 39, 39, 39, 39, 16, 17, 18,
	18, 18, 18, 18, 23, 24, 25, 25, 27, 26,
	26, 26, 19, 19, 28, 95, 95, 96, 96, 98,
	98, 98, 104, 104, 104, 29, 101, 101, 100, 100,
	103, 103, 102, 102, 97, 97, 99, 99, 20, 21,
	77, 77, 22, 22, 13, 13, 13, 13, 13, 13,
	13, 13, 105, 105, 12, 12, 31, 30, 32, 106,
	106, 33, 33, 33, 33, 108, 108, 34, 107, 107,
	68, 68, 68, 10, 10, 11, 11, 53, 53, 53,
	56, 56, 55, 55, 57, 57, 58, 58, 59, 59,
	54, 54, 60, 60, 82, 82, 82, 82, 82, 82,
	82, 82, 82, 82, 82, 42, 41, 41, 43, 43,
	44, 44, 45, 45, 45, 46, 46, 46, 47, 47,
	47, 47, 47, 48, 48, 48, 48, 49, 49, 79,
	79, 1, 1, 51, 51, 51, 51, 51, 51, 51,
	51, 51, 51, 51, 51, 51, 51, 51, 51, 50,
	50, 50, 50, 87, 87, 86, 85, 85, 85, 85,
	85, 85, 85, 85, 85, 67, 67, 40, 40, 75,
	75, 71, 61, 72, 78, 78, 66, 66, 66, 66,
	36, 89, 89, 90, 90, 91, 91, 92, 92, 92,
	92, 88, 88, 88, 74, 74, 84, 84, 73, 73,
	64, 64, 64,
}

var yyR2 = [...]int8{
	0, 2, 2, 2, 1, 2, 2, 0, 2, 2,
	3, 0, 2, 0, 1, 0, 3, 4, 1, 2,
	1, 1, 2, 0, 2, 6, 3, 0, 1, 1,
	3, 0, 3, 1, 3, 0, 1, 2, 5, 8,
	4, 3, 6, 2, 1, 3, 1, 3, 0, 3,
	1, 3, 0, 1, 2, 5, 8, 4, 3, 6,
	2, 1, 1, 1, 0, 1, 1, 3, 3, 1,
	1, 1, 1, 1, 1, 1, 1, 3, 2, 1,
	3, 5, 1, 1, 1, 1, 2, 3, 1, 3,
	1, 1, 0, 1, 2, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 2, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 2, 1, 1,
	2, 4, 1, 1, 2, 1, 1, 1, 2, 1,
	2, 1, 1, 4, 2, 4, 1, 3, 1, 3,
	1, 3, 1, 3, 1, 3, 1, 3, 2, 2,
	1, 3, 2, 4, 1, 1, 1, 1, 1, 1,
	1, 1, 0, 5, 0, 3, 6, 5, 7, 0,
	4, 4, 7, 7, 10, 1, 3, 4, 1, 3,
	1, 2, 4, 1, 2, 1, 4, 1, 5, 1,
	1, 1, 3, 4, 3, 4, 1, 3, 1, 3,
	2, 1, 1, 3, 1, 1, 1, 1, 1, 1,
	1, 1, 2, 1, 2, 2, 1, 3, 1, 3,
	1, 3, 1, 3, 3, 1, 3, 3, 1, 3,
	3, 3, 3, 2, 2, 2, 1, 2, 4, 0,
	2, 1, 2, 2, 3, 4, 4, 2, 4, 4,
	2, 3, 1, 1, 1, 1, 1, 1, 1, 2,
	3, 3, 2, 1, 3, 2, 1, 1, 2, 2,
	3, 2, 3, 3, 4, 1, 2, 1, 1, 1,
	3, 2, 2, 2, 3, 5, 2, 4, 1, 2,
	5, 1, 3, 0, 2, 0, 3, 2, 4, 7,
	3, 1, 2, 3, 1, 1, 4, 5, 2, 3,
	1, 3, 2,
}

var yyChk = [...]int16{
	-32768, -2, 90, 91, 92, -4, -6, -13, -9, -31,
	-30, -32, -33, -34, -35, -36, -38, -14, 52, 64,
	49, 63, 65, 43, 41, -81, -15, -16, -17, -18,
	-19, -20, -21, -22, -70, -62, 44, 60, -23, -24,
	-25, -26, -27, -28, -29, 51, 57, 39, 89, -76,
	40, 42, 62, 61, -64, 53, 50, -52, 66, -53,
	-42, -58, -55, 76, -59, 56, -54, 58, -60, -41,
	-43, -44, -45, -46, -47, -48, 74, 75, 88, -49,
	-51, 67, 69, 85, 6, 10, -1, 20, 35, 36,
	34, 9, -3, -8, -5, -61, -77, -53, 4, 73,
	-124, -53, -53, -71, -75, -40, -41, -42, 71, -108,
	-107, -53, 6, 6, -70, -37, -36, -35, -39, -80,
	71, 17, 18, 16, 23, 12, 13, 33, 32, 25,
	31, 15, 22, 82, -71, -99, 6, -99, -53, -97,
	6, 72, -83, -61, -53, -102, -100, -97, -98, -97,
	-96, -95, 83, 20, 50, -61, 52, 59, -41, 37,
	71, -119, -116, 76, 14, -109, -110, 6, -54, -82,
	80, 81, 28, 29, 26, 27, 11, 54, 58, 55,
	78, 87, 79, 24, 30, 74, 75, 76, 77, 84,
	21, -48, -48, -48, -79, 68, -64, -52, -76, 70,
	-52, -76, 86, -66, -78, -53, -72, -77, 9, 5,
	4, -7, -6, -13, -123, 72, -83, -14, 4, 71,
	71, 54, 72, -83, -11, -6, 4, 72, 71, 38,
	-120, 67, -93, 67, -63, -64, -61, 82, -53, -65,
	-64, -62, 72, 72, -93, 83, -52, 50, 72, 38,
	53, -95, -97, -53, -58, -59, -54, -53, 71, 72,
	-83, -111, -110, -110, 82, -41, 54, 58, -43, -44,
	-45, -46, -46, -47, -47, -48, -48, -48, -48, 14,
	-50, 67, 69, 83, 68, -84, 49, -83, -84, -83,
	86, 72, -83, 71, -84, -83, 5, 4, -53, -11,
	-11, -61, -40, -106, 7, -107, -11, -41, -69, 19,
	-121, -122, -118, 76, 14, -112, -113, 6, 71, -94,
	-92, -89, -90, -88, -53, -65, 82, 6, -53, 4,
	6, -53, -100, 6, -104, 76, 67, -103, -101, 6,
	46, -53, -109, 76, 14, -115, -53, -48, 68, -92,
	-86, -87, -85, -53, 71, 6, 68, -71, 68, 70,
	70, -53, -53, -105, -12, 46, 71, -68, 46, 48,
	47, -10, -7, 71, -53, 68, 72, -83, -114, -113,
	-113, 82, 71, -11, 68, 72, -83, 76, 14, -84,
	82, -62, -103, -83, 72, 38, -53, -111, -110, 72,
	68, 70, 72, -83, 71, -67, -53, 71, 54, 71,
	-84, 45, -12, 71, -11, 71, 71, 71, -53, -7,
	8, -11, -112, 76, 14, -117, -53, -53, -88, -53,
	-53, -53, -83, -101, 6, -115, -109, 14, -85, -67,
	-53, -67, -53, -58, -53, -53, -11, -12, -11, -11,
	-11, 38, -114, -113, 72, -91, 68, 72, -110, -67,
	-74, -84, -73, 52, 71, 48, 6, -117, -112, 14,
	72, 14, -56, -58, -57, 56, -11, 71, 72, -113,
	-88, 14, -110, -74, 71, -119, -11, 14, -53, -56,
	71, -113, -56,
}

var yyDef = [...]int16{
	0, -2, 0, 7, 0, 1, 4, 0, 64, 154,
	155, 156, 157, 158, 159, 160, 161, 66, 0, 0,
	0, 0, 0, 0, 0, 0, 69, 70, 71, 72,
	73, 74, 75, 76, 18, 79, 0, 108, 109, 110,
	111, 112, 113, 122, 123, 0, 0, 0, 0, 92,
	114, 115, 116, 119, 118, 0, 0, 88, 310, 90,
	91, 187, 189, 0, 196, 0, 198, 0, 201, 202,
	216, 218, 220, 222, 225, 228, 0, 0, 0, 236,
	239, 0, 0, 0, 252, 253, 254, 255, 256, 257,
	258, 241, 2, 0, 3, 11, 92, 150, 5, 65,
	0, 0, 0, 0, 92, 279, 277, 278, 0, 0,
	175, 178, 0, 15, 19, 22, 20, 21, 0, 78,
	0, 95, 96, 97, 98, 99, 100, 101, 102, 103,
	104, 105, 106, 0, 107, 148, 146, 149, 152, 15,
	144, 93, 94, 117, 120, 124, 142, 138, 0, 129,
	131, 127, 125, 126, 0, 312, 0, 0, 215, 0,
	0, 0, 92, 52, 0, 50, 46, 61, 200, 0,
	204, 205, 206, 207, 208, 209, 210, 211, 0, 213,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 233, 234, 235, 237, 243, 0, 88, 92, 247,
	88, 92, 250, 0, 92, 150, 288, 92, 242, 6,
	8, 9, 62, 63, 0, 93, 282, 67, 68, 0,
	0, 0, 93, 281, 169, 185, 0, 0, 0, 0,
	23, 27, 0, -2, 77, 82, 83, 0, 80, 86,
	84, 85, 0, 0, 0, 0, 89, 0, 0, 0,
	0, 128, 130, 311, 0, 197, 199, 192, 0, 93,
	54, 48, 53, 60, 0, 203, 212, 214, 217, 219,
	221, 223, 224, 226, 227, 229, 230, 231, 232, 0,
	240, 293, 0, 0, 244, 0, 0, 0, 0, 0,
	251, 93, 286, 0, 289, 283, 10, 12, 151, 162,
	164, 0, 280, 171, 0, 176, 177, 179, 0, 0,
	0, 28, 92, 35, 0, 33, 29, 44, 0, 0,
	14, 92, 0, 291, 301, 87, 0, 147, 153, 17,
	145, 121, 143, 139, 135, 132, 0, 92, 140, 136,
	0, 193, 51, 52, 0, 58, 47, 238, 259, 0,
	0, 92, 263, 266, 267, 262, 245, 0, 246, 248,
	249, 0, 284, 164, 167, 0, 0, 0, 0, 0,
	180, 0, 183, 0, 24, 26, 93, 37, 31, 36,
	43, 0, 0, 290, 16, -2, 297, 0, 0, 302,
	0, 81, 92, 134, 93, 0, 188, 48, 57, 0,
	260, 261, 93, 265, 271, 268, 269, 275, 0, 0,
	287, 0, 166, 0, 164, 0, 0, 0, 181, 184,
	186, 25, 34, 35, 0, 41, 30, 45, 292, 295,
	300, 303, 0, 141, 137, 55, 49, 0, 264, 272,
	273, 270, 276, 306, 285, 0, 165, 168, 170, 172,
	173, 0, 31, 40, 0, 298, 133, 0, 59, 274,
	307, 304, 305, 0, 0, 0, 182, 38, 32, 0,
	0, 0, 308, 190, 191, 0, 163, 0, 0, 42,
	296, 0, 56, 309, 0, 0, 174, 0, 299, 194,
	0, 39, 195,
}

var yyTok1 = [...]int8{
	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 84, 79, 3,
	67, 68, 76, 74, 72, 75, 83, 77, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 71, 73,
	80, 82, 81, 3, 89, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 69, 3, 70, 87, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 85, 78, 86, 88,
}

var yyTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
	42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
	52, 53, 54, 55, 56, 57, 58, 59, 60, 61,
	62, 63, 64, 65, 66, 90, 91, 92,
}

var yyTok3 = [...]int8{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -32768

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(yyPact[state])
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && int(yyChk[int(yyAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || int(yyExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := int(yyExca[i])
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(yyTok1[0])
		goto out
	}
	if char < len(yyTok1) {
		token = int(yyTok1[char])
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = int(yyTok2[char-yyPrivate])
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = int(yyTok3[i+0])
		if token == char {
			token = int(yyTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(yyTok2[1]) /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = int(yyPact[yystate])
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = int(yyAct[yyn])
	if int(yyChk[yyn]) == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = int(yyDef[yystate])
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && int(yyExca[xi+1]) == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = int(yyExca[xi+0])
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = int(yyExca[xi+1])
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = int(yyPact[yyS[yyp].yys]) + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = int(yyAct[yyn]) /* simulate a shift of "error" */
					if int(yyChk[yystate]) == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= int(yyR2[yyn])
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = int(yyR1[yyn])
	yyg := int(yyPgo[yyn])
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = int(yyAct[yyg])
	} else {
		yystate = int(yyAct[yyj])
		if int(yyChk[yystate]) != -yyn {
			yystate = int(yyAct[yyg])
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/grammar.y:251
		{
			yylex.(*yyLex).mod = yyDollar[2].mod
			return 0
		}
	case 2:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/grammar.y:256
		{
			yylex.(*yyLex).mod = yyDollar[2].mod
			return 0
		}
	case 3:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/grammar.y:261
		{
			yylex.(*yyLex).mod = yyDollar[2].mod
			return 0
		}
	case 4:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:275
		{
			yyVAL.mod = &ast.Interactive{ModBase: ast.ModBase{Pos: yyVAL.pos}, Body: yyDollar[1].stmts}
		}
	case 5:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/grammar.y:279
		{
			//  NB: compound_stmt in single_input is followed by extra NEWLINE!
			yyVAL.mod = &ast.Interactive{ModBase: ast.ModBase{Pos: yyVAL.pos}, Body: []ast.Stmt{yyDollar[1].stmt}}
		}
	case 6:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/grammar.y:287
		{
			yyVAL.mod = &ast.Module{ModBase: ast.ModBase{Pos: yyVAL.pos}, Body: yyDollar[1].stmts}
		}
	case 7:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser/grammar.y:293
		{
			yyVAL.stmts = nil
		}
	case 8:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/grammar.y:297
		{
		}
	case 9:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/grammar.y:300
		{
			yyVAL.stmts = append(yyVAL.stmts, yyDollar[2].stmts...)
		}
	case 10:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/grammar.y:307
		{
			yyVAL.mod = &ast.Expression{ModBase: ast.ModBase{Pos: yyVAL.pos}, Body: yyDollar[1].expr}
		}
	case 13:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser/grammar.y:316
		{
			yyVAL.call = &ast.Call{ExprBase: ast.ExprBase{Pos: yyVAL.pos}}
		}
	case 14:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:320
		{
			yyVAL.call = yyDollar[1].call
		}
	case 15:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser/grammar.y:325
		{
			yyVAL.call = nil
		}
	case 16:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/grammar.y:329
		{
			yyVAL.call = yyDollar[2].call
		}
	case 17:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/grammar.y:335
		{
			fn := &ast.Name{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, Id: ast.Identifier(yyDollar[2].str), Ctx: ast.Load}
			if yyDollar[3].call == nil {
				yyVAL.expr = fn
			} else {
				call := *yyDollar[3].call
				call.Func = fn
				yyVAL.expr = &call
			}
		}
	case 18:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:348
		{
			yyVAL.exprs = nil
			yyVAL.exprs = append(yyVAL.exprs, yyDollar[1].expr)
		}
	case 19:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/grammar.y:353
		{
			yyVAL.exprs = append(yyVAL.exprs, yyDollar[2].expr)
		}
	case 20:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:359
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 21:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:363
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 22:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/grammar.y:369
		{
			switch x := (yyDollar[2].stmt).(type) {
			case *ast.ClassDef:
				x.DecoratorList = yyDollar[1].exprs
				yyVAL.stmt = x
			case *ast.FunctionDef:
				x.DecoratorList = yyDollar[1].exprs
				yyVAL.stmt = x
			default:
				panic("bad type for decorated")
			}
		}
	case 23:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser/grammar.y:383
		{
			yyVAL.expr = nil
		}
	case 24:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/grammar.y:387
		{
			yyVAL.expr = yyDollar[2].expr
		}
	case 25:
		yyDollar = yyS[yypt-6 : yypt+1]
//line parser/grammar.y:393
		{
			yyVAL.stmt = &ast.FunctionDef{StmtBase: ast.StmtBase{Pos: yyVAL.pos}, Name: ast.Identifier(yyDollar[2].str), Args: yyDollar[3].arguments, Body: yyDollar[6].stmts, Returns: yyDollar[4].expr}
		}
	case 26:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/grammar.y:399
		{
			yyVAL.arguments = yyDollar[2].arguments
		}
	case 27:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser/grammar.y:404
		{
			yyVAL.arguments = &ast.Arguments{Pos: yyVAL.pos}
		}
	case 28:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:408
		{
			yyVAL.arguments = yyDollar[1].arguments
		}
	case 29:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:415
		{
			yyVAL.arg = yyDollar[1].arg
			yyVAL.expr = nil
		}
	case 30:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/grammar.y:420
		{
			yyVAL.arg = yyDollar[1].arg
			yyVAL.expr = yyDollar[3].expr
		}
	case 31:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser/grammar.y:426
		{
			yyVAL.args = nil
			yyVAL.exprs = nil
		}
	case 32:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/grammar.y:431
		{
			yyVAL.args = append(yyVAL.args, yyDollar[3].arg)
			if yyDollar[3].expr != nil {
				yyVAL.exprs = append(yyVAL.exprs, yyDollar[3].expr)
			}
		}
	case 33:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:440
		{
			yyVAL.args = nil
			yyVAL.args = append(yyVAL.args, yyDollar[1].arg)
			yyVAL.exprs = nil
			if yyDollar[1].expr != nil {
				yyVAL.exprs = append(yyVAL.exprs, yyDollar[1].expr)
			}
		}
	case 34:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/grammar.y:449
		{
			yyVAL.args = append(yyVAL.args, yyDollar[3].arg)
			if yyDollar[3].expr != nil {
				yyVAL.exprs = append(yyVAL.exprs, yyDollar[3].expr)
			}
		}
	case 35:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser/grammar.y:457
		{
			yyVAL.arg = nil
		}
	case 36:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:461
		{
			yyVAL.arg = yyDollar[1].arg
		}
	case 37:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/grammar.y:468
		{
			yyVAL.arguments = &ast.Arguments{Pos: yyVAL.pos, Args: yyDollar[1].args, Defaults: yyDollar[1].exprs}
		}
	case 38:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser/grammar.y:472
		{
			yyVAL.arguments = &ast.Arguments{Pos: yyVAL.pos, Args: yyDollar[1].args, Defaults: yyDollar[1].exprs, Vararg: yyDollar[4].arg, Kwonlyargs: yyDollar[5].args, KwDefaults: yyDollar[5].exprs}
		}
	case 39:
		yyDollar = yyS[yypt-8 : yypt+1]
//line parser/grammar.y:476
		{
			yyVAL.arguments = &ast.Arguments{Pos: yyVAL.pos, Args: yyDollar[1].args, Defaults: yyDollar[1].exprs, Vararg: yyDollar[4].arg, Kwonlyargs: yyDollar[5].args, KwDefaults: yyDollar[5].exprs, Kwarg: yyDollar[8].arg}
		}
	case 40:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/grammar.y:480
		{
			yyVAL.arguments = &ast.Arguments{Pos: yyVAL.pos, Args: yyDollar[1].args, Defaults: yyDollar[1].exprs, Kwarg: yyDollar[4].arg}
		}
	case 41:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/grammar.y:484
		{
			yyVAL.arguments = &ast.Arguments{Pos: yyVAL.pos, Vararg: yyDollar[2].arg, Kwonlyargs: yyDollar[3].args, KwDefaults: yyDollar[3].exprs}
		}
	case 42:
		yyDollar = yyS[yypt-6 : yypt+1]
//line parser/grammar.y:488
		{
			yyVAL.arguments = &ast.Arguments{Pos: yyVAL.pos, Vararg: yyDollar[2].arg, Kwonlyargs: yyDollar[3].args, KwDefaults: yyDollar[3].exprs, Kwarg: yyDollar[6].arg}
		}
	case 43:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/grammar.y:492
		{
			yyVAL.arguments = &ast.Arguments{Pos: yyVAL.pos, Kwarg: yyDollar[2].arg}
		}
	case 44:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:498
		{
			yyVAL.arg = &ast.Arg{Pos: yyVAL.pos, Arg: ast.Identifier(yyDollar[1].str)}
		}
	case 45:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/grammar.y:502
		{
			yyVAL.arg = &ast.Arg{Pos: yyVAL.pos, Arg: ast.Identifier(yyDollar[1].str), Annotation: yyDollar[3].expr}
		}
	case 46:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:508
		{
			yyVAL.arg = yyDollar[1].arg
			yyVAL.expr = nil
		}
	case 47:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/grammar.y:513
		{
			yyVAL.arg = yyDollar[1].arg
			yyVAL.expr = yyDollar[3].expr
		}
	case 48:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser/grammar.y:519
		{
			yyVAL.args = nil
			yyVAL.exprs = nil
		}
	case 49:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/grammar.y:524
		{
			yyVAL.args = append(yyVAL.args, yyDollar[3].arg)
			if yyDollar[3].expr != nil {
				yyVAL.exprs = append(yyVAL.exprs, yyDollar[3].expr)
			}
		}
	case 50:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:533
		{
			yyVAL.args = nil
			yyVAL.args = append(yyVAL.args, yyDollar[1].arg)
			yyVAL.exprs = nil
			if yyDollar[1].expr != nil {
				yyVAL.exprs = append(yyVAL.exprs, yyDollar[1].expr)
			}
		}
	case 51:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/grammar.y:542
		{
			yyVAL.args = append(yyVAL.args, yyDollar[3].arg)
			if yyDollar[3].expr != nil {
				yyVAL.exprs = append(yyVAL.exprs, yyDollar[3].expr)
			}
		}
	case 52:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser/grammar.y:550
		{
			yyVAL.arg = nil
		}
	case 53:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:554
		{
			yyVAL.arg = yyDollar[1].arg
		}
	case 54:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/grammar.y:561
		{
			yyVAL.arguments = &ast.Arguments{Pos: yyVAL.pos, Args: yyDollar[1].args, Defaults: yyDollar[1].exprs}
		}
	case 55:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser/grammar.y:565
		{
			yyVAL.arguments = &ast.Arguments{Pos: yyVAL.pos, Args: yyDollar[1].args, Defaults: yyDollar[1].exprs, Vararg: yyDollar[4].arg, Kwonlyargs: yyDollar[5].args, KwDefaults: yyDollar[5].exprs}
		}
	case 56:
		yyDollar = yyS[yypt-8 : yypt+1]
//line parser/grammar.y:569
		{
			yyVAL.arguments = &ast.Arguments{Pos: yyVAL.pos, Args: yyDollar[1].args, Defaults: yyDollar[1].exprs, Vararg: yyDollar[4].arg, Kwonlyargs: yyDollar[5].args, KwDefaults: yyDollar[5].exprs, Kwarg: yyDollar[8].arg}
		}
	case 57:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/grammar.y:573
		{
			yyVAL.arguments = &ast.Arguments{Pos: yyVAL.pos, Args: yyDollar[1].args, Defaults: yyDollar[1].exprs, Kwarg: yyDollar[4].arg}
		}
	case 58:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/grammar.y:577
		{
			yyVAL.arguments = &ast.Arguments{Pos: yyVAL.pos, Vararg: yyDollar[2].arg, Kwonlyargs: yyDollar[3].args, KwDefaults: yyDollar[3].exprs}
		}
	case 59:
		yyDollar = yyS[yypt-6 : yypt+1]
//line parser/grammar.y:581
		{
			yyVAL.arguments = &ast.Arguments{Pos: yyVAL.pos, Vararg: yyDollar[2].arg, Kwonlyargs: yyDollar[3].args, KwDefaults: yyDollar[3].exprs, Kwarg: yyDollar[6].arg}
		}
	case 60:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/grammar.y:585
		{
			yyVAL.arguments = &ast.Arguments{Pos: yyVAL.pos, Kwarg: yyDollar[2].arg}
		}
	case 61:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:591
		{
			yyVAL.arg = &ast.Arg{Pos: yyVAL.pos, Arg: ast.Identifier(yyDollar[1].str)}
		}
	case 62:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:597
		{
			yyVAL.stmts = yyDollar[1].stmts
		}
	case 63:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:601
		{
			yyVAL.stmts = []ast.Stmt{yyDollar[1].stmt}
		}
	case 66:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:609
		{
			yyVAL.stmts = nil
			yyVAL.stmts = append(yyVAL.stmts, yyDollar[1].stmt)
		}
	case 67:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/grammar.y:614
		{
			yyVAL.stmts = append(yyVAL.stmts, yyDollar[3].stmt)
		}
	case 68:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/grammar.y:620
		{
			yyVAL.stmts = yyDollar[1].stmts
		}
	case 69:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:626
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 70:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:630
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 71:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:634
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 72:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:638
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 73:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:642
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 74:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:646
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 75:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:650
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 76:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:654
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 77:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/grammar.y:681
		{
			target := yyDollar[1].expr
			setCtx(yylex, target, ast.Store)
			yyVAL.stmt = &ast.AugAssign{StmtBase: ast.StmtBase{Pos: yyVAL.pos}, Target: target, Op: yyDollar[2].op, Value: yyDollar[3].expr}
		}
	case 78:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/grammar.y:687
		{
			targets := []ast.Expr{yyDollar[1].expr}
			targets = append(targets, yyDollar[2].exprs...)
			value := targets[len(targets)-1]
			targets = targets[:len(targets)-1]
			setCtxs(yylex, targets, ast.Store)
			yyVAL.stmt = &ast.Assign{StmtBase: ast.StmtBase{Pos: yyVAL.pos}, Targets: targets, Value: value}
		}
	case 79:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:696
		{
			yyVAL.stmt = &ast.ExprStmt{StmtBase: ast.StmtBase{Pos: yyVAL.pos}, Value: yyDollar[1].expr}
		}
	case 80:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/grammar.y:700
		{
			setCtx(yylex, yyDollar[1].expr, ast.Store)
			yyVAL.stmt = &ast.AnnAssign{StmtBase: ast.StmtBase{Pos: yyVAL.pos}, Target: yyDollar[1].expr, Annotation: yyDollar[3].expr}
		}
	case 81:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser/grammar.y:705
		{
			setCtx(yylex, yyDollar[1].expr, ast.Store)
			yyVAL.stmt = &ast.AnnAssign{StmtBase: ast.StmtBase{Pos: yyVAL.pos}, Target: yyDollar[1].expr, Annotation: yyDollar[3].expr, Value: yyDollar[5].expr}
		}
	case 82:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:712
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 83:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:716
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 84:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:722
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 85:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:726
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 86:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/grammar.y:732
		{
			yyVAL.exprs = nil
			yyVAL.exprs = append(yyVAL.exprs, yyDollar[2].expr)
		}
	case 87:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/grammar.y:737
		{
			yyVAL.exprs = append(yyVAL.exprs, yyDollar[3].expr)
		}
	case 88:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:743
		{
			yyVAL.exprs = nil
			yyVAL.exprs = append(yyVAL.exprs, yyDollar[1].expr)
		}
	case 89:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/grammar.y:748
		{
			yyVAL.exprs = append(yyVAL.exprs, yyDollar[3].expr)
		}
	case 90:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:754
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 91:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:758
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 92:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser/grammar.y:763
		{
			yyVAL.comma = false
		}
	case 93:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:767
		{
			yyVAL.comma = true
		}
	case 94:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/grammar.y:773
		{
			yyVAL.expr = tupleOrExpr(yyVAL.pos, yyDollar[1].exprs, yyDollar[2].comma)
		}
	case 95:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:779
		{
			yyVAL.op = ast.Add
		}
	case 96:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:783
		{
			yyVAL.op = ast.Sub
		}
	case 97:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:787
		{
			yyVAL.op = ast.Mult
		}
	case 98:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:791
		{
			yyVAL.op = ast.Div
		}
	case 99:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:795
		{
			yyVAL.op = ast.Modulo
		}
	case 100:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:799
		{
			yyVAL.op = ast.BitAnd
		}
	case 101:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:803
		{
			yyVAL.op = ast.BitOr
		}
	case 102:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:807
		{
			yyVAL.op = ast.BitXor
		}
	case 103:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:811
		{
			yyVAL.op = ast.LShift
		}
	case 104:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:815
		{
			yyVAL.op = ast.RShift
		}
	case 105:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:819
		{
			yyVAL.op = ast.Pow
		}
	case 106:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:823
		{
			yyVAL.op = ast.FloorDiv
		}
	case 107:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/grammar.y:830
		{
			setCtxs(yylex, yyDollar[2].exprs, ast.Del)
			yyVAL.stmt = &ast.Delete{StmtBase: ast.StmtBase{Pos: yyVAL.pos}, Targets: yyDollar[2].exprs}
		}
	case 108:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:837
		{
			yyVAL.stmt = &ast.Pass{StmtBase: ast.StmtBase{Pos: yyVAL.pos}}
		}
	case 109:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:843
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 110:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:847
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 111:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:851
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 112:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:855
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 113:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:859
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 114:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:865
		{
			yyVAL.stmt = &ast.Break{StmtBase: ast.StmtBase{Pos: yyVAL.pos}}
		}
	case 115:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:871
		{
			yyVAL.stmt = &ast.Continue{StmtBase: ast.StmtBase{Pos: yyVAL.pos}}
		}
	case 116:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:877
		{
			yyVAL.stmt = &ast.Return{StmtBase: ast.StmtBase{Pos: yyVAL.pos}}
		}
	case 117:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/grammar.y:881
		{
			yyVAL.stmt = &ast.Return{StmtBase: ast.StmtBase{Pos: yyVAL.pos}, Value: yyDollar[2].expr}
		}
	case 118:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:887
		{
			yyVAL.stmt = &ast.ExprStmt{StmtBase: ast.StmtBase{Pos: yyVAL.pos}, Value: yyDollar[1].expr}
		}
	case 119:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:893
		{
			yyVAL.stmt = &ast.Raise{StmtBase: ast.StmtBase{Pos: yyVAL.pos}}
		}
	case 120:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/grammar.y:897
		{
			yyVAL.stmt = &ast.Raise{StmtBase: ast.StmtBase{Pos: yyVAL.pos}, Exc: yyDollar[2].expr}
		}
	case 121:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/grammar.y:901
		{
			yyVAL.stmt = &ast.Raise{StmtBase: ast.StmtBase{Pos: yyVAL.pos}, Exc: yyDollar[2].expr, Cause: yyDollar[4].expr}
		}
	case 122:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:907
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 123:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:911
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 124:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/grammar.y:917
		{
			yyVAL.stmt = &ast.Import{StmtBase: ast.StmtBase{Pos: yyVAL.pos}, Names: yyDollar[2].aliases}
		}
	case 125:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:924
		{
			yyVAL.level = 1
		}
	case 126:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:928
		{
			yyVAL.level = 3
		}
	case 127:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:934
		{
			yyVAL.level = yyDollar[1].level
		}
	case 128:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/grammar.y:938
		{
			yyVAL.level += yyDollar[2].level
		}
	case 129:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:944
		{
			yyVAL.level = 0
			yyVAL.str = yyDollar[1].str
		}
	case 130:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/grammar.y:949
		{
			yyVAL.level = yyDollar[1].level
			yyVAL.str = yyDollar[2].str
		}
	case 131:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:954
		{
			yyVAL.level = yyDollar[1].level
			yyVAL.str = ""
		}
	case 132:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:961
		{
			yyVAL.aliases = []*ast.Alias{&ast.Alias{Pos: yyVAL.pos, Name: ast.Identifier("*")}}
		}
	case 133:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/grammar.y:965
		{
			yyVAL.aliases = yyDollar[2].aliases
		}
	case 134:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/grammar.y:969
		{
			yyVAL.aliases = yyDollar[1].aliases
		}
	case 135:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/grammar.y:975
		{
			yyVAL.stmt = &ast.ImportFrom{StmtBase: ast.StmtBase{Pos: yyVAL.pos}, Module: ast.Identifier(yyDollar[2].str), Names: yyDollar[4].aliases, Level: yyDollar[2].level}
		}
	case 136:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:981
		{
			yyVAL.alias = &ast.Alias{Pos: yyVAL.pos, Name: ast.Identifier(yyDollar[1].str)}
		}
	case 137:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/grammar.y:985
		{
			yyVAL.alias = &ast.Alias{Pos: yyVAL.pos, Name: ast.Identifier(yyDollar[1].str), AsName: ast.Identifier(yyDollar[3].str)}
		}
	case 138:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:991
		{
			yyVAL.alias = &ast.Alias{Pos: yyVAL.pos, Name: ast.Identifier(yyDollar[1].str)}
		}
	case 139:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/grammar.y:995
		{
			yyVAL.alias = &ast.Alias{Pos: yyVAL.pos, Name: ast.Identifier(yyDollar[1].str), AsName: ast.Identifier(yyDollar[3].str)}
		}
	case 140:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:1001
		{
			yyVAL.aliases = nil
			yyVAL.aliases = append(yyVAL.aliases, yyDollar[1].alias)
		}
	case 141:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/grammar.y:1006
		{
			yyVAL.aliases = append(yyVAL.aliases, yyDollar[3].alias)
		}
	case 142:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:1012
		{
			yyVAL.aliases = nil
			yyVAL.aliases = append(yyVAL.aliases, yyDollar[1].alias)
		}
	case 143:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/grammar.y:1017
		{
			yyVAL.aliases = append(yyVAL.aliases, yyDollar[3].alias)
		}
	case 144:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:1023
		{
			yyVAL.str = yyDollar[1].str
		}
	case 145:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/grammar.y:1027
		{
			yyVAL.str += "." + yyDollar[3].str
		}
	case 146:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:1033
		{
			yyVAL.identifiers = nil
			yyVAL.identifiers = append(yyVAL.identifiers, ast.Identifier(yyDollar[1].str))
		}
	case 147:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/grammar.y:1038
		{
			yyVAL.identifiers = append(yyVAL.identifiers, ast.Identifier(yyDollar[3].str))
		}
	case 148:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/grammar.y:1044
		{
			yyVAL.stmt = &ast.Global{StmtBase: ast.StmtBase{Pos: yyVAL.pos}, Names: yyDollar[2].identifiers}
		}
	case 149:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/grammar.y:1050
		{
			yyVAL.stmt = &ast.Nonlocal{StmtBase: ast.StmtBase{Pos: yyVAL.pos}, Names: yyDollar[2].identifiers}
		}
	case 150:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:1056
		{
			yyVAL.exprs = nil
			yyVAL.exprs = append(yyVAL.exprs, yyDollar[1].expr)
		}
	case 151:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/grammar.y:1061
		{
			yyVAL.exprs = append(yyVAL.exprs, yyDollar[3].expr)
		}
	case 152:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/grammar.y:1067
		{
			yyVAL.stmt = &ast.Assert{StmtBase: ast.StmtBase{Pos: yyVAL.pos}, Test: yyDollar[2].expr}
		}
	case 153:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/grammar.y:1071
		{
			yyVAL.stmt = &ast.Assert{StmtBase: ast.StmtBase{Pos: yyVAL.pos}, Test: yyDollar[2].expr, Msg: yyDollar[4].expr}
		}
	case 154:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:1077
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 155:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:1081
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 156:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:1085
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 157:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:1089
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 158:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:1093
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 159:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:1097
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 160:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:1101
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 161:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:1105
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 162:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser/grammar.y:1110
		{
			yyVAL.ifstmt = nil
			yyVAL.lastif = nil
		}
	case 163:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser/grammar.y:1115
		{
			elifs := yyVAL.ifstmt
			newif := &ast.If{StmtBase: ast.StmtBase{Pos: yyVAL.pos}, Test: yyDollar[3].expr, Body: yyDollar[5].stmts}
			if elifs == nil {
				yyVAL.ifstmt = newif
			} else {
				yyVAL.lastif.Orelse = []ast.Stmt{newif}
			}
			yyVAL.lastif = newif
		}
	case 164:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser/grammar.y:1127
		{
			yyVAL.stmts = nil
		}
	case 165:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/grammar.y:1131
		{
			yyVAL.stmts = yyDollar[3].stmts
		}
	case 166:
		yyDollar = yyS[yypt-6 : yypt+1]
//line parser/grammar.y:1137
		{
			newif := &ast.If{StmtBase: ast.StmtBase{Pos: yyVAL.pos}, Test: yyDollar[2].expr, Body: yyDollar[4].stmts}
			yyVAL.stmt = newif
			elifs := yyDollar[5].ifstmt
			optional_else := yyDollar[6].stmts
			if len(optional_else) != 0 {
				if elifs != nil {
					yyDollar[5].lastif.Orelse = optional_else
					newif.Orelse = []ast.Stmt{elifs}
				} else {
					newif.Orelse = optional_else
				}
			} else {
				if elifs != nil {
					newif.Orelse = []ast.Stmt{elifs}
				}
			}
		}
	case 167:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser/grammar.y:1158
		{
			yyVAL.stmt = &ast.While{StmtBase: ast.StmtBase{Pos: yyVAL.pos}, Test: yyDollar[2].expr, Body: yyDollar[4].stmts, Orelse: yyDollar[5].stmts}
		}
	case 168:
		yyDollar = yyS[yypt-7 : yypt+1]
//line parser/grammar.y:1164
		{
			target := tupleOrExpr(yyVAL.pos, yyDollar[2].exprs, false)
			setCtx(yylex, target, ast.Store)
			yyVAL.stmt = &ast.For{StmtBase: ast.StmtBase{Pos: yyVAL.pos}, Target: target, Iter: yyDollar[4].expr, Body: yyDollar[6].stmts, Orelse: yyDollar[7].stmts}
		}
	case 169:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser/grammar.y:1171
		{
			yyVAL.exchandlers = nil
		}
	case 170:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/grammar.y:1175
		{
			exc := &ast.ExceptHandler{Pos: yyVAL.pos, ExprType: yyDollar[2].expr, Name: ast.Identifier(yyDollar[2].str), Body: yyDollar[4].stmts}
			yyVAL.exchandlers = append(yyVAL.exchandlers, exc)
		}
	case 171:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/grammar.y:1182
		{
			yyVAL.stmt = &ast.Try{StmtBase: ast.StmtBase{Pos: yyVAL.pos}, Body: yyDollar[3].stmts, Handlers: yyDollar[4].exchandlers}
		}
	case 172:
		yyDollar = yyS[yypt-7 : yypt+1]
//line parser/grammar.y:1186
		{
			yyVAL.stmt = &ast.Try{StmtBase: ast.StmtBase{Pos: yyVAL.pos}, Body: yyDollar[3].stmts, Handlers: yyDollar[4].exchandlers, Orelse: yyDollar[7].stmts}
		}
	case 173:
		yyDollar = yyS[yypt-7 : yypt+1]
//line parser/grammar.y:1190
		{
			yyVAL.stmt = &ast.Try{StmtBase: ast.StmtBase{Pos: yyVAL.pos}, Body: yyDollar[3].stmts, Handlers: yyDollar[4].exchandlers, Finalbody: yyDollar[7].stmts}
		}
	case 174:
		yyDollar = yyS[yypt-10 : yypt+1]
//line parser/grammar.y:1194
		{
			yyVAL.stmt = &ast.Try{StmtBase: ast.StmtBase{Pos: yyVAL.pos}, Body: yyDollar[3].stmts, Handlers: yyDollar[4].exchandlers, Orelse: yyDollar[7].stmts, Finalbody: yyDollar[10].stmts}
		}
	case 175:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:1200
		{
			yyVAL.withitems = nil
			yyVAL.withitems = append(yyVAL.withitems, yyDollar[1].withitem)
		}
	case 176:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/grammar.y:1205
		{
			yyVAL.withitems = append(yyVAL.withitems, yyDollar[3].withitem)
		}
	case 177:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/grammar.y:1211
		{
			yyVAL.stmt = &ast.With{StmtBase: ast.StmtBase{Pos: yyVAL.pos}, Items: yyDollar[2].withitems, Body: yyDollar[4].stmts}
		}
	case 178:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:1217
		{
			yyVAL.withitem = &ast.WithItem{Pos: yyVAL.pos, ContextExpr: yyDollar[1].expr}
		}
	case 179:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/grammar.y:1221
		{
			v := yyDollar[3].expr
			setCtx(yylex, v, ast.Store)
			yyVAL.withitem = &ast.WithItem{Pos: yyVAL.pos, ContextExpr: yyDollar[1].expr, OptionalVars: v}
		}
	case 180:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:1230
		{
			yyVAL.expr = nil
			yyVAL.str = ""
		}
	case 181:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/grammar.y:1235
		{
			yyVAL.expr = yyDollar[2].expr
			yyVAL.str = ""
		}
	case 182:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/grammar.y:1240
		{
			yyVAL.expr = yyDollar[2].expr
			yyVAL.str = yyDollar[4].str
		}
	case 183:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:1247
		{
			yyVAL.stmts = nil
			yyVAL.stmts = append(yyVAL.stmts, yyDollar[1].stmts...)
		}
	case 184:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/grammar.y:1252
		{
			yyVAL.stmts = append(yyVAL.stmts, yyDollar[2].stmts...)
		}
	case 185:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:1258
		{
			yyVAL.stmts = yyDollar[1].stmts
		}
	case 186:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/grammar.y:1262
		{
			yyVAL.stmts = yyDollar[3].stmts
		}
	case 187:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:1268
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 188:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser/grammar.y:1272
		{
			yyVAL.expr = &ast.IfExp{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, Test: yyDollar[3].expr, Body: yyDollar[1].expr, Orelse: yyDollar[5].expr}
		}
	case 189:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:1276
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 190:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:1282
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 191:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:1286
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 192:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/grammar.y:1292
		{
			args := &ast.Arguments{Pos: yyVAL.pos}
			yyVAL.expr = &ast.Lambda{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, Args: args, Body: yyDollar[3].expr}
		}
	case 193:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/grammar.y:1297
		{
			yyVAL.expr = &ast.Lambda{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, Args: yyDollar[2].arguments, Body: yyDollar[4].expr}
		}
	case 194:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/grammar.y:1303
		{
			args := &ast.Arguments{Pos: yyVAL.pos}
			yyVAL.expr = &ast.Lambda{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, Args: args, Body: yyDollar[3].expr}
		}
	case 195:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/grammar.y:1308
		{
			yyVAL.expr = &ast.Lambda{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, Args: yyDollar[2].arguments, Body: yyDollar[4].expr}
		}
	case 196:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:1314
		{
			yyVAL.expr = yyDollar[1].expr
			yyVAL.isExpr = true
		}
	case 197:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/grammar.y:1319
		{
			if !yyDollar[1].isExpr {
				boolop := yyVAL.expr.(*ast.BoolOp)
				boolop.Values = append(boolop.Values, yyDollar[3].expr)
			} else {
				yyVAL.expr = &ast.BoolOp{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, Op: ast.Or, Values: []ast.Expr{yyVAL.expr, yyDollar[3].expr}}
			}
			yyVAL.isExpr = false
		}
	case 198:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:1331
		{
			yyVAL.expr = yyDollar[1].expr
			yyVAL.isExpr = true
		}
	case 199:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/grammar.y:1336
		{
			if !yyDollar[1].isExpr {
				boolop := yyVAL.expr.(*ast.BoolOp)
				boolop.Values = append(boolop.Values, yyDollar[3].expr)
			} else {
				yyVAL.expr = &ast.BoolOp{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, Op: ast.And, Values: []ast.Expr{yyVAL.expr, yyDollar[3].expr}}
			}
			yyVAL.isExpr = false
		}
	case 200:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/grammar.y:1348
		{
			yyVAL.expr = &ast.UnaryOp{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, Op: ast.Not, Operand: yyDollar[2].expr}
		}
	case 201:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:1352
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 202:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:1358
		{
			yyVAL.expr = yyDollar[1].expr
			yyVAL.isExpr = true
		}
	case 203:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/grammar.y:1363
		{
			if !yyDollar[1].isExpr {
				comp := yyVAL.expr.(*ast.Compare)
				comp.Ops = append(comp.Ops, yyDollar[2].cmpop)
				comp.Comparators = append(comp.Comparators, yyDollar[3].expr)
			} else {
				yyVAL.expr = &ast.Compare{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, Left: yyVAL.expr, Ops: []ast.CmpOp{yyDollar[2].cmpop}, Comparators: []ast.Expr{yyDollar[3].expr}}
			}
			yyVAL.isExpr = false
		}
	case 204:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:1378
		{
			yyVAL.cmpop = ast.Lt
		}
	case 205:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:1382
		{
			yyVAL.cmpop = ast.Gt
		}
	case 206:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:1386
		{
			yyVAL.cmpop = ast.Eq
		}
	case 207:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:1390
		{
			yyVAL.cmpop = ast.GtE
		}
	case 208:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:1394
		{
			yyVAL.cmpop = ast.LtE
		}
	case 209:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:1398
		{
			yylex.(*yyLex).SyntaxError("invalid syntax")
		}
	case 210:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:1402
		{
			yyVAL.cmpop = ast.NotEq
		}
	case 211:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:1406
		{
			yyVAL.cmpop = ast.In
		}
	case 212:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/grammar.y:1410
		{
			yyVAL.cmpop = ast.NotIn
		}
	case 213:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:1414
		{
			yyVAL.cmpop = ast.Is
		}
	case 214:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/grammar.y:1418
		{
			yyVAL.cmpop = ast.IsNot
		}
	case 215:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/grammar.y:1424
		{
			yyVAL.expr = &ast.Starred{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, Value: yyDollar[2].expr, Ctx: ast.Load}
		}
	case 216:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:1430
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 217:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/grammar.y:1434
		{
			yyVAL.expr = &ast.BinOp{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, Left: yyDollar[1].expr, Op: ast.BitOr, Right: yyDollar[3].expr}
		}
	case 218:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:1440
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 219:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/grammar.y:1444
		{
			yyVAL.expr = &ast.BinOp{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, Left: yyDollar[1].expr, Op: ast.BitXor, Right: yyDollar[3].expr}
		}
	case 220:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:1450
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 221:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/grammar.y:1454
		{
			yyVAL.expr = &ast.BinOp{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, Left: yyDollar[1].expr, Op: ast.BitAnd, Right: yyDollar[3].expr}
		}
	case 222:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:1460
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 223:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/grammar.y:1464
		{
			yyVAL.expr = &ast.BinOp{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, Left: yyDollar[1].expr, Op: ast.LShift, Right: yyDollar[3].expr}
		}
	case 224:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/grammar.y:1468
		{
			yyVAL.expr = &ast.BinOp{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, Left: yyDollar[1].expr, Op: ast.RShift, Right: yyDollar[3].expr}
		}
	case 225:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:1474
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 226:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/grammar.y:1478
		{
			yyVAL.expr = &ast.BinOp{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, Left: yyDollar[1].expr, Op: ast.Add, Right: yyDollar[3].expr}
		}
	case 227:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/grammar.y:1482
		{
			yyVAL.expr = &ast.BinOp{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, Left: yyDollar[1].expr, Op: ast.Sub, Right: yyDollar[3].expr}
		}
	case 228:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:1488
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 229:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/grammar.y:1492
		{
			yyVAL.expr = &ast.BinOp{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, Left: yyDollar[1].expr, Op: ast.Mult, Right: yyDollar[3].expr}
		}
	case 230:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/grammar.y:1496
		{
			yyVAL.expr = &ast.BinOp{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, Left: yyDollar[1].expr, Op: ast.Div, Right: yyDollar[3].expr}
		}
	case 231:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/grammar.y:1500
		{
			yyVAL.expr = &ast.BinOp{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, Left: yyDollar[1].expr, Op: ast.Modulo, Right: yyDollar[3].expr}
		}
	case 232:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/grammar.y:1504
		{
			yyVAL.expr = &ast.BinOp{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, Left: yyDollar[1].expr, Op: ast.FloorDiv, Right: yyDollar[3].expr}
		}
	case 233:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/grammar.y:1510
		{
			yyVAL.expr = &ast.UnaryOp{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, Op: ast.UAdd, Operand: yyDollar[2].expr}
		}
	case 234:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/grammar.y:1514
		{
			yyVAL.expr = &ast.UnaryOp{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, Op: ast.USub, Operand: yyDollar[2].expr}
		}
	case 235:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/grammar.y:1518
		{
			yyVAL.expr = &ast.UnaryOp{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, Op: ast.Invert, Operand: yyDollar[2].expr}
		}
	case 236:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:1522
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 237:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/grammar.y:1528
		{
			yyVAL.expr = applyTrailers(yyDollar[1].expr, yyDollar[2].exprs)
		}
	case 238:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/grammar.y:1532
		{
			yyVAL.expr = &ast.BinOp{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, Left: applyTrailers(yyDollar[1].expr, yyDollar[2].exprs), Op: ast.Pow, Right: yyDollar[4].expr}
		}
	case 239:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser/grammar.y:1538
		{
			yyVAL.exprs = nil
		}
	case 240:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/grammar.y:1542
		{
			yyVAL.exprs = append(yyVAL.exprs, yyDollar[2].expr)
		}
	case 241:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:1548
		{
			yyVAL.obj = yyDollar[1].obj
		}
	case 242:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/grammar.y:1552
		{
			switch a := yyVAL.obj.(type) {
			case py.String:
				switch b := yyDollar[2].obj.(type) {
				case py.String:
					yyVAL.obj = a + b
				default:
					yylex.(*yyLex).SyntaxError("cannot mix string and nonstring literals")
				}
			case py.Bytes:
				switch b := yyDollar[2].obj.(type) {
				case py.Bytes:
					yyVAL.obj = append(a, b...)
				default:
					yylex.(*yyLex).SyntaxError("cannot mix bytes and nonbytes literals")
				}
			}
		}
	case 243:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/grammar.y:1573
		{
			yyVAL.expr = &ast.Tuple{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, Ctx: ast.Load}
		}
	case 244:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/grammar.y:1577
		{
			yyVAL.expr = yyDollar[2].expr
		}
	case 245:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/grammar.y:1581
		{
			yyVAL.expr = &ast.GeneratorExp{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, Elt: yyDollar[2].expr, Generators: yyDollar[3].comprehensions}
		}
	case 246:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/grammar.y:1585
		{
			yyVAL.expr = tupleOrExpr(yyVAL.pos, yyDollar[2].exprs, yyDollar[3].comma)
		}
	case 247:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/grammar.y:1589
		{
			yyVAL.expr = &ast.List{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, Ctx: ast.Load}
		}
	case 248:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/grammar.y:1593
		{
			yyVAL.expr = &ast.ListComp{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, Elt: yyDollar[2].expr, Generators: yyDollar[3].comprehensions}
		}
	case 249:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/grammar.y:1597
		{
			yyVAL.expr = &ast.List{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, Elts: yyDollar[2].exprs, Ctx: ast.Load}
		}
	case 250:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/grammar.y:1601
		{
			yyVAL.expr = &ast.Dict{ExprBase: ast.ExprBase{Pos: yyVAL.pos}}
		}
	case 251:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/grammar.y:1605
		{
			yyVAL.expr = yyDollar[2].expr
		}
	case 252:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:1609
		{
			yyVAL.expr = &ast.Name{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, Id: ast.Identifier(yyDollar[1].str), Ctx: ast.Load}
		}
	case 253:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:1613
		{
			yyVAL.expr = &ast.Num{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, N: yyDollar[1].obj}
		}
	case 254:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:1617
		{
			switch s := yyDollar[1].obj.(type) {
			case py.String:
				yyVAL.expr = &ast.Str{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, S: s}
			case py.Bytes:
				yyVAL.expr = &ast.Bytes{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, S: s}
			case *py.FString:
				yyVAL.expr = &ast.FString{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, Text: s.Text, Raw: s.Raw}
			default:
				panic("not Bytes or String in strings")
			}
		}
	case 255:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:1630
		{
			yyVAL.expr = &ast.Ellipsis{ExprBase: ast.ExprBase{Pos: yyVAL.pos}}
		}
	case 256:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:1634
		{
			yyVAL.expr = &ast.NameConstant{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, Value: py.None}
		}
	case 257:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:1638
		{
			yyVAL.expr = &ast.NameConstant{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, Value: py.True}
		}
	case 258:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:1642
		{
			yyVAL.expr = &ast.NameConstant{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, Value: py.False}
		}
	case 259:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/grammar.y:1649
		{
			yyVAL.expr = &ast.Call{ExprBase: ast.ExprBase{Pos: yyVAL.pos}}
		}
	case 260:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/grammar.y:1653
		{
			yyVAL.expr = yyDollar[2].call
		}
	case 261:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/grammar.y:1657
		{
			slice := yyDollar[2].slice
			// If all items of a ExtSlice are just Index then return as tuple
			if extslice, ok := slice.(*ast.ExtSlice); ok {
				elts := make([]ast.Expr, len(extslice.Dims))
				for i, item := range extslice.Dims {
					if index, isIndex := item.(*ast.Index); isIndex {
						elts[i] = index.Value
					} else {
						goto notAllIndex
					}
				}
				slice = &ast.Index{SliceBase: extslice.SliceBase, Value: &ast.Tuple{ExprBase: ast.ExprBase{Pos: extslice.SliceBase.Pos}, Elts: elts, Ctx: ast.Load}}
			notAllIndex:
			}
			yyVAL.expr = &ast.Subscript{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, Slice: slice, Ctx: ast.Load}
		}
	case 262:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/grammar.y:1675
		{
			yyVAL.expr = &ast.Attribute{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, Attr: ast.Identifier(yyDollar[2].str), Ctx: ast.Load}
		}
	case 263:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:1681
		{
			yyVAL.slice = yyDollar[1].slice
			yyVAL.isExpr = true
		}
	case 264:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/grammar.y:1686
		{
			if !yyDollar[1].isExpr {
				extSlice := yyVAL.slice.(*ast.ExtSlice)
				extSlice.Dims = append(extSlice.Dims, yyDollar[3].slice)
			} else {
				yyVAL.slice = &ast.ExtSlice{SliceBase: ast.SliceBase{Pos: yyVAL.pos}, Dims: []ast.Slicer{yyDollar[1].slice, yyDollar[3].slice}}
			}
			yyVAL.isExpr = false
		}
	case 265:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/grammar.y:1698
		{
			if yyDollar[2].comma && yyDollar[1].isExpr {
				yyVAL.slice = &ast.ExtSlice{SliceBase: ast.SliceBase{Pos: yyVAL.pos}, Dims: []ast.Slicer{yyDollar[1].slice}}
			} else {
				yyVAL.slice = yyDollar[1].slice
			}
		}
	case 266:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:1708
		{
			yyVAL.slice = &ast.Index{SliceBase: ast.SliceBase{Pos: yyVAL.pos}, Value: yyDollar[1].expr}
		}
	case 267:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:1712
		{
			yyVAL.slice = &ast.Slice{SliceBase: ast.SliceBase{Pos: yyVAL.pos}, Lower: nil, Upper: nil, Step: nil}
		}
	case 268:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/grammar.y:1716
		{
			yyVAL.slice = &ast.Slice{SliceBase: ast.SliceBase{Pos: yyVAL.pos}, Lower: nil, Upper: nil, Step: yyDollar[2].expr}
		}
	case 269:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/grammar.y:1720
		{
			yyVAL.slice = &ast.Slice{SliceBase: ast.SliceBase{Pos: yyVAL.pos}, Lower: nil, Upper: yyDollar[2].expr, Step: nil}
		}
	case 270:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/grammar.y:1724
		{
			yyVAL.slice = &ast.Slice{SliceBase: ast.SliceBase{Pos: yyVAL.pos}, Lower: nil, Upper: yyDollar[2].expr, Step: yyDollar[3].expr}
		}
	case 271:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/grammar.y:1728
		{
			yyVAL.slice = &ast.Slice{SliceBase: ast.SliceBase{Pos: yyVAL.pos}, Lower: yyDollar[1].expr, Upper: nil, Step: nil}
		}
	case 272:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/grammar.y:1732
		{
			yyVAL.slice = &ast.Slice{SliceBase: ast.SliceBase{Pos: yyVAL.pos}, Lower: yyDollar[1].expr, Upper: nil, Step: yyDollar[3].expr}
		}
	case 273:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/grammar.y:1736
		{
			yyVAL.slice = &ast.Slice{SliceBase: ast.SliceBase{Pos: yyVAL.pos}, Lower: yyDollar[1].expr, Upper: yyDollar[3].expr, Step: nil}
		}
	case 274:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/grammar.y:1740
		{
			yyVAL.slice = &ast.Slice{SliceBase: ast.SliceBase{Pos: yyVAL.pos}, Lower: yyDollar[1].expr, Upper: yyDollar[3].expr, Step: yyDollar[4].expr}
		}
	case 275:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:1746
		{
			yyVAL.expr = nil
		}
	case 276:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/grammar.y:1750
		{
			yyVAL.expr = yyDollar[2].expr
		}
	case 277:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:1756
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 278:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:1760
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 279:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:1766
		{
			yyVAL.exprs = nil
			yyVAL.exprs = append(yyVAL.exprs, yyDollar[1].expr)
		}
	case 280:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/grammar.y:1771
		{
			yyVAL.exprs = append(yyVAL.exprs, yyDollar[3].expr)
		}
	case 281:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/grammar.y:1777
		{
			yyVAL.exprs = yyDollar[1].exprs
			yyVAL.comma = yyDollar[2].comma
		}
	case 282:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/grammar.y:1784
		{
			elts := yyDollar[1].exprs
			if yyDollar[2].comma || len(elts) > 1 {
				yyVAL.expr = &ast.Tuple{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, Elts: elts, Ctx: ast.Load}
			} else {
				yyVAL.expr = elts[0]
			}
		}
	case 283:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/grammar.y:1795
		{
			yyVAL.exprs = yyDollar[1].exprs
		}
	case 284:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/grammar.y:1802
		{
			yyVAL.exprs = nil
			yyVAL.exprs = append(yyVAL.exprs, yyDollar[1].expr, yyDollar[3].expr) // key, value order
		}
	case 285:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser/grammar.y:1807
		{
			yyVAL.exprs = append(yyVAL.exprs, yyDollar[3].expr, yyDollar[5].expr)
		}
	case 286:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/grammar.y:1813
		{
			keyValues := yyDollar[1].exprs
			d := &ast.Dict{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, Keys: nil, Values: nil}
			for i := 0; i < len(keyValues)-1; i += 2 {
				d.Keys = append(d.Keys, keyValues[i])
				d.Values = append(d.Values, keyValues[i+1])
			}
			yyVAL.expr = d
		}
	case 287:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/grammar.y:1823
		{
			yyVAL.expr = &ast.DictComp{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, Key: yyDollar[1].expr, Value: yyDollar[3].expr, Generators: yyDollar[4].comprehensions}
		}
	case 288:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:1827
		{
			yyVAL.expr = &ast.Set{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, Elts: yyDollar[1].exprs}
		}
	case 289:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/grammar.y:1831
		{
			yyVAL.expr = &ast.SetComp{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, Elt: yyDollar[1].expr, Generators: yyDollar[2].comprehensions}
		}
	case 290:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser/grammar.y:1837
		{
			classDef := &ast.ClassDef{StmtBase: ast.StmtBase{Pos: yyVAL.pos}, Name: ast.Identifier(yyDollar[2].str), Body: yyDollar[5].stmts}
			yyVAL.stmt = classDef
			args := yyDollar[3].call
			if args != nil {
				classDef.Bases = args.Args
				classDef.Keywords = args.Keywords
				classDef.Starargs = args.Starargs
				classDef.Kwargs = args.Kwargs
			}
		}
	case 291:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:1851
		{
			yyVAL.call = yyDollar[1].call
		}
	case 292:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/grammar.y:1855
		{
			yyVAL.call.Args = append(yyVAL.call.Args, yyDollar[3].call.Args...)
			yyVAL.call.Keywords = append(yyVAL.call.Keywords, yyDollar[3].call.Keywords...)
		}
	case 293:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser/grammar.y:1861
		{
			yyVAL.call = &ast.Call{}
		}
	case 294:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/grammar.y:1865
		{
			yyVAL.call = yyDollar[1].call
		}
	case 295:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser/grammar.y:1870
		{
			yyVAL.call = &ast.Call{}
		}
	case 296:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/grammar.y:1874
		{
			yyVAL.call.Args = append(yyVAL.call.Args, yyDollar[3].call.Args...)
			yyVAL.call.Keywords = append(yyVAL.call.Keywords, yyDollar[3].call.Keywords...)
		}
	case 297:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/grammar.y:1881
		{
			yyVAL.call = yyDollar[1].call
		}
	case 298:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/grammar.y:1885
		{
			call := yyDollar[1].call
			call.Starargs = yyDollar[3].expr
			if len(yyDollar[4].call.Args) != 0 {
				yylex.(*yyLex).SyntaxError("only named arguments may follow *expression")
			}
			call.Keywords = append(call.Keywords, yyDollar[4].call.Keywords...)
			yyVAL.call = call
		}
	case 299:
		yyDollar = yyS[yypt-7 : yypt+1]
//line parser/grammar.y:1895
		{
			call := yyDollar[1].call
			call.Starargs = yyDollar[3].expr
			call.Kwargs = yyDollar[7].expr
			if len(yyDollar[4].call.Args) != 0 {
				yylex.(*yyLex).SyntaxError("only named arguments may follow *expression")
			}
			call.Keywords = append(call.Keywords, yyDollar[4].call.Keywords...)
			yyVAL.call = call
		}
	case 300:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/grammar.y:1906
		{
			call := yyDollar[1].call
			call.Kwargs = yyDollar[3].expr
			yyVAL.call = call
		}
	case 301:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:1916
		{
			yyVAL.call = &ast.Call{}
			yyVAL.call.Args = []ast.Expr{yyDollar[1].expr}
		}
	case 302:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/grammar.y:1921
		{
			yyVAL.call = &ast.Call{}
			yyVAL.call.Args = []ast.Expr{
				&ast.GeneratorExp{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, Elt: yyDollar[1].expr, Generators: yyDollar[2].comprehensions},
			}
		}
	case 303:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/grammar.y:1928
		{
			yyVAL.call = &ast.Call{}
			test := yyDollar[1].expr
			if name, ok := test.(*ast.Name); ok {
				yyVAL.call.Keywords = []*ast.Keyword{&ast.Keyword{Pos: name.Pos, Arg: name.Id, Value: yyDollar[3].expr}}
			} else {
				yylex.(*yyLex).SyntaxError("keyword can't be an expression")
			}
		}
	case 304:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:1940
		{
			yyVAL.comprehensions = yyDollar[1].comprehensions
			yyVAL.exprs = nil
		}
	case 305:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:1945
		{
			yyVAL.comprehensions = yyDollar[1].comprehensions
			yyVAL.exprs = yyDollar[1].exprs
		}
	case 306:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/grammar.y:1952
		{
			c := ast.Comprehension{
				Target: tupleOrExpr(yyVAL.pos, yyDollar[2].exprs, yyDollar[2].comma),
				Iter:   yyDollar[4].expr,
			}
			setCtx(yylex, c.Target, ast.Store)
			yyVAL.comprehensions = []ast.Comprehension{c}
		}
	case 307:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser/grammar.y:1961
		{
			c := ast.Comprehension{
				Target: tupleOrExpr(yyVAL.pos, yyDollar[2].exprs, yyDollar[2].comma),
				Iter:   yyDollar[4].expr,
				Ifs:    yyDollar[5].exprs,
			}
			setCtx(yylex, c.Target, ast.Store)
			yyVAL.comprehensions = []ast.Comprehension{c}
			yyVAL.comprehensions = append(yyVAL.comprehensions, yyDollar[5].comprehensions...)
		}
	case 308:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/grammar.y:1974
		{
			yyVAL.exprs = []ast.Expr{yyDollar[2].expr}
			yyVAL.comprehensions = nil
		}
	case 309:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/grammar.y:1979
		{
			yyVAL.exprs = []ast.Expr{yyDollar[2].expr}
			yyVAL.exprs = append(yyVAL.exprs, yyDollar[3].exprs...)
			yyVAL.comprehensions = yyDollar[3].comprehensions
		}
	case 310:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:1990
		{
			yyVAL.expr = &ast.Yield{ExprBase: ast.ExprBase{Pos: yyVAL.pos}}
		}
	case 311:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/grammar.y:1994
		{
			yyVAL.expr = &ast.YieldFrom{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, Value: yyDollar[3].expr}
		}
	case 312:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/grammar.y:1998
		{
			yyVAL.expr = &ast.Yield{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, Value: yyDollar[2].expr}
		}
	}
	goto yystack /* stack new state and value */
}
