// Code generated by goyacc -v parser/y.output -o parser/y.go parser/grammar.y. DO NOT EDIT.

//line parser/grammar.y:6

package parser

import __yyfmt__ "fmt"

//line parser/grammar.y:7

// Grammar for Python

import (
	"fmt"
	"github.com/vishnukv64/gpython/ast"
	"github.com/vishnukv64/gpython/py"
)

// NB can put code blocks in not just at the end

// posonlyArgs carries the positional-only parameters of a function
// definition (PEP 570) from the posonly_prefix rule down to the
// typedargslist rules that build the ast.Arguments.
type posonlyArgs struct {
	args     []*ast.Arg
	defaults []ast.Expr
}

// Returns a Tuple if > 1 items or a trailing comma, otherwise returns
// the first item in elts
func tupleOrExpr(pos ast.Pos, elts []ast.Expr, optional_comma bool) ast.Expr {
	if optional_comma || len(elts) > 1 {
		return &ast.Tuple{ExprBase: ast.ExprBase{Pos: pos}, Elts: elts, Ctx: ast.Load}
	} else {
		return elts[0]
	}
}

// Apply trailers (if any) to expr
//
// trailers are half made Call, Subscript or Attribute
func applyTrailers(expr ast.Expr, trailers []ast.Expr) ast.Expr {
	//trailers := $1
	for _, trailer := range trailers {
		switch x := trailer.(type) {
		case *ast.Call:
			x.Func, expr = expr, x
		case *ast.Subscript:
			x.Value, expr = expr, x
		case *ast.Attribute:
			x.Value, expr = expr, x
		default:
			panic(fmt.Sprintf("Unknown trailer type: %T", expr))
		}
	}
	return expr
}

// Set the context for expr
func setCtx(yylex yyLexer, expr ast.Expr, ctx ast.ExprContext) {
	setctxer, ok := expr.(ast.SetCtxer)
	if !ok {
		expr_name := ""
		switch expr.(type) {
		case *ast.Lambda:
			expr_name = "lambda"
		case *ast.Call:
			expr_name = "function call"
		case *ast.BoolOp, *ast.BinOp, *ast.UnaryOp:
			expr_name = "operator"
		case *ast.GeneratorExp:
			expr_name = "generator expression"
		case *ast.Yield, *ast.YieldFrom:
			expr_name = "yield expression"
		case *ast.ListComp:
			expr_name = "list comprehension"
		case *ast.SetComp:
			expr_name = "set comprehension"
		case *ast.DictComp:
			expr_name = "dict comprehension"
		case *ast.Dict, *ast.Set, *ast.Num, *ast.Str, *ast.Bytes:
			expr_name = "literal"
		case *ast.NameConstant:
			expr_name = "keyword"
		case *ast.Ellipsis:
			expr_name = "Ellipsis"
		case *ast.Compare:
			expr_name = "comparison"
		case *ast.IfExp:
			expr_name = "conditional expression"
		default:
			expr_name = fmt.Sprintf("unexpected %T", expr)
		}
		action := "assign to"
		if ctx == ast.Del {
			action = "delete"
		}
		yylex.(*yyLex).SyntaxErrorf("can't %s %s", action, expr_name)
		return
	}
	setctxer.SetCtx(ctx)
}

// Set the context for all the items in exprs
func setCtxs(yylex yyLexer, exprs []ast.Expr, ctx ast.ExprContext) {
	for i := range exprs {
		setCtx(yylex, exprs[i], ctx)
	}
}

//line parser/grammar.y:111
type yySymType struct {
	yys            int
	pos            ast.Pos // kept up to date by the lexer
	str            string
	obj            py.Object
	mod            ast.Mod
	stmt           ast.Stmt
	stmts          []ast.Stmt
	expr           ast.Expr
	exprs          []ast.Expr
	op             ast.OperatorNumber
	cmpop          ast.CmpOp
	comma          bool
	comprehensions []ast.Comprehension
	isExpr         bool
	slice          ast.Slicer
	call           *ast.Call
	level          int
	alias          *ast.Alias
	aliases        []*ast.Alias
	identifiers    []ast.Identifier
	ifstmt         *ast.If
	lastif         *ast.If
	exchandlers    []*ast.ExceptHandler
	withitem       *ast.WithItem
	withitems      []*ast.WithItem
	arg            *ast.Arg
	annassign      *ast.AnnAssign
	posonly        posonlyArgs
	args           []*ast.Arg
	arguments      *ast.Arguments
}

const NEWLINE = 57346
const ENDMARKER = 57347
const NAME = 57348
const INDENT = 57349
const DEDENT = 57350
const STRING = 57351
const NUMBER = 57352
const PLINGEQ = 57353
const PERCEQ = 57354
const ANDEQ = 57355
const STARSTAR = 57356
const STARSTAREQ = 57357
const STAREQ = 57358
const PLUSEQ = 57359
const MINUSEQ = 57360
const MINUSGT = 57361
const ELIPSIS = 57362
const DIVDIV = 57363
const DIVDIVEQ = 57364
const DIVEQ = 57365
const LTLT = 57366
const LTLTEQ = 57367
const LTEQ = 57368
const LTGT = 57369
const EQEQ = 57370
const GTEQ = 57371
const GTGT = 57372
const GTGTEQ = 57373
const HATEQ = 57374
const PIPEEQ = 57375
const FALSE = 57376
const NONE = 57377
const TRUE = 57378
const AND = 57379
const AS = 57380
const ASSERT = 57381
const BREAK = 57382
const CLASS = 57383
const CONTINUE = 57384
const DEF = 57385
const DEL = 57386
const ELIF = 57387
const ELSE = 57388
const EXCEPT = 57389
const FINALLY = 57390
const FOR = 57391
const FROM = 57392
const GLOBAL = 57393
const IF = 57394
const IMPORT = 57395
const IN = 57396
const IS = 57397
const LAMBDA = 57398
const NONLOCAL = 57399
const NOT = 57400
const OR = 57401
const PASS = 57402
const RAISE = 57403
const RETURN = 57404
const TRY = 57405
const WHILE = 57406
const WITH = 57407
const YIELD = 57408
const SINGLE_INPUT = 57409
const FILE_INPUT = 57410
const EVAL_INPUT = 57411

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"NEWLINE",
	"ENDMARKER",
	"NAME",
	"INDENT",
	"DEDENT",
	"STRING",
	"NUMBER",
	"PLINGEQ",
	"PERCEQ",
	"ANDEQ",
	"STARSTAR",
	"STARSTAREQ",
	"STAREQ",
	"PLUSEQ",
	"MINUSEQ",
	"MINUSGT",
	"ELIPSIS",
	"DIVDIV",
	"DIVDIVEQ",
	"DIVEQ",
	"LTLT",
	"LTLTEQ",
	"LTEQ",
	"LTGT",
	"EQEQ",
	"GTEQ",
	"GTGT",
	"GTGTEQ",
	"HATEQ",
	"PIPEEQ",
	"FALSE",
	"NONE",
	"TRUE",
	"AND",
	"AS",
	"ASSERT",
	"BREAK",
	"CLASS",
	"CONTINUE",
	"DEF",
	"DEL",
	"ELIF",
	"ELSE",
	"EXCEPT",
	"FINALLY",
	"FOR",
	"FROM",
	"GLOBAL",
	"IF",
	"IMPORT",
	"IN",
	"IS",
	"LAMBDA",
	"NONLOCAL",
	"NOT",
	"OR",
	"PASS",
	"RAISE",
	"RETURN",
	"TRY",
	"WHILE",
	"WITH",
	"YIELD",
	"'('",
	"')'",
	"'['",
	"']'",
	"':'",
	"','",
	"';'",
	"'+'",
	"'-'",
	"'*'",
	"'/'",
	"'|'",
	"'&'",
	"'<'",
	"'>'",
	"'='",
	"'.'",
	"'%'",
	"'{'",
	"'}'",
	"'^'",
	"'~'",
	"'@'",
	"SINGLE_INPUT",
	"FILE_INPUT",
	"EVAL_INPUT",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line yacctab:1
var yyExca = [...]int16{
	-1, 1,
	1, -1,
	-2, 0,
	-1, 233,
	68, 13,
	-2, 302,
	-1, 389,
	68, 102,
	-2, 303,
}

const yyPrivate = 57344

const yyLast = 1417

var yyAct = [...]int16{
	59, 142, 317, 492, 166, 97, 61, 475, 365, 161,
	434, 165, 324, 409, 353, 346, 382, 261, 487, 101,
	102, 339, 338, 111, 35, 476, 224, 312, 69, 60,
	225, 211, 103, 6, 239, 146, 110, 105, 321, 71,
	54, 95, 72, 74, 66, 151, 70, 64, 138, 106,
	107, 75, 73, 97, 144, 57, 147, 17, 181, 97,
	290, 232, 2, 3, 4, 106, 107, 233, 24, 134,
	23, 140, 279, 245, 385, 249, 125, 126, 96, 131,
	123, 121, 122, 245, 205, 153, 132, 124, 190, 129,
	286, 327, 158, 49, 143, 130, 128, 127, 216, 264,
	155, 237, 182, 180, 84, 139, 223, 91, 85, 318,
	185, 186, 168, 149, 462, 392, 48, 429, 87, 97,
	245, 238, 196, 394, 212, 281, 99, 282, 191, 192,
	193, 510, 90, 88, 89, 120, 405, 197, 200, 228,
	227, 283, 318, 187, 188, 167, 133, 340, 152, 498,
	466, 189, 489, 164, 65, 253, 67, 217, 241, 235,
	236, 257, 207, 254, 260, 81, 349, 82, 262, 263,
	361, 486, 76, 77, 240, 198, 201, 391, 472, 428,
	427, 468, 398, 83, 167, 430, 78, 318, 406, 403,
	389, 167, 164, 377, 215, 381, 251, 246, 265, 345,
	287, 244, 286, 289, 256, 255, 292, 252, 337, 295,
	506, 318, 465, 360, 291, 163, 298, 336, 141, 315,
	259, 269, 97, 285, 293, 270, 288, 268, 111, 273,
	274, 294, 248, 243, 325, 242, 271, 272, 222, 275,
	276, 277, 278, 514, 329, 497, 299, 300, 332, 160,
	316, 106, 107, 479, 163, 306, 471, 380, 307, 342,
	302, 344, 241, 301, 305, 347, 411, 421, 420, 419,
	417, 343, 326, 413, 408, 386, 84, 374, 240, 91,
	85, 314, 325, 354, 333, 367, 319, 258, 220, 219,
	87, 108, 362, 404, 363, 388, 376, 359, 357, 284,
	233, 231, 156, 157, 90, 88, 89, 267, 341, 157,
	375, 412, 266, 221, 378, 106, 107, 383, 384, 358,
	350, 157, 286, 480, 390, 478, 495, 250, 67, 247,
	286, 348, 316, 415, 366, 212, 373, 81, 135, 82,
	397, 379, 400, 366, 76, 77, 387, 460, 399, 262,
	402, 393, 395, 229, 407, 83, 410, 159, 78, 309,
	396, 286, 401, 183, 478, 369, 371, 370, 318, 184,
	318, 157, 422, 416, 34, 208, 516, 304, 509, 15,
	14, 431, 318, 383, 433, 137, 435, 436, 167, 414,
	325, 318, 438, 439, 418, 440, 426, 432, 441, 500,
	114, 425, 437, 212, 423, 116, 117, 354, 481, 449,
	443, 340, 451, 330, 453, 445, 454, 444, 176, 452,
	442, 447, 448, 356, 450, 334, 140, 456, 331, 461,
	167, 383, 464, 174, 175, 172, 173, 328, 491, 297,
	296, 470, 318, 467, 455, 463, 457, 458, 459, 426,
	488, 473, 167, 136, 113, 112, 218, 98, 100, 214,
	446, 177, 179, 474, 213, 178, 483, 7, 383, 485,
	311, 490, 310, 230, 482, 162, 109, 303, 364, 335,
	145, 148, 484, 150, 445, 493, 320, 170, 171, 469,
	325, 501, 323, 322, 352, 499, 504, 351, 169, 25,
	505, 119, 502, 511, 512, 507, 496, 194, 204, 104,
	513, 477, 515, 493, 517, 206, 308, 368, 518, 519,
	203, 493, 234, 68, 508, 210, 209, 84, 494, 62,
	91, 85, 80, 280, 79, 313, 118, 16, 115, 13,
	12, 87, 11, 9, 10, 44, 43, 42, 41, 40,
	39, 38, 33, 32, 31, 90, 88, 89, 30, 29,
	47, 50, 24, 51, 23, 36, 28, 27, 26, 372,
	20, 56, 45, 18, 55, 8, 93, 65, 46, 67,
	94, 37, 53, 52, 21, 19, 22, 58, 81, 84,
	82, 424, 91, 85, 5, 76, 77, 63, 92, 1,
	86, 0, 0, 87, 0, 0, 83, 0, 0, 78,
	48, 0, 0, 0, 0, 0, 0, 90, 88, 89,
	0, 0, 47, 50, 24, 51, 23, 36, 0, 0,
	0, 0, 20, 56, 45, 18, 55, 0, 0, 65,
	46, 67, 0, 37, 53, 52, 21, 19, 22, 58,
	81, 84, 82, 0, 91, 85, 0, 76, 77, 63,
	0, 0, 0, 0, 0, 87, 0, 0, 83, 0,
	0, 78, 48, 0, 0, 0, 0, 0, 0, 90,
	88, 89, 0, 0, 47, 50, 24, 51, 23, 36,
	0, 0, 0, 0, 20, 56, 45, 18, 55, 0,
	0, 65, 46, 67, 0, 37, 53, 52, 21, 19,
	22, 58, 81, 0, 82, 0, 0, 0, 0, 76,
	77, 63, 226, 0, 84, 0, 0, 91, 85, 0,
	83, 0, 0, 78, 48, 0, 0, 0, 87, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 90, 88, 89, 0, 0, 47, 50, 0,
	51, 0, 36, 0, 0, 0, 0, 0, 56, 45,
	0, 55, 0, 0, 65, 46, 67, 0, 37, 53,
	52, 0, 0, 0, 58, 81, 84, 82, 0, 91,
	85, 0, 76, 77, 63, 0, 0, 0, 0, 0,
	87, 0, 0, 83, 0, 0, 78, 0, 0, 0,
	0, 0, 0, 0, 90, 88, 89, 0, 0, 47,
	50, 0, 51, 0, 36, 0, 0, 0, 0, 0,
	56, 45, 0, 55, 0, 0, 65, 46, 67, 0,
	37, 53, 52, 0, 0, 0, 58, 81, 84, 82,
	0, 91, 85, 0, 76, 77, 63, 0, 0, 0,
	0, 0, 87, 0, 0, 83, 0, 0, 78, 0,
	0, 0, 0, 0, 0, 0, 90, 88, 89, 0,
	0, 0, 0, 0, 0, 84, 0, 0, 91, 85,
	0, 0, 0, 0, 0, 0, 0, 0, 65, 87,
	67, 0, 0, 0, 0, 0, 0, 0, 58, 81,
	195, 82, 0, 90, 88, 89, 76, 77, 63, 0,
	0, 0, 84, 0, 0, 91, 85, 83, 0, 0,
	78, 0, 0, 0, 0, 65, 87, 67, 0, 0,
	0, 0, 0, 0, 0, 58, 81, 0, 82, 0,
	90, 88, 89, 76, 77, 63, 0, 0, 0, 0,
	0, 0, 0, 0, 83, 84, 0, 78, 91, 85,
	0, 0, 65, 503, 67, 0, 0, 0, 0, 87,
	0, 0, 0, 81, 0, 82, 199, 0, 0, 0,
	76, 77, 63, 90, 88, 89, 0, 0, 0, 0,
	0, 83, 84, 0, 78, 91, 85, 0, 0, 0,
	0, 0, 0, 0, 0, 65, 87, 67, 0, 0,
	0, 0, 0, 0, 0, 0, 81, 0, 82, 0,
	90, 88, 89, 76, 77, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 83, 84, 0, 78, 91, 85,
	0, 0, 65, 0, 67, 0, 0, 0, 0, 87,
	0, 0, 0, 81, 0, 82, 0, 411, 0, 0,
	76, 77, 0, 90, 88, 89, 0, 0, 0, 0,
	0, 83, 0, 0, 78, 0, 0, 84, 0, 0,
	91, 85, 0, 0, 0, 65, 0, 67, 0, 0,
	0, 87, 0, 0, 0, 0, 81, 0, 82, 0,
	355, 0, 0, 76, 77, 90, 88, 89, 0, 0,
	0, 0, 0, 0, 83, 0, 0, 78, 0, 0,
	84, 0, 0, 91, 85, 0, 0, 65, 0, 67,
	0, 0, 0, 0, 87, 0, 0, 0, 81, 0,
	82, 0, 0, 0, 0, 76, 77, 63, 90, 88,
	89, 0, 0, 0, 0, 0, 83, 84, 0, 78,
	91, 85, 0, 0, 0, 0, 0, 0, 0, 0,
	65, 87, 67, 0, 0, 0, 0, 0, 0, 0,
	58, 81, 0, 82, 0, 90, 88, 89, 76, 77,
	0, 0, 0, 0, 84, 0, 0, 91, 85, 83,
	0, 0, 78, 0, 0, 0, 0, 65, 87, 67,
	0, 0, 0, 0, 0, 0, 0, 0, 81, 0,
	82, 0, 90, 88, 89, 76, 77, 0, 0, 0,
	0, 84, 0, 0, 91, 85, 83, 202, 154, 78,
	0, 0, 0, 0, 65, 87, 67, 0, 0, 0,
	0, 0, 0, 0, 0, 81, 0, 82, 0, 90,
	88, 89, 76, 77, 0, 0, 0, 0, 84, 0,
	0, 91, 85, 83, 0, 0, 78, 0, 0, 0,
	0, 65, 87, 67, 0, 0, 0, 0, 0, 0,
	0, 0, 81, 0, 82, 0, 90, 88, 89, 76,
	77, 0, 0, 0, 84, 0, 0, 91, 85, 0,
	83, 0, 0, 78, 0, 0, 0, 0, 87, 0,
	67, 0, 0, 0, 84, 0, 0, 91, 85, 81,
	0, 82, 90, 88, 89, 0, 76, 77, 87, 0,
	0, 0, 0, 0, 0, 0, 0, 83, 0, 0,
	78, 0, 90, 88, 89, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 81, 0, 82, 0, 0,
	0, 0, 76, 77, 63, 0, 0, 0, 0, 0,
	0, 0, 0, 83, 0, 81, 78, 82, 0, 0,
	0, 0, 76, 77, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 83, 0, 0, 78,
}

var yyPact = [...]int16{
	-28, -32768, 645, -32768, 1235, -32768, -32768, 453, 53, -32768,
	-32768, -32768, -32768, -32768, -32768, -32768, -32768, -32768, 1235, 1235,
	1308, 220, 1235, 449, 448, 27, -32768, -32768, -32768, -32768,
	-32768, -32768, -32768, -32768, -32768, 64, 1308, -32768, -32768, -32768,
	-32768, -32768, -32768, -32768, -32768, 447, 447, 1235, 420, 146,
	-32768, -32768, 1235, 1235, -32768, 420, 65, -32768, 1198, -32768,
	-32768, 250, -32768, 1328, 320, 178, -32768, 1272, 407, 25,
	-29, 23, 339, 36, 67, -32768, 1328, 1328, 1328, -32768,
	-32768, 842, 916, 1161, -32768, -32768, 366, -32768, -32768, -32768,
	-32768, -32768, -32768, 521, -32768, -32768, 122, -32768, -32768, 780,
	452, 218, 217, 259, 166, -32768, 25, -32768, 718, 68,
	-32768, 315, 234, 233, -32768, -32768, -32768, -32768, 1124, 19,
	1235, -32768, -32768, -32768, -32768, -32768, -32768, -32768, -32768, -32768,
	-32768, -32768, -32768, 879, -32768, 163, -32768, 163, 161, 0,
	-32768, 1081, -32768, -32768, 279, 160, -32768, 37, 274, -10,
	65, -32768, -32768, -32768, 1235, -32768, 1272, 1272, 25, 1272,
	1235, 216, 148, 382, 382, -32768, 17, -32768, -32768, 1328,
	-32768, -32768, -32768, -32768, -32768, -32768, -32768, -32768, 258, 249,
	1328, 1328, 1328, 1328, 1328, 1328, 1328, 1328, 1328, 1328,
	1328, -32768, -32768, -32768, 58, -32768, 231, 281, 146, -32768,
	281, 146, -32768, -26, 142, 153, -32768, 122, -32768, -32768,
	-32768, -32768, -32768, -32768, 435, 1235, -32768, -32768, -32768, 718,
	718, 1235, 1308, -32768, -32768, -32768, 370, 1235, 718, 1328,
	340, 205, 215, 1235, -32768, -32768, -32768, 879, 9, -32768,
	-32768, -32768, 431, 1235, 409, 422, -32768, 1235, 420, 419,
	141, -32768, -10, -32768, 262, 320, -32768, -32768, 1235, 185,
	-32768, -32768, -32768, -32768, 1235, 25, -32768, -32768, -29, 23,
	339, 36, 36, 67, 67, -32768, -32768, -32768, -32768, 1328,
	-32768, 98, 1039, 417, -32768, 230, 1308, 229, 143, 100,
	-32768, 1235, -32768, 1235, -32768, -32768, -32768, -32768, -32768, -32768,
	297, 214, -32768, 319, 645, -32768, -32768, 25, 206, 1235,
	228, -32768, 121, 181, 376, 376, -32768, -8, 204, 718,
	227, -32768, 118, 101, -32768, 41, -32768, 1081, -32768, -32768,
	-32768, -32768, -32768, -32768, -32768, -32768, -32768, 405, 110, -32768,
	310, 1235, -32768, -32768, 382, 382, 117, -32768, -32768, -32768,
	225, 66, 116, -32768, 203, 996, -32768, -32768, 257, -32768,
	-32768, -32768, 202, 281, 288, -32768, 199, 718, 198, 197,
	196, 1235, 583, -32768, 718, -32768, -32768, 103, -32768, 113,
	376, 376, -32768, -32768, -32768, 1235, 1235, -32768, -32768, 1235,
	-32768, 1235, 1235, -32768, 1235, -32768, 110, -32768, 405, 404,
	-32768, -32768, -32768, 446, -32768, -32768, 1039, -32768, 996, -32768,
	195, 1235, 1272, 1235, -32768, 1235, -32768, 718, 297, 718,
	718, 718, 309, -32768, -32768, -32768, -32768, 42, 376, 376,
	136, -32768, -32768, -32768, 109, -32768, -32768, -32768, -32768, 42,
	-32768, 188, -32768, -32768, 106, -32768, 382, -32768, -32768, 195,
	-32768, -32768, 312, -32768, 182, -32768, -32768, -32768, 275, -32768,
	402, -32768, -32768, -32768, 42, 376, 376, 99, 436, 80,
	-32768, -32768, 424, -32768, -32768, -32768, -32768, -32768, 270, 718,
	174, -32768, 77, -32768, -32768, -32768, 385, -32768, 376, 959,
	-32768, 382, 273, 244, -32768, 139, -32768, 718, 364, 59,
	376, -32768, -32768, 1235, -32768, -32768, 270, 172, -32768, 376,
	362, -32768, 42, -32768, 270, -32768, 376, -32768, -32768, -32768,
}

var yyPgo = [...]int16{
	0, 600, 599, 598, 594, 580, 30, 31, 576, 575,
	569, 26, 8, 464, 57, 568, 567, 566, 559, 558,
	554, 553, 552, 551, 550, 549, 548, 547, 546, 545,
	544, 543, 542, 540, 539, 380, 379, 538, 537, 536,
	535, 37, 28, 29, 46, 39, 42, 52, 43, 51,
	534, 533, 532, 55, 0, 44, 529, 3, 528, 6,
	47, 523, 41, 24, 522, 40, 34, 520, 13, 517,
	516, 374, 32, 515, 511, 7, 509, 93, 78, 508,
	507, 501, 499, 498, 1, 25, 14, 497, 494, 12,
	493, 492, 489, 38, 61, 486, 45, 483, 56, 481,
	338, 35, 21, 480, 22, 479, 478, 477, 36, 476,
	11, 4, 17, 18, 2, 16, 15, 475, 10, 27,
	9, 473, 472, 470, 459, 458,
}

var yyR1 = [...]int8{
	0, 2, 2, 2, 4, 4, 3, 8, 8, 8,
	5, 124, 124, 95, 95, 94, 94, 71, 82, 82,
	37, 37, 38, 70, 70, 35, 121, 122, 122, 113,
	113, 118, 118, 119, 119, 115, 115, 40, 123, 123,
	123, 123, 123, 123, 123, 123, 123, 123, 123, 123,
	123, 123, 123, 114, 114, 110, 110, 116, 116, 117,
	117, 112, 112, 120, 120, 120, 120, 120, 120, 120,
	111, 7, 7, 125, 125, 9, 9, 6, 14, 14,
	14, 14, 14, 14, 14, 14, 15, 15, 15, 15,
	15, 64, 64, 66, 66, 81, 81, 77, 77, 53,
	53, 84, 84, 63, 39, 39, 39, 39, 39, 39,
	39, 39, 39, 39, 39, 39, 16, 17, 18, 18,
	18, 18, 18, 23, 24, 25, 25, 27, 26, 26,
	26, 19, 19, 28, 96, 96, 97, 97, 99, 99,
	99, 105, 105, 105, 29, 102, 102, 101, 101, 104,
	104, 103, 103, 98, 98, 100, 100, 20, 21, 78,
	78, 22, 22, 13, 13, 13, 13, 13, 13, 13,
	13, 106, 106, 12, 12, 31, 30, 32, 107, 107,
	33, 33, 33, 33, 109, 109, 34, 108, 108, 69,
	69, 69, 10, 10, 11, 11, 54, 54, 54, 57,
	57, 56, 56, 58, 58, 59, 59, 60, 60, 55,
	55, 61, 61, 83, 83, 83, 83, 83, 83, 83,
	83, 83, 83, 83, 43, 42, 42, 44, 44, 45,
	45, 46, 46, 46, 47, 47, 47, 48, 48, 48,
	48, 48, 49, 49, 49, 49, 50, 50, 80, 80,
	1, 1, 52, 52, 52, 52, 52, 52, 52, 52,
	52, 52, 52, 52, 52, 52, 52, 52, 51, 51,
	51, 51, 88, 88, 87, 86, 86, 86, 86, 86,
	86, 86, 86, 86, 68, 68, 41, 41, 76, 76,
	72, 62, 73, 79, 79, 67, 67, 67, 67, 36,
	90, 90, 91, 91, 92, 92, 93, 93, 93, 93,
	89, 89, 89, 75, 75, 85, 85, 74, 74, 65,
	65, 65,
}

var yyR2 = [...]int8{
	0, 2, 2, 2, 1, 2, 2, 0, 2, 2,
	3, 0, 2, 0, 1, 0, 3, 4, 1, 2,
	1, 1, 2, 0, 2, 6, 3, 0, 1, 1,
	3, 0, 3, 1, 3, 0, 1, 4, 2, 1,
	3, 6, 9, 5, 4, 7, 3, 5, 8, 5,
	3, 6, 2, 1, 3, 1, 3, 0, 3, 1,
	3, 0, 1, 2, 5, 8, 4, 3, 6, 2,
	1, 1, 1, 0, 1, 1, 3, 3, 1, 1,
	1, 1, 1, 1, 1, 1, 3, 2, 1, 3,
	5, 1, 1, 1, 1, 2, 3, 1, 3, 1,
	1, 0, 1, 2, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 2, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 2, 1, 1, 2,
	4, 1, 1, 2, 1, 1, 1, 2, 1, 2,
	1, 1, 4, 2, 4, 1, 3, 1, 3, 1,
	3, 1, 3, 1, 3, 1, 3, 2, 2, 1,
	3, 2, 4, 1, 1, 1, 1, 1, 1, 1,
	1, 0, 5, 0, 3, 6, 5, 7, 0, 4,
	4, 7, 7, 10, 1, 3, 4, 1, 3, 1,
	2, 4, 1, 2, 1, 4, 1, 5, 1, 1,
	1, 3, 4, 3, 4, 1, 3, 1, 3, 2,
	1, 1, 3, 1, 1, 1, 1, 1, 1, 1,
	1, 2, 1, 2, 2, 1, 3, 1, 3, 1,
	3, 1, 3, 3, 1, 3, 3, 1, 3, 3,
	3, 3, 2, 2, 2, 1, 2, 4, 0, 2,
	1, 2, 2, 3, 4, 4, 2, 4, 4, 2,
	3, 1, 1, 1, 1, 1, 1, 1, 2, 3,
	3, 2, 1, 3, 2, 1, 1, 2, 2, 3,
	2, 3, 3, 4, 1, 2, 1, 1, 1, 3,
	2, 2, 2, 3, 5, 2, 4, 1, 2, 5,
	1, 3, 0, 2, 0, 3, 2, 5, 8, 4,
	1, 2, 3, 1, 1, 4, 5, 2, 3, 1,
	3, 2,
}

var yyChk = [...]int16{
	-32768, -2, 90, 91, 92, -4, -6, -13, -9, -31,
	-30, -32, -33, -34, -35, -36, -38, -14, 52, 64,
	49, 63, 65, 43, 41, -82, -15, -16, -17, -18,
	-19, -20, -21, -22, -71, -63, 44, 60, -23, -24,
	-25, -26, -27, -28, -29, 51, 57, 39, 89, -77,
	40, 42, 62, 61, -65, 53, 50, -53, 66, -54,
	-43, -59, -56, 76, -60, 56, -55, 58, -61, -42,
	-44, -45, -46, -47, -48, -49, 74, 75, 88, -50,
	-52, 67, 69, 85, 6, 10, -1, 20, 35, 36,
	34, 9, -3, -8, -5, -62, -78, -54, 4, 73,
	-125, -54, -54, -72, -76, -41, -42, -43, 71, -109,
	-108, -54, 6, 6, -71, -37, -36, -35, -39, -81,
	71, 17, 18, 16, 23, 12, 13, 33, 32, 25,
	31, 15, 22, 82, -72, -100, 6, -100, -54, -98,
	6, 72, -84, -62, -54, -103, -101, -98, -99, -98,
	-97, -96, 83, 20, 50, -62, 52, 59, -42, 37,
	71, -120, -117, 76, 14, -110, -111, 6, -55, -83,
	80, 81, 28, 29, 26, 27, 11, 54, 58, 55,
	78, 87, 79, 24, 30, 74, 75, 76, 77, 84,
	21, -49, -49, -49, -80, 68, -65, -53, -77, 70,
	-53, -77, 86, -67, -79, -54, -73, -78, 9, 5,
	4, -7, -6, -13, -124, 72, -84, -14, 4, 71,
	71, 54, 72, -84, -11, -6, 4, 72, 71, 38,
	-121, 67, -94, 67, -64, -65, -62, 82, -54, -66,
	-65, -63, 72, 72, -94, 83, -53, 50, 72, 38,
	53, -96, -98, -54, -59, -60, -55, -54, 71, 72,
	-84, -112, -111, -111, 82, -42, 54, 58, -44, -45,
	-46, -47, -47, -48, -48, -49, -49, -49, -49, 14,
	-51, 67, 69, 83, 68, -85, 49, -84, -85, -84,
	86, 72, -84, 71, -85, -84, 5, 4, -54, -11,
	-11, -62, -41, -107, 7, -108, -11, -42, -70, 19,
	-122, -123, -119, -40, 76, 14, -113, -114, 6, 71,
	-95, -93, -90, -91, -89, -54, -66, 82, 6, -54,
	4, 6, -54, -101, 6, -105, 76, 67, -104, -102,
	6, 46, -54, -110, 76, 14, -116, -54, -49, 68,
	-93, -87, -88, -86, -54, 71, 6, 68, -72, 68,
	70, 70, -54, -54, -106, -12, 46, 71, -69, 46,
	48, 47, -10, -7, 71, -54, 68, 72, -84, -119,
	76, 14, -115, -114, -114, 82, 71, -11, 68, 72,
	-84, 76, 14, -85, 82, -63, -104, -84, 72, 38,
	-54, -112, -111, 72, 68, 70, 72, -84, 71, -68,
	-54, 71, 54, 71, -85, 45, -12, 71, -11, 71,
	71, 71, -54, -7, 8, -11, -113, 77, 76, 14,
	72, -84, -115, -114, -118, -54, -54, -89, -54, -54,
	-54, -84, -102, 6, -116, -110, 14, -86, -68, -54,
	-68, -54, -59, -54, -54, -11, -12, -11, -11, -11,
	38, -84, 72, -115, -114, 76, 14, -118, 72, -92,
	-84, 68, 72, -111, -68, -75, -85, -74, 52, 71,
	48, 6, -118, -84, -115, -114, 72, -113, 14, 72,
	-84, 14, -57, -59, -58, 56, -11, 71, 72, -118,
	14, -114, -89, 14, -111, -75, 71, -120, -11, 14,
	72, -114, -54, -57, 71, -114, 14, -84, -57, -114,
}

var yyDef = [...]int16{
	0, -2, 0, 7, 0, 1, 4, 0, 73, 163,
	164, 165, 166, 167, 168, 169, 170, 75, 0, 0,
	0, 0, 0, 0, 0, 0, 78, 79, 80, 81,
	82, 83, 84, 85, 18, 88, 0, 117, 118, 119,
	120, 121, 122, 131, 132, 0, 0, 0, 0, 101,
	123, 124, 125, 128, 127, 0, 0, 97, 319, 99,
	100, 196, 198, 0, 205, 0, 207, 0, 210, 211,
	225, 227, 229, 231, 234, 237, 0, 0, 0, 245,
	248, 0, 0, 0, 261, 262, 263, 264, 265, 266,
	267, 250, 2, 0, 3, 11, 101, 159, 5, 74,
	0, 0, 0, 0, 101, 288, 286, 287, 0, 0,
	184, 187, 0, 15, 19, 22, 20, 21, 0, 87,
	0, 104, 105, 106, 107, 108, 109, 110, 111, 112,
	113, 114, 115, 0, 116, 157, 155, 158, 161, 15,
	153, 102, 103, 126, 129, 133, 151, 147, 0, 138,
	140, 136, 134, 135, 0, 321, 0, 0, 224, 0,
	0, 0, 101, 61, 0, 59, 55, 70, 209, 0,
	213, 214, 215, 216, 217, 218, 219, 220, 0, 222,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 242, 243, 244, 246, 252, 0, 97, 101, 256,
	97, 101, 259, 0, 101, 159, 297, 101, 251, 6,
	8, 9, 71, 72, 0, 102, 291, 76, 77, 0,
	0, 0, 102, 290, 178, 194, 0, 0, 0, 0,
	23, 27, 0, -2, 86, 91, 92, 0, 89, 95,
	93, 94, 0, 0, 0, 0, 98, 0, 0, 0,
	0, 137, 139, 320, 0, 206, 208, 201, 0, 102,
	63, 57, 62, 69, 0, 212, 221, 223, 226, 228,
	230, 232, 233, 235, 236, 238, 239, 240, 241, 0,
	249, 302, 0, 0, 253, 0, 0, 0, 0, 0,
	260, 102, 295, 0, 298, 292, 10, 12, 160, 171,
	173, 0, 289, 180, 0, 185, 186, 188, 0, 0,
	0, 28, 101, 39, 35, 0, 33, 29, 53, 0,
	0, 14, 101, 0, 300, 310, 96, 0, 156, 162,
	17, 154, 130, 152, 148, 144, 141, 0, 101, 149,
	145, 0, 202, 60, 61, 0, 67, 56, 247, 268,
	0, 0, 101, 272, 275, 276, 271, 254, 0, 255,
	257, 258, 0, 293, 173, 176, 0, 0, 0, 0,
	0, 189, 0, 192, 0, 24, 26, 102, 38, 101,
	35, 0, 31, 36, 52, 0, 0, 299, 16, -2,
	306, 0, 0, 311, 0, 90, 101, 143, 102, 0,
	197, 57, 66, 0, 269, 270, 102, 274, 280, 277,
	278, 284, 0, 0, 296, 0, 175, 0, 173, 0,
	0, 0, 190, 193, 195, 25, 34, 101, 35, 0,
	102, 40, 31, 46, 50, 30, 54, 301, 304, 101,
	312, 0, 150, 146, 64, 58, 0, 273, 281, 282,
	279, 285, 315, 294, 0, 174, 177, 179, 181, 182,
	0, 37, 102, 31, 101, 35, 0, 44, 0, 101,
	309, 142, 0, 68, 283, 316, 313, 314, 0, 0,
	0, 191, 47, 49, 31, 43, 0, 32, 0, 102,
	307, 0, 317, 199, 200, 0, 172, 0, 0, 41,
	0, 51, 305, 0, 65, 318, 0, 0, 183, 0,
	0, 45, 101, 203, 0, 48, 0, 308, 204, 42,
}

var yyTok1 = [...]int8{
	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 84, 79, 3,
	67, 68, 76, 74, 72, 75, 83, 77, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 71, 73,
	80, 82, 81, 3, 89, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 69, 3, 70, 87, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 85, 78, 86, 88,
}

var yyTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
	42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
	52, 53, 54, 55, 56, 57, 58, 59, 60, 61,
	62, 63, 64, 65, 66, 90, 91, 92,
}

var yyTok3 = [...]int8{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -32768

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(yyPact[state])
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && int(yyChk[int(yyAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || int(yyExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := int(yyExca[i])
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(yyTok1[0])
		goto out
	}
	if char < len(yyTok1) {
		token = int(yyTok1[char])
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = int(yyTok2[char-yyPrivate])
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = int(yyTok3[i+0])
		if token == char {
			token = int(yyTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(yyTok2[1]) /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = int(yyPact[yystate])
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = int(yyAct[yyn])
	if int(yyChk[yyn]) == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = int(yyDef[yystate])
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && int(yyExca[xi+1]) == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = int(yyExca[xi+0])
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = int(yyExca[xi+1])
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = int(yyPact[yyS[yyp].yys]) + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = int(yyAct[yyn]) /* simulate a shift of "error" */
					if int(yyChk[yystate]) == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= int(yyR2[yyn])
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = int(yyR1[yyn])
	yyg := int(yyPgo[yyn])
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = int(yyAct[yyg])
	} else {
		yystate = int(yyAct[yyj])
		if int(yyChk[yystate]) != -yyn {
			yystate = int(yyAct[yyg])
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/grammar.y:261
		{
			yylex.(*yyLex).mod = yyDollar[2].mod
			return 0
		}
	case 2:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/grammar.y:266
		{
			yylex.(*yyLex).mod = yyDollar[2].mod
			return 0
		}
	case 3:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/grammar.y:271
		{
			yylex.(*yyLex).mod = yyDollar[2].mod
			return 0
		}
	case 4:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:285
		{
			yyVAL.mod = &ast.Interactive{ModBase: ast.ModBase{Pos: yyVAL.pos}, Body: yyDollar[1].stmts}
		}
	case 5:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/grammar.y:289
		{
			//  NB: compound_stmt in single_input is followed by extra NEWLINE!
			yyVAL.mod = &ast.Interactive{ModBase: ast.ModBase{Pos: yyVAL.pos}, Body: []ast.Stmt{yyDollar[1].stmt}}
		}
	case 6:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/grammar.y:297
		{
			yyVAL.mod = &ast.Module{ModBase: ast.ModBase{Pos: yyVAL.pos}, Body: yyDollar[1].stmts}
		}
	case 7:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser/grammar.y:303
		{
			yyVAL.stmts = nil
		}
	case 8:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/grammar.y:307
		{
		}
	case 9:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/grammar.y:310
		{
			yyVAL.stmts = append(yyVAL.stmts, yyDollar[2].stmts...)
		}
	case 10:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/grammar.y:317
		{
			yyVAL.mod = &ast.Expression{ModBase: ast.ModBase{Pos: yyVAL.pos}, Body: yyDollar[1].expr}
		}
	case 13:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser/grammar.y:326
		{
			yyVAL.call = &ast.Call{ExprBase: ast.ExprBase{Pos: yyVAL.pos}}
		}
	case 14:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:330
		{
			yyVAL.call = yyDollar[1].call
		}
	case 15:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser/grammar.y:335
		{
			yyVAL.call = nil
		}
	case 16:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/grammar.y:339
		{
			yyVAL.call = yyDollar[2].call
		}
	case 17:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/grammar.y:345
		{
			fn := &ast.Name{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, Id: ast.Identifier(yyDollar[2].str), Ctx: ast.Load}
			if yyDollar[3].call == nil {
				yyVAL.expr = fn
			} else {
				call := *yyDollar[3].call
				call.Func = fn
				yyVAL.expr = &call
			}
		}
	case 18:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:358
		{
			yyVAL.exprs = nil
			yyVAL.exprs = append(yyVAL.exprs, yyDollar[1].expr)
		}
	case 19:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/grammar.y:363
		{
			yyVAL.exprs = append(yyVAL.exprs, yyDollar[2].expr)
		}
	case 20:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:369
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 21:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:373
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 22:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/grammar.y:379
		{
			switch x := (yyDollar[2].stmt).(type) {
			case *ast.ClassDef:
				x.DecoratorList = yyDollar[1].exprs
				yyVAL.stmt = x
			case *ast.FunctionDef:
				x.DecoratorList = yyDollar[1].exprs
				yyVAL.stmt = x
			default:
				panic("bad type for decorated")
			}
		}
	case 23:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser/grammar.y:393
		{
			yyVAL.expr = nil
		}
	case 24:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/grammar.y:397
		{
			yyVAL.expr = yyDollar[2].expr
		}
	case 25:
		yyDollar = yyS[yypt-6 : yypt+1]
//line parser/grammar.y:403
		{
			yyVAL.stmt = &ast.FunctionDef{StmtBase: ast.StmtBase{Pos: yyVAL.pos}, Name: ast.Identifier(yyDollar[2].str), Args: yyDollar[3].arguments, Body: yyDollar[6].stmts, Returns: yyDollar[4].expr}
		}
	case 26:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/grammar.y:409
		{
			yyVAL.arguments = yyDollar[2].arguments
		}
	case 27:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser/grammar.y:414
		{
			yyVAL.arguments = &ast.Arguments{Pos: yyVAL.pos}
		}
	case 28:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:418
		{
			yyVAL.arguments = yyDollar[1].arguments
		}
	case 29:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:425
		{
			yyVAL.arg = yyDollar[1].arg
			yyVAL.expr = nil
		}
	case 30:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/grammar.y:430
		{
			yyVAL.arg = yyDollar[1].arg
			yyVAL.expr = yyDollar[3].expr
		}
	case 31:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser/grammar.y:436
		{
			yyVAL.args = nil
			yyVAL.exprs = nil
		}
	case 32:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/grammar.y:441
		{
			yyVAL.args = append(yyVAL.args, yyDollar[3].arg)
			if yyDollar[3].expr != nil {
				yyVAL.exprs = append(yyVAL.exprs, yyDollar[3].expr)
			}
		}
	case 33:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:450
		{
			yyVAL.args = nil
			yyVAL.args = append(yyVAL.args, yyDollar[1].arg)
			yyVAL.exprs = nil
			if yyDollar[1].expr != nil {
				yyVAL.exprs = append(yyVAL.exprs, yyDollar[1].expr)
			}
		}
	case 34:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/grammar.y:459
		{
			yyVAL.args = append(yyVAL.args, yyDollar[3].arg)
			if yyDollar[3].expr != nil {
				yyVAL.exprs = append(yyVAL.exprs, yyDollar[3].expr)
			}
		}
	case 35:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser/grammar.y:467
		{
			yyVAL.arg = nil
		}
	case 36:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:471
		{
			yyVAL.arg = yyDollar[1].arg
		}
	case 37:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/grammar.y:481
		{
			yyVAL.posonly = posonlyArgs{args: yyDollar[1].args, defaults: yyDollar[1].exprs}
		}
	case 38:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/grammar.y:488
		{
			yyVAL.arguments = &ast.Arguments{Pos: yyVAL.pos, Args: yyDollar[1].args, Defaults: yyDollar[1].exprs}
		}
	case 39:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:492
		{
			yyVAL.arguments = &ast.Arguments{Pos: yyVAL.pos, Args: yyDollar[1].posonly.args, Defaults: yyDollar[1].posonly.defaults, Posonlyargs: yyDollar[1].posonly.args}
		}
	case 40:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/grammar.y:496
		{
			po := yyDollar[1].posonly
			args := append(append([]*ast.Arg{}, po.args...), yyDollar[2].args...)
			defaults := append(append([]ast.Expr{}, po.defaults...), yyDollar[2].exprs...)
			yyVAL.arguments = &ast.Arguments{Pos: yyVAL.pos, Args: args, Defaults: defaults, Posonlyargs: po.args}
		}
	case 41:
		yyDollar = yyS[yypt-6 : yypt+1]
//line parser/grammar.y:503
		{
			po := yyDollar[1].posonly
			args := append(append([]*ast.Arg{}, po.args...), yyDollar[2].args...)
			defaults := append(append([]ast.Expr{}, po.defaults...), yyDollar[2].exprs...)
			yyVAL.arguments = &ast.Arguments{Pos: yyVAL.pos, Args: args, Defaults: defaults, Posonlyargs: po.args, Vararg: yyDollar[5].arg, Kwonlyargs: yyDollar[6].args, KwDefaults: yyDollar[6].exprs}
		}
	case 42:
		yyDollar = yyS[yypt-9 : yypt+1]
//line parser/grammar.y:510
		{
			po := yyDollar[1].posonly
			args := append(append([]*ast.Arg{}, po.args...), yyDollar[2].args...)
			defaults := append(append([]ast.Expr{}, po.defaults...), yyDollar[2].exprs...)
			yyVAL.arguments = &ast.Arguments{Pos: yyVAL.pos, Args: args, Defaults: defaults, Posonlyargs: po.args, Vararg: yyDollar[5].arg, Kwonlyargs: yyDollar[6].args, KwDefaults: yyDollar[6].exprs, Kwarg: yyDollar[9].arg}
		}
	case 43:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser/grammar.y:517
		{
			po := yyDollar[1].posonly
			args := append(append([]*ast.Arg{}, po.args...), yyDollar[2].args...)
			defaults := append(append([]ast.Expr{}, po.defaults...), yyDollar[2].exprs...)
			yyVAL.arguments = &ast.Arguments{Pos: yyVAL.pos, Args: args, Defaults: defaults, Posonlyargs: po.args, Kwarg: yyDollar[5].arg}
		}
	case 44:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/grammar.y:524
		{
			po := yyDollar[1].posonly
			yyVAL.arguments = &ast.Arguments{Pos: yyVAL.pos, Args: po.args, Defaults: po.defaults, Posonlyargs: po.args, Vararg: yyDollar[3].arg, Kwonlyargs: yyDollar[4].args, KwDefaults: yyDollar[4].exprs}
		}
	case 45:
		yyDollar = yyS[yypt-7 : yypt+1]
//line parser/grammar.y:529
		{
			po := yyDollar[1].posonly
			yyVAL.arguments = &ast.Arguments{Pos: yyVAL.pos, Args: po.args, Defaults: po.defaults, Posonlyargs: po.args, Vararg: yyDollar[3].arg, Kwonlyargs: yyDollar[4].args, KwDefaults: yyDollar[4].exprs, Kwarg: yyDollar[7].arg}
		}
	case 46:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/grammar.y:534
		{
			po := yyDollar[1].posonly
			yyVAL.arguments = &ast.Arguments{Pos: yyVAL.pos, Args: po.args, Defaults: po.defaults, Posonlyargs: po.args, Kwarg: yyDollar[3].arg}
		}
	case 47:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser/grammar.y:539
		{
			yyVAL.arguments = &ast.Arguments{Pos: yyVAL.pos, Args: yyDollar[1].args, Defaults: yyDollar[1].exprs, Vararg: yyDollar[4].arg, Kwonlyargs: yyDollar[5].args, KwDefaults: yyDollar[5].exprs}
		}
	case 48:
		yyDollar = yyS[yypt-8 : yypt+1]
//line parser/grammar.y:543
		{
			yyVAL.arguments = &ast.Arguments{Pos: yyVAL.pos, Args: yyDollar[1].args, Defaults: yyDollar[1].exprs, Vararg: yyDollar[4].arg, Kwonlyargs: yyDollar[5].args, KwDefaults: yyDollar[5].exprs, Kwarg: yyDollar[8].arg}
		}
	case 49:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser/grammar.y:547
		{
			yyVAL.arguments = &ast.Arguments{Pos: yyVAL.pos, Args: yyDollar[1].args, Defaults: yyDollar[1].exprs, Kwarg: yyDollar[4].arg}
		}
	case 50:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/grammar.y:551
		{
			yyVAL.arguments = &ast.Arguments{Pos: yyVAL.pos, Vararg: yyDollar[2].arg, Kwonlyargs: yyDollar[3].args, KwDefaults: yyDollar[3].exprs}
		}
	case 51:
		yyDollar = yyS[yypt-6 : yypt+1]
//line parser/grammar.y:555
		{
			yyVAL.arguments = &ast.Arguments{Pos: yyVAL.pos, Vararg: yyDollar[2].arg, Kwonlyargs: yyDollar[3].args, KwDefaults: yyDollar[3].exprs, Kwarg: yyDollar[6].arg}
		}
	case 52:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/grammar.y:559
		{
			yyVAL.arguments = &ast.Arguments{Pos: yyVAL.pos, Kwarg: yyDollar[2].arg}
		}
	case 53:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:565
		{
			yyVAL.arg = &ast.Arg{Pos: yyVAL.pos, Arg: ast.Identifier(yyDollar[1].str)}
		}
	case 54:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/grammar.y:569
		{
			yyVAL.arg = &ast.Arg{Pos: yyVAL.pos, Arg: ast.Identifier(yyDollar[1].str), Annotation: yyDollar[3].expr}
		}
	case 55:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:575
		{
			yyVAL.arg = yyDollar[1].arg
			yyVAL.expr = nil
		}
	case 56:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/grammar.y:580
		{
			yyVAL.arg = yyDollar[1].arg
			yyVAL.expr = yyDollar[3].expr
		}
	case 57:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser/grammar.y:586
		{
			yyVAL.args = nil
			yyVAL.exprs = nil
		}
	case 58:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/grammar.y:591
		{
			yyVAL.args = append(yyVAL.args, yyDollar[3].arg)
			if yyDollar[3].expr != nil {
				yyVAL.exprs = append(yyVAL.exprs, yyDollar[3].expr)
			}
		}
	case 59:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:600
		{
			yyVAL.args = nil
			yyVAL.args = append(yyVAL.args, yyDollar[1].arg)
			yyVAL.exprs = nil
			if yyDollar[1].expr != nil {
				yyVAL.exprs = append(yyVAL.exprs, yyDollar[1].expr)
			}
		}
	case 60:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/grammar.y:609
		{
			yyVAL.args = append(yyVAL.args, yyDollar[3].arg)
			if yyDollar[3].expr != nil {
				yyVAL.exprs = append(yyVAL.exprs, yyDollar[3].expr)
			}
		}
	case 61:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser/grammar.y:617
		{
			yyVAL.arg = nil
		}
	case 62:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:621
		{
			yyVAL.arg = yyDollar[1].arg
		}
	case 63:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/grammar.y:628
		{
			yyVAL.arguments = &ast.Arguments{Pos: yyVAL.pos, Args: yyDollar[1].args, Defaults: yyDollar[1].exprs}
		}
	case 64:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser/grammar.y:632
		{
			yyVAL.arguments = &ast.Arguments{Pos: yyVAL.pos, Args: yyDollar[1].args, Defaults: yyDollar[1].exprs, Vararg: yyDollar[4].arg, Kwonlyargs: yyDollar[5].args, KwDefaults: yyDollar[5].exprs}
		}
	case 65:
		yyDollar = yyS[yypt-8 : yypt+1]
//line parser/grammar.y:636
		{
			yyVAL.arguments = &ast.Arguments{Pos: yyVAL.pos, Args: yyDollar[1].args, Defaults: yyDollar[1].exprs, Vararg: yyDollar[4].arg, Kwonlyargs: yyDollar[5].args, KwDefaults: yyDollar[5].exprs, Kwarg: yyDollar[8].arg}
		}
	case 66:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/grammar.y:640
		{
			yyVAL.arguments = &ast.Arguments{Pos: yyVAL.pos, Args: yyDollar[1].args, Defaults: yyDollar[1].exprs, Kwarg: yyDollar[4].arg}
		}
	case 67:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/grammar.y:644
		{
			yyVAL.arguments = &ast.Arguments{Pos: yyVAL.pos, Vararg: yyDollar[2].arg, Kwonlyargs: yyDollar[3].args, KwDefaults: yyDollar[3].exprs}
		}
	case 68:
		yyDollar = yyS[yypt-6 : yypt+1]
//line parser/grammar.y:648
		{
			yyVAL.arguments = &ast.Arguments{Pos: yyVAL.pos, Vararg: yyDollar[2].arg, Kwonlyargs: yyDollar[3].args, KwDefaults: yyDollar[3].exprs, Kwarg: yyDollar[6].arg}
		}
	case 69:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/grammar.y:652
		{
			yyVAL.arguments = &ast.Arguments{Pos: yyVAL.pos, Kwarg: yyDollar[2].arg}
		}
	case 70:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:658
		{
			yyVAL.arg = &ast.Arg{Pos: yyVAL.pos, Arg: ast.Identifier(yyDollar[1].str)}
		}
	case 71:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:664
		{
			yyVAL.stmts = yyDollar[1].stmts
		}
	case 72:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:668
		{
			yyVAL.stmts = []ast.Stmt{yyDollar[1].stmt}
		}
	case 75:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:676
		{
			yyVAL.stmts = nil
			yyVAL.stmts = append(yyVAL.stmts, yyDollar[1].stmt)
		}
	case 76:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/grammar.y:681
		{
			yyVAL.stmts = append(yyVAL.stmts, yyDollar[3].stmt)
		}
	case 77:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/grammar.y:687
		{
			yyVAL.stmts = yyDollar[1].stmts
		}
	case 78:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:693
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 79:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:697
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 80:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:701
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 81:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:705
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 82:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:709
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 83:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:713
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 84:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:717
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 85:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:721
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 86:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/grammar.y:748
		{
			target := yyDollar[1].expr
			setCtx(yylex, target, ast.Store)
			yyVAL.stmt = &ast.AugAssign{StmtBase: ast.StmtBase{Pos: yyVAL.pos}, Target: target, Op: yyDollar[2].op, Value: yyDollar[3].expr}
		}
	case 87:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/grammar.y:754
		{
			targets := []ast.Expr{yyDollar[1].expr}
			targets = append(targets, yyDollar[2].exprs...)
			value := targets[len(targets)-1]
			targets = targets[:len(targets)-1]
			setCtxs(yylex, targets, ast.Store)
			yyVAL.stmt = &ast.Assign{StmtBase: ast.StmtBase{Pos: yyVAL.pos}, Targets: targets, Value: value}
		}
	case 88:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:763
		{
			yyVAL.stmt = &ast.ExprStmt{StmtBase: ast.StmtBase{Pos: yyVAL.pos}, Value: yyDollar[1].expr}
		}
	case 89:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/grammar.y:767
		{
			setCtx(yylex, yyDollar[1].expr, ast.Store)
			yyVAL.stmt = &ast.AnnAssign{StmtBase: ast.StmtBase{Pos: yyVAL.pos}, Target: yyDollar[1].expr, Annotation: yyDollar[3].expr}
		}
	case 90:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser/grammar.y:772
		{
			setCtx(yylex, yyDollar[1].expr, ast.Store)
			yyVAL.stmt = &ast.AnnAssign{StmtBase: ast.StmtBase{Pos: yyVAL.pos}, Target: yyDollar[1].expr, Annotation: yyDollar[3].expr, Value: yyDollar[5].expr}
		}
	case 91:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:779
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 92:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:783
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 93:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:789
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 94:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:793
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 95:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/grammar.y:799
		{
			yyVAL.exprs = nil
			yyVAL.exprs = append(yyVAL.exprs, yyDollar[2].expr)
		}
	case 96:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/grammar.y:804
		{
			yyVAL.exprs = append(yyVAL.exprs, yyDollar[3].expr)
		}
	case 97:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:810
		{
			yyVAL.exprs = nil
			yyVAL.exprs = append(yyVAL.exprs, yyDollar[1].expr)
		}
	case 98:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/grammar.y:815
		{
			yyVAL.exprs = append(yyVAL.exprs, yyDollar[3].expr)
		}
	case 99:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:821
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 100:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:825
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 101:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser/grammar.y:830
		{
			yyVAL.comma = false
		}
	case 102:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:834
		{
			yyVAL.comma = true
		}
	case 103:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/grammar.y:840
		{
			yyVAL.expr = tupleOrExpr(yyVAL.pos, yyDollar[1].exprs, yyDollar[2].comma)
		}
	case 104:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:846
		{
			yyVAL.op = ast.Add
		}
	case 105:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:850
		{
			yyVAL.op = ast.Sub
		}
	case 106:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:854
		{
			yyVAL.op = ast.Mult
		}
	case 107:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:858
		{
			yyVAL.op = ast.Div
		}
	case 108:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:862
		{
			yyVAL.op = ast.Modulo
		}
	case 109:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:866
		{
			yyVAL.op = ast.BitAnd
		}
	case 110:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:870
		{
			yyVAL.op = ast.BitOr
		}
	case 111:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:874
		{
			yyVAL.op = ast.BitXor
		}
	case 112:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:878
		{
			yyVAL.op = ast.LShift
		}
	case 113:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:882
		{
			yyVAL.op = ast.RShift
		}
	case 114:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:886
		{
			yyVAL.op = ast.Pow
		}
	case 115:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:890
		{
			yyVAL.op = ast.FloorDiv
		}
	case 116:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/grammar.y:897
		{
			setCtxs(yylex, yyDollar[2].exprs, ast.Del)
			yyVAL.stmt = &ast.Delete{StmtBase: ast.StmtBase{Pos: yyVAL.pos}, Targets: yyDollar[2].exprs}
		}
	case 117:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:904
		{
			yyVAL.stmt = &ast.Pass{StmtBase: ast.StmtBase{Pos: yyVAL.pos}}
		}
	case 118:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:910
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 119:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:914
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 120:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:918
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 121:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:922
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 122:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:926
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 123:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:932
		{
			yyVAL.stmt = &ast.Break{StmtBase: ast.StmtBase{Pos: yyVAL.pos}}
		}
	case 124:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:938
		{
			yyVAL.stmt = &ast.Continue{StmtBase: ast.StmtBase{Pos: yyVAL.pos}}
		}
	case 125:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:944
		{
			yyVAL.stmt = &ast.Return{StmtBase: ast.StmtBase{Pos: yyVAL.pos}}
		}
	case 126:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/grammar.y:948
		{
			yyVAL.stmt = &ast.Return{StmtBase: ast.StmtBase{Pos: yyVAL.pos}, Value: yyDollar[2].expr}
		}
	case 127:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:954
		{
			yyVAL.stmt = &ast.ExprStmt{StmtBase: ast.StmtBase{Pos: yyVAL.pos}, Value: yyDollar[1].expr}
		}
	case 128:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:960
		{
			yyVAL.stmt = &ast.Raise{StmtBase: ast.StmtBase{Pos: yyVAL.pos}}
		}
	case 129:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/grammar.y:964
		{
			yyVAL.stmt = &ast.Raise{StmtBase: ast.StmtBase{Pos: yyVAL.pos}, Exc: yyDollar[2].expr}
		}
	case 130:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/grammar.y:968
		{
			yyVAL.stmt = &ast.Raise{StmtBase: ast.StmtBase{Pos: yyVAL.pos}, Exc: yyDollar[2].expr, Cause: yyDollar[4].expr}
		}
	case 131:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:974
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 132:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:978
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 133:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/grammar.y:984
		{
			yyVAL.stmt = &ast.Import{StmtBase: ast.StmtBase{Pos: yyVAL.pos}, Names: yyDollar[2].aliases}
		}
	case 134:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:991
		{
			yyVAL.level = 1
		}
	case 135:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:995
		{
			yyVAL.level = 3
		}
	case 136:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:1001
		{
			yyVAL.level = yyDollar[1].level
		}
	case 137:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/grammar.y:1005
		{
			yyVAL.level += yyDollar[2].level
		}
	case 138:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:1011
		{
			yyVAL.level = 0
			yyVAL.str = yyDollar[1].str
		}
	case 139:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/grammar.y:1016
		{
			yyVAL.level = yyDollar[1].level
			yyVAL.str = yyDollar[2].str
		}
	case 140:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:1021
		{
			yyVAL.level = yyDollar[1].level
			yyVAL.str = ""
		}
	case 141:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:1028
		{
			yyVAL.aliases = []*ast.Alias{&ast.Alias{Pos: yyVAL.pos, Name: ast.Identifier("*")}}
		}
	case 142:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/grammar.y:1032
		{
			yyVAL.aliases = yyDollar[2].aliases
		}
	case 143:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/grammar.y:1036
		{
			yyVAL.aliases = yyDollar[1].aliases
		}
	case 144:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/grammar.y:1042
		{
			yyVAL.stmt = &ast.ImportFrom{StmtBase: ast.StmtBase{Pos: yyVAL.pos}, Module: ast.Identifier(yyDollar[2].str), Names: yyDollar[4].aliases, Level: yyDollar[2].level}
		}
	case 145:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:1048
		{
			yyVAL.alias = &ast.Alias{Pos: yyVAL.pos, Name: ast.Identifier(yyDollar[1].str)}
		}
	case 146:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/grammar.y:1052
		{
			yyVAL.alias = &ast.Alias{Pos: yyVAL.pos, Name: ast.Identifier(yyDollar[1].str), AsName: ast.Identifier(yyDollar[3].str)}
		}
	case 147:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:1058
		{
			yyVAL.alias = &ast.Alias{Pos: yyVAL.pos, Name: ast.Identifier(yyDollar[1].str)}
		}
	case 148:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/grammar.y:1062
		{
			yyVAL.alias = &ast.Alias{Pos: yyVAL.pos, Name: ast.Identifier(yyDollar[1].str), AsName: ast.Identifier(yyDollar[3].str)}
		}
	case 149:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:1068
		{
			yyVAL.aliases = nil
			yyVAL.aliases = append(yyVAL.aliases, yyDollar[1].alias)
		}
	case 150:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/grammar.y:1073
		{
			yyVAL.aliases = append(yyVAL.aliases, yyDollar[3].alias)
		}
	case 151:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:1079
		{
			yyVAL.aliases = nil
			yyVAL.aliases = append(yyVAL.aliases, yyDollar[1].alias)
		}
	case 152:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/grammar.y:1084
		{
			yyVAL.aliases = append(yyVAL.aliases, yyDollar[3].alias)
		}
	case 153:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:1090
		{
			yyVAL.str = yyDollar[1].str
		}
	case 154:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/grammar.y:1094
		{
			yyVAL.str += "." + yyDollar[3].str
		}
	case 155:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:1100
		{
			yyVAL.identifiers = nil
			yyVAL.identifiers = append(yyVAL.identifiers, ast.Identifier(yyDollar[1].str))
		}
	case 156:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/grammar.y:1105
		{
			yyVAL.identifiers = append(yyVAL.identifiers, ast.Identifier(yyDollar[3].str))
		}
	case 157:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/grammar.y:1111
		{
			yyVAL.stmt = &ast.Global{StmtBase: ast.StmtBase{Pos: yyVAL.pos}, Names: yyDollar[2].identifiers}
		}
	case 158:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/grammar.y:1117
		{
			yyVAL.stmt = &ast.Nonlocal{StmtBase: ast.StmtBase{Pos: yyVAL.pos}, Names: yyDollar[2].identifiers}
		}
	case 159:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:1123
		{
			yyVAL.exprs = nil
			yyVAL.exprs = append(yyVAL.exprs, yyDollar[1].expr)
		}
	case 160:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/grammar.y:1128
		{
			yyVAL.exprs = append(yyVAL.exprs, yyDollar[3].expr)
		}
	case 161:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/grammar.y:1134
		{
			yyVAL.stmt = &ast.Assert{StmtBase: ast.StmtBase{Pos: yyVAL.pos}, Test: yyDollar[2].expr}
		}
	case 162:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/grammar.y:1138
		{
			yyVAL.stmt = &ast.Assert{StmtBase: ast.StmtBase{Pos: yyVAL.pos}, Test: yyDollar[2].expr, Msg: yyDollar[4].expr}
		}
	case 163:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:1144
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 164:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:1148
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 165:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:1152
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 166:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:1156
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 167:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:1160
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 168:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:1164
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 169:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:1168
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 170:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:1172
		{
			yyVAL.stmt = yyDollar[1].stmt
		}
	case 171:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser/grammar.y:1177
		{
			yyVAL.ifstmt = nil
			yyVAL.lastif = nil
		}
	case 172:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser/grammar.y:1182
		{
			elifs := yyVAL.ifstmt
			newif := &ast.If{StmtBase: ast.StmtBase{Pos: yyVAL.pos}, Test: yyDollar[3].expr, Body: yyDollar[5].stmts}
			if elifs == nil {
				yyVAL.ifstmt = newif
			} else {
				yyVAL.lastif.Orelse = []ast.Stmt{newif}
			}
			yyVAL.lastif = newif
		}
	case 173:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser/grammar.y:1194
		{
			yyVAL.stmts = nil
		}
	case 174:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/grammar.y:1198
		{
			yyVAL.stmts = yyDollar[3].stmts
		}
	case 175:
		yyDollar = yyS[yypt-6 : yypt+1]
//line parser/grammar.y:1204
		{
			newif := &ast.If{StmtBase: ast.StmtBase{Pos: yyVAL.pos}, Test: yyDollar[2].expr, Body: yyDollar[4].stmts}
			yyVAL.stmt = newif
			elifs := yyDollar[5].ifstmt
			optional_else := yyDollar[6].stmts
			if len(optional_else) != 0 {
				if elifs != nil {
					yyDollar[5].lastif.Orelse = optional_else
					newif.Orelse = []ast.Stmt{elifs}
				} else {
					newif.Orelse = optional_else
				}
			} else {
				if elifs != nil {
					newif.Orelse = []ast.Stmt{elifs}
				}
			}
		}
	case 176:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser/grammar.y:1225
		{
			yyVAL.stmt = &ast.While{StmtBase: ast.StmtBase{Pos: yyVAL.pos}, Test: yyDollar[2].expr, Body: yyDollar[4].stmts, Orelse: yyDollar[5].stmts}
		}
	case 177:
		yyDollar = yyS[yypt-7 : yypt+1]
//line parser/grammar.y:1231
		{
			target := tupleOrExpr(yyVAL.pos, yyDollar[2].exprs, false)
			setCtx(yylex, target, ast.Store)
			yyVAL.stmt = &ast.For{StmtBase: ast.StmtBase{Pos: yyVAL.pos}, Target: target, Iter: yyDollar[4].expr, Body: yyDollar[6].stmts, Orelse: yyDollar[7].stmts}
		}
	case 178:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser/grammar.y:1238
		{
			yyVAL.exchandlers = nil
		}
	case 179:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/grammar.y:1242
		{
			exc := &ast.ExceptHandler{Pos: yyVAL.pos, ExprType: yyDollar[2].expr, Name: ast.Identifier(yyDollar[2].str), Body: yyDollar[4].stmts}
			yyVAL.exchandlers = append(yyVAL.exchandlers, exc)
		}
	case 180:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/grammar.y:1249
		{
			yyVAL.stmt = &ast.Try{StmtBase: ast.StmtBase{Pos: yyVAL.pos}, Body: yyDollar[3].stmts, Handlers: yyDollar[4].exchandlers}
		}
	case 181:
		yyDollar = yyS[yypt-7 : yypt+1]
//line parser/grammar.y:1253
		{
			yyVAL.stmt = &ast.Try{StmtBase: ast.StmtBase{Pos: yyVAL.pos}, Body: yyDollar[3].stmts, Handlers: yyDollar[4].exchandlers, Orelse: yyDollar[7].stmts}
		}
	case 182:
		yyDollar = yyS[yypt-7 : yypt+1]
//line parser/grammar.y:1257
		{
			yyVAL.stmt = &ast.Try{StmtBase: ast.StmtBase{Pos: yyVAL.pos}, Body: yyDollar[3].stmts, Handlers: yyDollar[4].exchandlers, Finalbody: yyDollar[7].stmts}
		}
	case 183:
		yyDollar = yyS[yypt-10 : yypt+1]
//line parser/grammar.y:1261
		{
			yyVAL.stmt = &ast.Try{StmtBase: ast.StmtBase{Pos: yyVAL.pos}, Body: yyDollar[3].stmts, Handlers: yyDollar[4].exchandlers, Orelse: yyDollar[7].stmts, Finalbody: yyDollar[10].stmts}
		}
	case 184:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:1267
		{
			yyVAL.withitems = nil
			yyVAL.withitems = append(yyVAL.withitems, yyDollar[1].withitem)
		}
	case 185:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/grammar.y:1272
		{
			yyVAL.withitems = append(yyVAL.withitems, yyDollar[3].withitem)
		}
	case 186:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/grammar.y:1278
		{
			yyVAL.stmt = &ast.With{StmtBase: ast.StmtBase{Pos: yyVAL.pos}, Items: yyDollar[2].withitems, Body: yyDollar[4].stmts}
		}
	case 187:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:1284
		{
			yyVAL.withitem = &ast.WithItem{Pos: yyVAL.pos, ContextExpr: yyDollar[1].expr}
		}
	case 188:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/grammar.y:1288
		{
			v := yyDollar[3].expr
			setCtx(yylex, v, ast.Store)
			yyVAL.withitem = &ast.WithItem{Pos: yyVAL.pos, ContextExpr: yyDollar[1].expr, OptionalVars: v}
		}
	case 189:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:1297
		{
			yyVAL.expr = nil
			yyVAL.str = ""
		}
	case 190:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/grammar.y:1302
		{
			yyVAL.expr = yyDollar[2].expr
			yyVAL.str = ""
		}
	case 191:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/grammar.y:1307
		{
			yyVAL.expr = yyDollar[2].expr
			yyVAL.str = yyDollar[4].str
		}
	case 192:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:1314
		{
			yyVAL.stmts = nil
			yyVAL.stmts = append(yyVAL.stmts, yyDollar[1].stmts...)
		}
	case 193:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/grammar.y:1319
		{
			yyVAL.stmts = append(yyVAL.stmts, yyDollar[2].stmts...)
		}
	case 194:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:1325
		{
			yyVAL.stmts = yyDollar[1].stmts
		}
	case 195:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/grammar.y:1329
		{
			yyVAL.stmts = yyDollar[3].stmts
		}
	case 196:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:1335
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 197:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser/grammar.y:1339
		{
			yyVAL.expr = &ast.IfExp{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, Test: yyDollar[3].expr, Body: yyDollar[1].expr, Orelse: yyDollar[5].expr}
		}
	case 198:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:1343
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 199:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:1349
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 200:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:1353
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 201:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/grammar.y:1359
		{
			args := &ast.Arguments{Pos: yyVAL.pos}
			yyVAL.expr = &ast.Lambda{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, Args: args, Body: yyDollar[3].expr}
		}
	case 202:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/grammar.y:1364
		{
			yyVAL.expr = &ast.Lambda{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, Args: yyDollar[2].arguments, Body: yyDollar[4].expr}
		}
	case 203:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/grammar.y:1370
		{
			args := &ast.Arguments{Pos: yyVAL.pos}
			yyVAL.expr = &ast.Lambda{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, Args: args, Body: yyDollar[3].expr}
		}
	case 204:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/grammar.y:1375
		{
			yyVAL.expr = &ast.Lambda{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, Args: yyDollar[2].arguments, Body: yyDollar[4].expr}
		}
	case 205:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:1381
		{
			yyVAL.expr = yyDollar[1].expr
			yyVAL.isExpr = true
		}
	case 206:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/grammar.y:1386
		{
			if !yyDollar[1].isExpr {
				boolop := yyVAL.expr.(*ast.BoolOp)
				boolop.Values = append(boolop.Values, yyDollar[3].expr)
			} else {
				yyVAL.expr = &ast.BoolOp{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, Op: ast.Or, Values: []ast.Expr{yyVAL.expr, yyDollar[3].expr}}
			}
			yyVAL.isExpr = false
		}
	case 207:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:1398
		{
			yyVAL.expr = yyDollar[1].expr
			yyVAL.isExpr = true
		}
	case 208:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/grammar.y:1403
		{
			if !yyDollar[1].isExpr {
				boolop := yyVAL.expr.(*ast.BoolOp)
				boolop.Values = append(boolop.Values, yyDollar[3].expr)
			} else {
				yyVAL.expr = &ast.BoolOp{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, Op: ast.And, Values: []ast.Expr{yyVAL.expr, yyDollar[3].expr}}
			}
			yyVAL.isExpr = false
		}
	case 209:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/grammar.y:1415
		{
			yyVAL.expr = &ast.UnaryOp{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, Op: ast.Not, Operand: yyDollar[2].expr}
		}
	case 210:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:1419
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 211:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:1425
		{
			yyVAL.expr = yyDollar[1].expr
			yyVAL.isExpr = true
		}
	case 212:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/grammar.y:1430
		{
			if !yyDollar[1].isExpr {
				comp := yyVAL.expr.(*ast.Compare)
				comp.Ops = append(comp.Ops, yyDollar[2].cmpop)
				comp.Comparators = append(comp.Comparators, yyDollar[3].expr)
			} else {
				yyVAL.expr = &ast.Compare{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, Left: yyVAL.expr, Ops: []ast.CmpOp{yyDollar[2].cmpop}, Comparators: []ast.Expr{yyDollar[3].expr}}
			}
			yyVAL.isExpr = false
		}
	case 213:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:1445
		{
			yyVAL.cmpop = ast.Lt
		}
	case 214:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:1449
		{
			yyVAL.cmpop = ast.Gt
		}
	case 215:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:1453
		{
			yyVAL.cmpop = ast.Eq
		}
	case 216:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:1457
		{
			yyVAL.cmpop = ast.GtE
		}
	case 217:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:1461
		{
			yyVAL.cmpop = ast.LtE
		}
	case 218:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:1465
		{
			yylex.(*yyLex).SyntaxError("invalid syntax")
		}
	case 219:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:1469
		{
			yyVAL.cmpop = ast.NotEq
		}
	case 220:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:1473
		{
			yyVAL.cmpop = ast.In
		}
	case 221:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/grammar.y:1477
		{
			yyVAL.cmpop = ast.NotIn
		}
	case 222:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:1481
		{
			yyVAL.cmpop = ast.Is
		}
	case 223:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/grammar.y:1485
		{
			yyVAL.cmpop = ast.IsNot
		}
	case 224:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/grammar.y:1491
		{
			yyVAL.expr = &ast.Starred{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, Value: yyDollar[2].expr, Ctx: ast.Load}
		}
	case 225:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:1497
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 226:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/grammar.y:1501
		{
			yyVAL.expr = &ast.BinOp{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, Left: yyDollar[1].expr, Op: ast.BitOr, Right: yyDollar[3].expr}
		}
	case 227:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:1507
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 228:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/grammar.y:1511
		{
			yyVAL.expr = &ast.BinOp{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, Left: yyDollar[1].expr, Op: ast.BitXor, Right: yyDollar[3].expr}
		}
	case 229:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:1517
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 230:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/grammar.y:1521
		{
			yyVAL.expr = &ast.BinOp{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, Left: yyDollar[1].expr, Op: ast.BitAnd, Right: yyDollar[3].expr}
		}
	case 231:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:1527
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 232:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/grammar.y:1531
		{
			yyVAL.expr = &ast.BinOp{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, Left: yyDollar[1].expr, Op: ast.LShift, Right: yyDollar[3].expr}
		}
	case 233:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/grammar.y:1535
		{
			yyVAL.expr = &ast.BinOp{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, Left: yyDollar[1].expr, Op: ast.RShift, Right: yyDollar[3].expr}
		}
	case 234:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:1541
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 235:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/grammar.y:1545
		{
			yyVAL.expr = &ast.BinOp{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, Left: yyDollar[1].expr, Op: ast.Add, Right: yyDollar[3].expr}
		}
	case 236:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/grammar.y:1549
		{
			yyVAL.expr = &ast.BinOp{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, Left: yyDollar[1].expr, Op: ast.Sub, Right: yyDollar[3].expr}
		}
	case 237:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:1555
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 238:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/grammar.y:1559
		{
			yyVAL.expr = &ast.BinOp{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, Left: yyDollar[1].expr, Op: ast.Mult, Right: yyDollar[3].expr}
		}
	case 239:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/grammar.y:1563
		{
			yyVAL.expr = &ast.BinOp{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, Left: yyDollar[1].expr, Op: ast.Div, Right: yyDollar[3].expr}
		}
	case 240:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/grammar.y:1567
		{
			yyVAL.expr = &ast.BinOp{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, Left: yyDollar[1].expr, Op: ast.Modulo, Right: yyDollar[3].expr}
		}
	case 241:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/grammar.y:1571
		{
			yyVAL.expr = &ast.BinOp{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, Left: yyDollar[1].expr, Op: ast.FloorDiv, Right: yyDollar[3].expr}
		}
	case 242:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/grammar.y:1577
		{
			yyVAL.expr = &ast.UnaryOp{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, Op: ast.UAdd, Operand: yyDollar[2].expr}
		}
	case 243:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/grammar.y:1581
		{
			yyVAL.expr = &ast.UnaryOp{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, Op: ast.USub, Operand: yyDollar[2].expr}
		}
	case 244:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/grammar.y:1585
		{
			yyVAL.expr = &ast.UnaryOp{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, Op: ast.Invert, Operand: yyDollar[2].expr}
		}
	case 245:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:1589
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 246:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/grammar.y:1595
		{
			yyVAL.expr = applyTrailers(yyDollar[1].expr, yyDollar[2].exprs)
		}
	case 247:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/grammar.y:1599
		{
			yyVAL.expr = &ast.BinOp{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, Left: applyTrailers(yyDollar[1].expr, yyDollar[2].exprs), Op: ast.Pow, Right: yyDollar[4].expr}
		}
	case 248:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser/grammar.y:1605
		{
			yyVAL.exprs = nil
		}
	case 249:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/grammar.y:1609
		{
			yyVAL.exprs = append(yyVAL.exprs, yyDollar[2].expr)
		}
	case 250:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:1615
		{
			yyVAL.obj = yyDollar[1].obj
		}
	case 251:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/grammar.y:1619
		{
			switch a := yyVAL.obj.(type) {
			case py.String:
				switch b := yyDollar[2].obj.(type) {
				case py.String:
					yyVAL.obj = a + b
				default:
					yylex.(*yyLex).SyntaxError("cannot mix string and nonstring literals")
				}
			case py.Bytes:
				switch b := yyDollar[2].obj.(type) {
				case py.Bytes:
					yyVAL.obj = append(a, b...)
				default:
					yylex.(*yyLex).SyntaxError("cannot mix bytes and nonbytes literals")
				}
			}
		}
	case 252:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/grammar.y:1640
		{
			yyVAL.expr = &ast.Tuple{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, Ctx: ast.Load}
		}
	case 253:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/grammar.y:1644
		{
			yyVAL.expr = yyDollar[2].expr
		}
	case 254:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/grammar.y:1648
		{
			yyVAL.expr = &ast.GeneratorExp{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, Elt: yyDollar[2].expr, Generators: yyDollar[3].comprehensions}
		}
	case 255:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/grammar.y:1652
		{
			yyVAL.expr = tupleOrExpr(yyVAL.pos, yyDollar[2].exprs, yyDollar[3].comma)
		}
	case 256:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/grammar.y:1656
		{
			yyVAL.expr = &ast.List{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, Ctx: ast.Load}
		}
	case 257:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/grammar.y:1660
		{
			yyVAL.expr = &ast.ListComp{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, Elt: yyDollar[2].expr, Generators: yyDollar[3].comprehensions}
		}
	case 258:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/grammar.y:1664
		{
			yyVAL.expr = &ast.List{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, Elts: yyDollar[2].exprs, Ctx: ast.Load}
		}
	case 259:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/grammar.y:1668
		{
			yyVAL.expr = &ast.Dict{ExprBase: ast.ExprBase{Pos: yyVAL.pos}}
		}
	case 260:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/grammar.y:1672
		{
			yyVAL.expr = yyDollar[2].expr
		}
	case 261:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:1676
		{
			yyVAL.expr = &ast.Name{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, Id: ast.Identifier(yyDollar[1].str), Ctx: ast.Load}
		}
	case 262:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:1680
		{
			yyVAL.expr = &ast.Num{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, N: yyDollar[1].obj}
		}
	case 263:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:1684
		{
			switch s := yyDollar[1].obj.(type) {
			case py.String:
				yyVAL.expr = &ast.Str{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, S: s}
			case py.Bytes:
				yyVAL.expr = &ast.Bytes{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, S: s}
			case *py.FString:
				yyVAL.expr = &ast.FString{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, Text: s.Text, Raw: s.Raw}
			default:
				panic("not Bytes or String in strings")
			}
		}
	case 264:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:1697
		{
			yyVAL.expr = &ast.Ellipsis{ExprBase: ast.ExprBase{Pos: yyVAL.pos}}
		}
	case 265:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:1701
		{
			yyVAL.expr = &ast.NameConstant{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, Value: py.None}
		}
	case 266:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:1705
		{
			yyVAL.expr = &ast.NameConstant{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, Value: py.True}
		}
	case 267:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:1709
		{
			yyVAL.expr = &ast.NameConstant{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, Value: py.False}
		}
	case 268:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/grammar.y:1716
		{
			yyVAL.expr = &ast.Call{ExprBase: ast.ExprBase{Pos: yyVAL.pos}}
		}
	case 269:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/grammar.y:1720
		{
			yyVAL.expr = yyDollar[2].call
		}
	case 270:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/grammar.y:1724
		{
			slice := yyDollar[2].slice
			// If all items of a ExtSlice are just Index then return as tuple
			if extslice, ok := slice.(*ast.ExtSlice); ok {
				elts := make([]ast.Expr, len(extslice.Dims))
				for i, item := range extslice.Dims {
					if index, isIndex := item.(*ast.Index); isIndex {
						elts[i] = index.Value
					} else {
						goto notAllIndex
					}
				}
				slice = &ast.Index{SliceBase: extslice.SliceBase, Value: &ast.Tuple{ExprBase: ast.ExprBase{Pos: extslice.SliceBase.Pos}, Elts: elts, Ctx: ast.Load}}
			notAllIndex:
			}
			yyVAL.expr = &ast.Subscript{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, Slice: slice, Ctx: ast.Load}
		}
	case 271:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/grammar.y:1742
		{
			yyVAL.expr = &ast.Attribute{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, Attr: ast.Identifier(yyDollar[2].str), Ctx: ast.Load}
		}
	case 272:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:1748
		{
			yyVAL.slice = yyDollar[1].slice
			yyVAL.isExpr = true
		}
	case 273:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/grammar.y:1753
		{
			if !yyDollar[1].isExpr {
				extSlice := yyVAL.slice.(*ast.ExtSlice)
				extSlice.Dims = append(extSlice.Dims, yyDollar[3].slice)
			} else {
				yyVAL.slice = &ast.ExtSlice{SliceBase: ast.SliceBase{Pos: yyVAL.pos}, Dims: []ast.Slicer{yyDollar[1].slice, yyDollar[3].slice}}
			}
			yyVAL.isExpr = false
		}
	case 274:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/grammar.y:1765
		{
			if yyDollar[2].comma && yyDollar[1].isExpr {
				yyVAL.slice = &ast.ExtSlice{SliceBase: ast.SliceBase{Pos: yyVAL.pos}, Dims: []ast.Slicer{yyDollar[1].slice}}
			} else {
				yyVAL.slice = yyDollar[1].slice
			}
		}
	case 275:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:1775
		{
			yyVAL.slice = &ast.Index{SliceBase: ast.SliceBase{Pos: yyVAL.pos}, Value: yyDollar[1].expr}
		}
	case 276:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:1779
		{
			yyVAL.slice = &ast.Slice{SliceBase: ast.SliceBase{Pos: yyVAL.pos}, Lower: nil, Upper: nil, Step: nil}
		}
	case 277:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/grammar.y:1783
		{
			yyVAL.slice = &ast.Slice{SliceBase: ast.SliceBase{Pos: yyVAL.pos}, Lower: nil, Upper: nil, Step: yyDollar[2].expr}
		}
	case 278:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/grammar.y:1787
		{
			yyVAL.slice = &ast.Slice{SliceBase: ast.SliceBase{Pos: yyVAL.pos}, Lower: nil, Upper: yyDollar[2].expr, Step: nil}
		}
	case 279:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/grammar.y:1791
		{
			yyVAL.slice = &ast.Slice{SliceBase: ast.SliceBase{Pos: yyVAL.pos}, Lower: nil, Upper: yyDollar[2].expr, Step: yyDollar[3].expr}
		}
	case 280:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/grammar.y:1795
		{
			yyVAL.slice = &ast.Slice{SliceBase: ast.SliceBase{Pos: yyVAL.pos}, Lower: yyDollar[1].expr, Upper: nil, Step: nil}
		}
	case 281:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/grammar.y:1799
		{
			yyVAL.slice = &ast.Slice{SliceBase: ast.SliceBase{Pos: yyVAL.pos}, Lower: yyDollar[1].expr, Upper: nil, Step: yyDollar[3].expr}
		}
	case 282:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/grammar.y:1803
		{
			yyVAL.slice = &ast.Slice{SliceBase: ast.SliceBase{Pos: yyVAL.pos}, Lower: yyDollar[1].expr, Upper: yyDollar[3].expr, Step: nil}
		}
	case 283:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/grammar.y:1807
		{
			yyVAL.slice = &ast.Slice{SliceBase: ast.SliceBase{Pos: yyVAL.pos}, Lower: yyDollar[1].expr, Upper: yyDollar[3].expr, Step: yyDollar[4].expr}
		}
	case 284:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:1813
		{
			yyVAL.expr = nil
		}
	case 285:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/grammar.y:1817
		{
			yyVAL.expr = yyDollar[2].expr
		}
	case 286:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:1823
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 287:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:1827
		{
			yyVAL.expr = yyDollar[1].expr
		}
	case 288:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:1833
		{
			yyVAL.exprs = nil
			yyVAL.exprs = append(yyVAL.exprs, yyDollar[1].expr)
		}
	case 289:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/grammar.y:1838
		{
			yyVAL.exprs = append(yyVAL.exprs, yyDollar[3].expr)
		}
	case 290:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/grammar.y:1844
		{
			yyVAL.exprs = yyDollar[1].exprs
			yyVAL.comma = yyDollar[2].comma
		}
	case 291:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/grammar.y:1851
		{
			elts := yyDollar[1].exprs
			if yyDollar[2].comma || len(elts) > 1 {
				yyVAL.expr = &ast.Tuple{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, Elts: elts, Ctx: ast.Load}
			} else {
				yyVAL.expr = elts[0]
			}
		}
	case 292:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/grammar.y:1862
		{
			yyVAL.exprs = yyDollar[1].exprs
		}
	case 293:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/grammar.y:1869
		{
			yyVAL.exprs = nil
			yyVAL.exprs = append(yyVAL.exprs, yyDollar[1].expr, yyDollar[3].expr) // key, value order
		}
	case 294:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser/grammar.y:1874
		{
			yyVAL.exprs = append(yyVAL.exprs, yyDollar[3].expr, yyDollar[5].expr)
		}
	case 295:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/grammar.y:1880
		{
			keyValues := yyDollar[1].exprs
			d := &ast.Dict{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, Keys: nil, Values: nil}
			for i := 0; i < len(keyValues)-1; i += 2 {
				d.Keys = append(d.Keys, keyValues[i])
				d.Values = append(d.Values, keyValues[i+1])
			}
			yyVAL.expr = d
		}
	case 296:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/grammar.y:1890
		{
			yyVAL.expr = &ast.DictComp{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, Key: yyDollar[1].expr, Value: yyDollar[3].expr, Generators: yyDollar[4].comprehensions}
		}
	case 297:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:1894
		{
			yyVAL.expr = &ast.Set{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, Elts: yyDollar[1].exprs}
		}
	case 298:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/grammar.y:1898
		{
			yyVAL.expr = &ast.SetComp{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, Elt: yyDollar[1].expr, Generators: yyDollar[2].comprehensions}
		}
	case 299:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser/grammar.y:1904
		{
			classDef := &ast.ClassDef{StmtBase: ast.StmtBase{Pos: yyVAL.pos}, Name: ast.Identifier(yyDollar[2].str), Body: yyDollar[5].stmts}
			yyVAL.stmt = classDef
			args := yyDollar[3].call
			if args != nil {
				classDef.Bases = args.Args
				classDef.Keywords = args.Keywords
				classDef.Starargs = args.Starargs
				classDef.Kwargs = args.Kwargs
			}
		}
	case 300:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:1918
		{
			yyVAL.call = yyDollar[1].call
		}
	case 301:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/grammar.y:1922
		{
			yyVAL.call.Args = append(yyVAL.call.Args, yyDollar[3].call.Args...)
			yyVAL.call.Keywords = append(yyVAL.call.Keywords, yyDollar[3].call.Keywords...)
		}
	case 302:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser/grammar.y:1928
		{
			yyVAL.call = &ast.Call{}
		}
	case 303:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/grammar.y:1932
		{
			yyVAL.call = yyDollar[1].call
		}
	case 304:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser/grammar.y:1937
		{
			yyVAL.call = &ast.Call{}
		}
	case 305:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/grammar.y:1941
		{
			yyVAL.call.Args = append(yyVAL.call.Args, yyDollar[3].call.Args...)
			yyVAL.call.Keywords = append(yyVAL.call.Keywords, yyDollar[3].call.Keywords...)
		}
	case 306:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/grammar.y:1948
		{
			yyVAL.call = yyDollar[1].call
		}
	case 307:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser/grammar.y:1952
		{
			call := yyDollar[1].call
			call.Starargs = yyDollar[3].expr
			if len(yyDollar[4].call.Args) != 0 {
				yylex.(*yyLex).SyntaxError("only named arguments may follow *expression")
			}
			call.Keywords = append(call.Keywords, yyDollar[4].call.Keywords...)
			yyVAL.call = call
		}
	case 308:
		yyDollar = yyS[yypt-8 : yypt+1]
//line parser/grammar.y:1962
		{
			call := yyDollar[1].call
			call.Starargs = yyDollar[3].expr
			call.Kwargs = yyDollar[7].expr
			if len(yyDollar[4].call.Args) != 0 {
				yylex.(*yyLex).SyntaxError("only named arguments may follow *expression")
			}
			call.Keywords = append(call.Keywords, yyDollar[4].call.Keywords...)
			yyVAL.call = call
		}
	case 309:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/grammar.y:1973
		{
			call := yyDollar[1].call
			call.Kwargs = yyDollar[3].expr
			yyVAL.call = call
		}
	case 310:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:1983
		{
			yyVAL.call = &ast.Call{}
			yyVAL.call.Args = []ast.Expr{yyDollar[1].expr}
		}
	case 311:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/grammar.y:1988
		{
			yyVAL.call = &ast.Call{}
			yyVAL.call.Args = []ast.Expr{
				&ast.GeneratorExp{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, Elt: yyDollar[1].expr, Generators: yyDollar[2].comprehensions},
			}
		}
	case 312:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/grammar.y:1995
		{
			yyVAL.call = &ast.Call{}
			test := yyDollar[1].expr
			if name, ok := test.(*ast.Name); ok {
				yyVAL.call.Keywords = []*ast.Keyword{&ast.Keyword{Pos: name.Pos, Arg: name.Id, Value: yyDollar[3].expr}}
			} else {
				yylex.(*yyLex).SyntaxError("keyword can't be an expression")
			}
		}
	case 313:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:2007
		{
			yyVAL.comprehensions = yyDollar[1].comprehensions
			yyVAL.exprs = nil
		}
	case 314:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:2012
		{
			yyVAL.comprehensions = yyDollar[1].comprehensions
			yyVAL.exprs = yyDollar[1].exprs
		}
	case 315:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser/grammar.y:2019
		{
			c := ast.Comprehension{
				Target: tupleOrExpr(yyVAL.pos, yyDollar[2].exprs, yyDollar[2].comma),
				Iter:   yyDollar[4].expr,
			}
			setCtx(yylex, c.Target, ast.Store)
			yyVAL.comprehensions = []ast.Comprehension{c}
		}
	case 316:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser/grammar.y:2028
		{
			c := ast.Comprehension{
				Target: tupleOrExpr(yyVAL.pos, yyDollar[2].exprs, yyDollar[2].comma),
				Iter:   yyDollar[4].expr,
				Ifs:    yyDollar[5].exprs,
			}
			setCtx(yylex, c.Target, ast.Store)
			yyVAL.comprehensions = []ast.Comprehension{c}
			yyVAL.comprehensions = append(yyVAL.comprehensions, yyDollar[5].comprehensions...)
		}
	case 317:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/grammar.y:2041
		{
			yyVAL.exprs = []ast.Expr{yyDollar[2].expr}
			yyVAL.comprehensions = nil
		}
	case 318:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/grammar.y:2046
		{
			yyVAL.exprs = []ast.Expr{yyDollar[2].expr}
			yyVAL.exprs = append(yyVAL.exprs, yyDollar[3].exprs...)
			yyVAL.comprehensions = yyDollar[3].comprehensions
		}
	case 319:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/grammar.y:2057
		{
			yyVAL.expr = &ast.Yield{ExprBase: ast.ExprBase{Pos: yyVAL.pos}}
		}
	case 320:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/grammar.y:2061
		{
			yyVAL.expr = &ast.YieldFrom{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, Value: yyDollar[3].expr}
		}
	case 321:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/grammar.y:2065
		{
			yyVAL.expr = &ast.Yield{ExprBase: ast.ExprBase{Pos: yyVAL.pos}, Value: yyDollar[2].expr}
		}
	}
	goto yystack /* stack new state and value */
}
