// Copyright 2022 The go-python Authors.  All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Package keyword provides the implementation of python's 'keyword' module.
//
// The module is data plus two predicates: the list of keywords the parser
// recognises, the list of soft keywords, and a membership test for each.
// There is no state and nothing to configure.
//
// One deliberate difference from CPython is noted on iskeyword below.

package keyword

import (
	"github.com/vishnukv64/gpython/py"
)

const module_doc = `Keywords (from "Grammar/python.gram")

This file is automatically generated; please don't muck it up!

To update the symbols in this file, 'cd' to the top directory of
the python source tree and run:

    PYTHONPATH=Tools/peg_generator python3 -m pegen.keywordgen \
        Grammar/python.gram \
        Grammar/Tokens \
        Lib/keyword.py

Alternatively, you can run 'make regen-keyword'.
`

// kwlist is CPython 3.14's keyword list, in CPython's order.  The order is
// part of the interface: the parser and code that reflects on it both read
// the list positionally, and it sorts the same way the source grammar does.
var kwlist = []string{
	"False",
	"None",
	"True",
	"and",
	"as",
	"assert",
	"async",
	"await",
	"break",
	"class",
	"continue",
	"def",
	"del",
	"elif",
	"else",
	"except",
	"finally",
	"for",
	"from",
	"global",
	"if",
	"import",
	"in",
	"is",
	"lambda",
	"nonlocal",
	"not",
	"or",
	"pass",
	"raise",
	"return",
	"try",
	"while",
	"with",
	"yield",
}

// softkwlist holds the soft keywords: names the parser can treat as keywords
// in some positions and as ordinary identifiers elsewhere.  A program may
// still use "match" or "type" as a variable, so they are kept separate from
// kwlist.
var softkwlist = []string{
	"_",
	"case",
	"match",
	"type",
}

// stringsToObjects converts a Go string slice to the Python list of str that
// the module exports.
func stringsToObjects(words []string) *py.List {
	items := make([]py.Object, len(words))
	for i, w := range words {
		items[i] = py.String(w)
	}
	return py.NewListFromItems(items)
}

// membership builds one of the two predicates.  name is used in the error
// message and words is the set to test against.
func membership(name string, words []string) *py.Method {
	// CPython builds the predicate as frozenset(kwlist).__contains__; a plain
	// Go map is the same membership test, and the argument is a string by the
	// time it is looked up.
	set := make(map[string]bool, len(words))
	for _, w := range words {
		set[w] = true
	}
	return py.MustNewMethod(name, func(self py.Object, args py.Tuple) (py.Object, error) {
		var s py.Object
		if err := py.UnpackTuple(args, py.StringDict{}, name, 1, 1, &s); err != nil {
			return nil, err
		}
		// CPython's iskeyword is frozenset(kwlist).__contains__, so a
		// non-string simply misses and answers False.  This module is
		// stricter and rejects a non-string instead: a caller passing
		// something that is not a string has a bug that a silent False would
		// hide.  Every caller in the wild passes the result of
		// str.isidentifier(), so nothing is lost.
		str, ok := s.(py.String)
		if !ok {
			return nil, py.ExceptionNewf(py.TypeError, "%s() argument must be str, not %s", name, s.Type().Name)
		}
		return py.NewBool(set[string(str)]), nil
	}, 0, "Return True if s is a keyword.")
}

func init() {
	globals := py.NewStringDictFrom(
		py.DictEntry{Key: "kwlist", Value: stringsToObjects(kwlist)},
		py.DictEntry{Key: "softkwlist", Value: stringsToObjects(softkwlist)},
		py.DictEntry{Key: "iskeyword", Value: membership("iskeyword", kwlist)},
		py.DictEntry{Key: "issoftkeyword", Value: membership("issoftkeyword", softkwlist)},
	)
	globals.Set("__all__", py.NewListFromItems([]py.Object{
		py.String("kwlist"),
		py.String("softkwlist"),
		py.String("iskeyword"),
		py.String("issoftkeyword"),
	}))

	py.RegisterModule(&py.ModuleImpl{
		Info: py.ModuleInfo{
			Name: "keyword",
			Doc:  module_doc,
		},
		Globals: globals,
	})
}
